### ISSUE TITLE
Network Protocol Error

### ISSUE THREAD

**Issue by fanlepian1** [ReplayMod/ReplayMod#1000]
In the Velocity proxy server, use the TAB plugin. Upon entering this server to record playback, opening the playback will prompt a Network Protocol Error.
On the Github of TAB, you can see issues related to this.
[TAB issues](https://github.com/NEZNAMY/TAB/issues/1341)
This link may help you

**Comment by Johni0702** [comment]
This has been fixed by ReplayMod 2.6.19 released Sep 9th.
