### ISSUE TITLE
Connection Lost Network Protocol Error

### ISSUE THREAD

**Issue by buni-gutz** [ReplayMod/ReplayMod#1002]
Whenever I try to play a recording, i always get this message. i am playing on singleplayer 1.20.6 with fabric 0.16.4
there's no option to update the mod and i have turned off the display chat option.
[latest.log](https://github.com/user-attachments/files/17182342/latest.log)

**Comment by Johni0702** [comment]
You're using an old ReplayMod version (2.6.18); the latest version released on Sep 9 is 2.6.19 and fixes a bunch of Network Protocol Error issues.
Please update and if the issue still happens with the latest version, please also attach the affected replay file.
