### ISSUE TITLE
Replay never loads

### ISSUE THREAD

**Issue by vindognz** [ReplayMod/ReplayMod#1004]
I recorded a Replay of a Hoplite Battle Royale game in the Hoplite for Lunar Client modpack, featuring ReplayMod. I then attempt to replay the recording and it gets stuck on the resourcepack loading screen and never finishes. No errors. nothing.

edit:
it eventually does load sometimes and i either get instantly smacked with a `Network Protocol Error`. This or my 12 minute long replay only plays 1 second before finishing.

**Comment by vindognz** [comment]
I can provide a video of this happening if you need

**Comment by vindognz** [comment]
* replays work perfectly fine in the Hoplite pregame lobbies but not in an actual game

**Comment by vindognz** [comment]
ooh i have new information! Lunar Client just released Mission Control which lets you easily view logs and I can see this:

[a51be178-86a7-4caf-99e5-21064212ae2e-master.log](https://github.com/user-attachments/files/17594769/a51be178-86a7-4caf-99e5-21064212ae2e-master.log)

(full logs from Minecraft boot, opening a replay, then it network protocol errors me)

**Comment by Johni0702** [comment]
Update the mod.
