### ISSUE TITLE
Replay Mod rendered videos are corrupted

### ISSUE THREAD

**Issue by Carnagee0300** [ReplayMod/ReplayMod#1008]
I not sure why happen this, sometimes work but sometimes when i try use shaders this problem happen:

<img width="1280" alt="bug" src="https://github.com/user-attachments/assets/885a7401-b5c1-4f75-ba00-a8f9230bf3de">

**Comment by Syhmac** [comment]
It's the problem with shaders. Either use different shaders or don't use any at all.
