### ISSUE TITLE
When I add replay mod to the feather client always is error with other mods i dont have this problem only replay mod

### ISSUE THREAD

**Issue by xMerfi** [ReplayMod/ReplayMod#1010]
![image](https://github.com/user-attachments/assets/dbea8ae9-368a-4139-a9a5-83d750a761da)
![image](https://github.com/user-attachments/assets/83158889-a7dc-4c1f-b156-4feb6cd5e364)
When I tried in the lunar client it works but i prefer to play on the feather client can you help me?

Thank you in advance.

xMerfi

**Comment by xMerfi** [comment]
i can do english version if u want couse polish is a bit hard XD

**Comment by Johni0702** [comment]
If it only happens with Feather, then it's likely an issue on their end and you should go contact them.
The crash report in that screenshot is wholly incomplete and the interesting bits are further up. Should just attach the entire log as a file instead of screenshotting one part of it.
