### ISSUE TITLE
Add ability to look in chests like regular spectator mode when viewing replays

### ISSUE THREAD

**Issue by Tyopo131** [ReplayMod/ReplayMod#1017]
Would be cool if you could look inside chests or other GUIs when viewing a replay. Maybe even GUI keyframes where a portion of the render is spent looking at a GUI.

You can already view a player's inventory while spectating.

**Comment by Syhmac** [comment]
Replay mode is not a spectator mode. It doesn't save any information about player's inventory or any containers like chests.
