### ISSUE TITLE
Crash when you click the stop button in the game.

### ISSUE THREAD

**Issue by PhantomX12123** [ReplayMod/ReplayMod#103]
When I record a timelapse. I press the stop button in the menu. And when I go to the main menu of minecraft, write to me that there was a failure what to do?

Failure shale:

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2020-02-11 17:08:58 YEKT
Description: Saving replay file

java.io.IOException: decoding
    at com.replaymod.replaystudio.io.ReplayInputStream.fillBuffer(ReplayInputStream.java:233)
    at com.replaymod.replaystudio.io.ReplayInputStream.readPacket(ReplayInputStream.java:184)
    at com.replaymod.editor.gui.MarkerProcessor.apply(MarkerProcessor.java:146)
    at com.replaymod.recording.packet.PacketListener.lambda$channelInactive$8(PacketListener.java:225)
    at com.replaymod.recording.packet.PacketListener$$Lambda$1776/1994259462.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Value otg has no mapping for key class com.replaymod.lib.com.github.steveice10.mc.protocol.data.game.world.WorldType.
    at com.replaymod.lib.com.github.steveice10.mc.protocol.data.MagicValues.key(MagicValues.java:1081)
    at com.replaymod.lib.com.github.steveice10.mc.protocol.packet.ingame.server.ServerJoinGamePacket.read(ServerJoinGamePacket.java:80)
    at com.replaymod.lib.com.github.steveice10.packetlib.tcp.TcpPacketCodec.decode(TcpPacketCodec.java:41)
    at com.replaymod.replaystudio.studio.protocol.StudioCodec.decode(StudioCodec.java:42)
    at com.replaymod.replaystudio.io.ReplayInputStream.fillBuffer(ReplayInputStream.java:229)
    ... 5 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 2366029192 bytes (2256 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_E3 101 mods loaded, 101 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                   | Version                  | Source                                            | Signature                                |
       |:------ |:-------------------- |:------------------------ |:------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft            | 1.12.2                   | minecraft.jar                                     | None                                     |
       | LCHIJA | mcp                  | 9.42                     | minecraft.jar                                     | None                                     |
       | LCHIJA | FML                  | 8.0.99.99                | forge-1.12.2-14.23.5.2847.jar                     | None                                     |
       | LCHIJA | forge                | 14.23.5.2847             | forge-1.12.2-14.23.5.2847.jar                     | None                                     |
       | LCHIJA | creativecoredummy    | 1.0.0                    | minecraft.jar                                     | None                                     |
       | LCHIJA | otgcore              | 1.12.2 - v7              | minecraft.jar                                     | None                                     |
       | LCHIJA | smoothfontcore       | mc1.12.2-1.16            | minecraft.jar                                     | None                                     |
       | LCHIJA | foamfixcore          | 7.7.4                    | minecraft.jar                                     | None                                     |
       | LCHIJA | dsurroundcore        | 3.5.4.3                  | minecraft.jar                                     | None                                     |
       | LCHIJA | randompatches        | 1.12.2-1.16.1.0          | randompatches-1.12.2-1.16.1.0.jar                 | None                                     |
       | LCHIJA | smoothfont           | mc1.12.2-1.16.2          | SmoothFont-mc1.12.2-1.16.2.jar                    | None                                     |
       | LCHIJA | replaymod            | 1.12.2-2.2.0-b7          | replaymod-1.12.2-2.2.0-b7.jar                     | None                                     |
       | LCHIJA | rpghud               | 3.6.6.2                  | [1.12]+RPG-HUD-3.6.6.2.jar                        | None                                     |
       | LCHIJA | aiimprovements       | 0.0.1.3                  | AIImprovements-1.12-0.0.1b3.jar                   | None                                     |
       | LCHIJA | antiqueatlas         | 4.5.0                    | antiqueatlas_1.12.2_4.5.0.jar                     | e631d7254e451d0360d0148cb21407d5511d45e9 |
       | LCHIJA | antiqueatlasoverlay  | 1.2                      | antiqueatlas_1.12.2_4.5.0.jar                     | e631d7254e451d0360d0148cb21407d5511d45e9 |
       | LCHIJA | jei                  | 4.15.0.268               | jei_1.12.2-4.15.0.268.jar                         | None                                     |
       | LCHIJA | appleskin            | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                        | None                                     |
       | LCHIJA | quark                | r1.5-159                 | Quark-r1.5-159.jar                                | None                                     |
       | LCHIJA | autoreglib           | 1.3-30                   | AutoRegLib-1.3-30.jar                             | None                                     |
       | LCHIJA | backpacks16840       | 3.5.6                    | backpacks+1.12.2+-+3.5.6.jar                      | None                                     |
       | LCHIJA | ichunutil            | 7.1.4                    | iChunUtil-1.12.2-7.1.4.jar                        | None                                     |
       | LCHIJA | backtools            | 7.0.0                    | BackTools-1.12.2-7.0.0.jar                        | None                                     |
       | LCHIJA | baubles              | 1.5.2                    | Baubles-1.12-1.5.2.jar                            | None                                     |
       | LCHIJA | baubleshud           | 5.0.2                    | BaublesHud-1.12.2-5.0.2.jar                       | None                                     |
       | LCHIJA | betterunderground    | 1.1.2                    | Better-Underground-Mod-1.12.2.jar                 | None                                     |
       | LCHIJA | betterbuilderswands  | 0.13.2                   | BetterBuildersWands-1.12.2-0.13.2.271+5997513.jar | None                                     |
       | LCHIJA | betternether         | 0.1.8.3                  | betternether-0.1.8.3.jar                          | None                                     |
       | LCHIJA | bibliocraft          | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar                 | None                                     |
       | LCHIJA | openterraingenerator | v6                       | OpenTerrainGenerator-1.12.2+-+v6.jar              | e9f7847a78c5342af5b0a9e04e5abc0b554d69e0 |
       | LCHIJA | biomebundle          | 5.1                      | Biome_Bundle-1.12.2-v6.1.jar                      | None                                     |
       | LCHIJA | bookshelf            | 2.3.577                  | Bookshelf-1.12.2-2.3.577.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | bullseye             | 3.0.7                    | Bullseye-1.12.2-3.0.7.jar                         | None                                     |
       | LCHIJA | campfire             | 1.2                      | campfire-1.12-v1.2.jar                            | None                                     |
       | LCHIJA | clienttweaks         | 3.1.11                   | ClientTweaks_1.12.2-3.1.11.jar                    | None                                     |
       | LCHIJA | clumps               | 3.1.2                    | Clumps-3.1.2.jar                                  | None                                     |
       | LCHIJA | colytra              | 1.2.0                    | colytra-1.12.2-1.2.0.jar                          | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | LCHIJA | coralreef            | 2.0                      | CoralReef-2.5-1.12.2.jar                          | None                                     |
       | LCHIJA | igcm                 | 1.2.2                    | igcm_v1.2.10_mc1.12.2.jar                         | None                                     |
       | LCHIJA | creativecore         | 1.9.9                    | creativecore_v1.9.74_mc1.12.2.jar                 | None                                     |
       | LCHIJA | cxlibrary            | 1.6.1                    | cxlibrary-1.12.1-1.6.1.jar                        | None                                     |
       | LCHIJA | dungeontactics       | DT-0.16.5                | DungeonTactics-1.12.2-0.16.5.jar                  | None                                     |
       | LCHIJA | eerieentities        | 1.0.6                    | EerieEntities-1.12.2-1.0.6.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | ebwizardry           | 4.1.4                    | Electroblob's+Wizardry+-+4.1.4+-+MC+1.12.2.jar    | None                                     |
       | LCHIJA | familiarfauna        | 1.0.11                   | FamiliarFauna-1.12.2-1.0.11.jar                   | None                                     |
       | LCHIJA | fastbench            | 1.7.0                    | FastWorkbench-1.12.2-1.7.0.jar                    | None                                     |
       | LCHIJA | foamfix              | 0.10.5-1.12.2            | foamfix-0.10.5-1.12.2.jar                         | None                                     |
       | LCHIJA | cfm                  | 6.3.0                    | furniture-6.3.0-1.12.2.jar                        | None                                     |
       | LCHIJA | gottschcore          | 1.7.0                    | GottschCore-mc1.12.2-f14.23.5.2768-v1.7.0.jar     | None                                     |
       | LCHIJA | grapplemod           | 1.12.2-v11.1             | grapplemod-v11.1-1.12.2.jar                       | None                                     |
       | LCHIJA | hammercore           | 2.0.4.7                  | HammerCore-1.12.2-2.0.4.7.jar                     | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | LCHIJA | huntingdim           | 1.0.38                   | HuntingDimension-1.12.2-1.0.38.jar                | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | waila                | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                       | None                                     |
       | LCHIJA | llibrary             | 1.7.19                   | llibrary-1.7.19-1.12.2.jar                        | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHIJA | iceandfire           | 1.7.1                    | iceandfire-1.7.1-1.12.2.jar                       | None                                     |
       | LCHIJA | inventorytweaks      | 1.64+dev.132.bd1e422     | InventoryTweaks-1.64+dev.132.jar                  | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCHIJA | jaff                 | 1.7_for_1.12             | JustAFewFish-1.7_for_1.12.jar                     | None                                     |
       | LCHIJA | jeresources          | 0.8.10.50                | JustEnoughResources-1.12.2-0.8.10.50.jar          | None                                     |
       | LCHIJA | login_shield         | 1.12.2-3-g7c6e7ac        | Login_Shield-1.12.2-3-g7c6e7ac.jar                | None                                     |
       | LCHIJA | malisiscore          | 1.12.2-6.5.1-SNAPSHOT    | malisiscore-1.12.2-6.5.1.jar                      | None                                     |
       | LCHIJA | malisisdoors         | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                     | None                                     |
       | LCHIJA | mantle               | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                          | None                                     |
       | LCHIJA | megaloot             | 0.2.30                   | megaloot-1.12.2-0.2.30.jar                        | None                                     |
       | LCHIJA | millenaire           | Millénaire 7.2.1         | millenaire-1.12.2-7.2.1.jar                       | None                                     |
       | LCHIJA | mobdismemberment     | 7.0.0                    | MobDismemberment-1.12.2-7.0.0.jar                 | None                                     |
       | LCHIJA | mobends              | 0.24                     | mobends-0.24_for_MC-1.12.jar                      | None                                     |
       | LCHIJA | morefurnaces         | 1.10.5                   | MoreFurnaces-1.12.2-1.10.6.jar                    | None                                     |
       | LCHIJA | mousetweaks          | 2.10                     | MouseTweaks-2.10-mc1.12.2.jar                     | None                                     |
       | LCHIJA | mowziesmobs          | 1.5.4                    | mowziesmobs-1.5.4.jar                             | None                                     |
       | LCHIJA | naturescompass       | 1.5.1                    | NaturesCompass-1.12.2-1.5.1.jar                   | None                                     |
       | LCHIJA | nofirespread         | 1.12.2.003               | NoFireSpread-1.12.2.003.jar                       | None                                     |
       | LCHIJA | yurtmod              | 9.3.2                    | NomadicTents[1.12.2]-9.3.2.jar                    | None                                     |
       | LCHIJA | placeableitems       | 3.3                      | placeableitems-3.3.jar                            | None                                     |
       | LCHIJA | randomtweaks         | 1.12.2-2.5.0.6           | randomtweaks-1.12.2-2.5.0.6.jar                   | 20d08fb3fe9c268a63a75d337fb507464c8aaccd |
       | LCHIJA | redstonepaste        | 1.7.5                    | redstonepaste-mc1.12-1.7.5.jar                    | None                                     |
       | LCHIJA | additionalstructures | 2.2.2                    | Rex's-Additional-Structures-1.12.x-(v.2.2.2).jar  | None                                     |
       | LCHIJA | ropebridge           | 2.0.5                    | ropebridge-1.12-2.0.7.jar                         | None                                     |
       | LCHIJA | rustic               | 1.1.0                    | rustic-1.1.0.jar                                  | None                                     |
       | LCHIJA | soundfilters         | 0.10_for_1.12            | SoundFilters-0.10_for_1.12.jar                    | None                                     |
       | LCHIJA | spawntemple          | 2.1                      | SpawnTemple-v.2.1-mc1.12.jar                      | None                                     |
       | LCHIJA | specialmobs          | 1.0.2_for_mc1.12.2       | specialmobs-1.0.2_for_mc1.12.2.jar                | None                                     |
       | LCHIJA | stg                  | 1.11.2-1.1.2             | stg-1.11.2-1.1.2.jar                              | None                                     |
       | LCHIJA | surge                | 2.0.77                   | Surge-1.12.2-2.0.77.jar                           | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | sync                 | 7.0.2                    | Sync-1.12.2-7.0.2.jar                             | None                                     |
       | LCHIJA | thaumcraft           | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar                  | None                                     |
       | LCHIJA | twilightforest       | 3.8.689                  | twilightforest-1.12.2-3.8.689-universal.jar       | None                                     |
       | LCHIJA | tconstruct           | 1.12.2-2.12.0.135        | TConstruct-1.12.2-2.12.0.135.jar                  | None                                     |
       | LCHIJA | tcinventoryscan      | 2.0.10                   | ThaumicInventoryScanning_1.12.2-2.0.10.jar        | None                                     |
       | LCHIJA | thaumicjei           | 1.6.0                    | ThaumicJEI-1.12.2-1.6.0-27.jar                    | None                                     |
       | LCHIJA | thaumicperiphery     | 0.3.0                    | thaumicperiphery-0.3.0.jar                        | None                                     |
       | LCHIJA | tinkersjei           | 1.2                      | tinkersjei-1.2.jar                                | None                                     |
       | LCHIJA | tinkertoolleveling   | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar               | None                                     |
       | LCHIJA | totemic              | 1.12.2-0.11.6            | Totemic-1.12.2-0.11.6.jar                         | 21d11d7bf4d97b465382a1f95428029aac6daaea |
       | LCHIJA | treasure2            | 1.3.0                    | Treasure2-mc1.12.2-f14.23.5.2768-v1.3.0.jar       | None                                     |
       | LCHIJA | vanillafix           | 1.0.10-SNAPSHOT          | VanillaFix-1.0.10-99.jar                          | None                                     |
       | LCHIJA | visuals              | 6r                       | Visuals-1.12.2-6r.jar                             | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | LCHIJA | waystones            | 4.0.67                   | Waystones_1.12.2-4.0.67.jar                       | None                                     |
       | LCHIJA | orelib               | 3.5.2.2                  | OreLib-1.12.2-3.5.2.2.jar                         | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | dsurround            | 3.5.4.3                  | DynamicSurroundings-1.12.2-3.5.4.3.jar            | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | phosphor-lighting    | 1.12.2-0.2.4             | phosphor-1.12.2-0.2.4+build46-universal.jar       | f0387d288626cc2d937daa504e74af570c52a2f1 |
       | LCHIJA | vt                   | 1.4.7                    | VanillaTweaks-1.4.7.jar                           | None                                     |
  Loaded coremods (and transformers): Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      HCASM (HammerCore-1.12.2-2.0.4.7.jar)
                                        com.zeitheron.hammercore.asm.HammerCoreTransformer
                                      OTGCorePlugin (OTG-Core.jar)
                                        com.pg85.otg.forge.asm.OTGClassTransformer
                                      CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
                                        cubex2.cxlibrary.CoreModTransformer
                                      RandomPatches (randompatches-1.12.2-1.16.1.0.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
                                      NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
                                        net.fybertech.nwr.NWRTransformer
                                      BCModPlugin (backpacks+1.12.2+-+3.5.6.jar)
                                        brad16840.core.ClassTransformer
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      IGCMPatchingLoader (igcm_v1.2.10_mc1.12.2.jar)
                                        com.creativemd.igcm.core.IGCMTransformer
                                      LoadingPlugin (replaymod-1.12.2-2.2.0-b7.jar)
                                        
                                      PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.4+build46-universal.jar)
                                        
                                      Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.132.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      CorePlugin (SmoothFont-mc1.12.2-1.16.2.jar)
                                        bre.smoothfont.asm.Transformer
                                      Quark Plugin (Quark-r1.5-159.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
                                        
                                      SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
                                        
                                      ColytraLoadingPlugin (colytra-1.12.2-1.2.0.jar)
                                        c4.colytra.asm.ElytraTransformer
                                      CreativePatchingLoader (creativecore_v1.9.74_mc1.12.2.jar)
                                        
                                      DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
                                        org.orecruncher.dsurround.asm.Transformer
  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
                           OreDictionary Info: Registered 489 names; 695 stacks.
                           Pastebin Connection: Okay.
                           Dependent Mods:
                               -Visuals (visuals) @6r
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - wailaIntegration (Enabled/Not Forced)
  Suspected Mods: Replay Mod (replaymod)

**Comment by Johni0702** [comment]
The current implementation of the Start/Stop/Pause/Resume feature is fairly incompatible with third-party mods. In this particular case, it's the OpenTerrainGenerator mod which it doesn't know how to deal with. This may improve in the future but don't wait for it.

You should usually be able to find the raw, uncut replay file in `.minecraft/replay_files/raw/`, just move it up one folder and you should be able to play it.
