### ISSUE TITLE
Compatibility with Minecraft 1.15+

### ISSUE THREAD

**Issue by cbergmann** [ReplayMod/ReplayMod#104]
Hi there,

To be clear upfront I know that this is a spare time project mainly by @CrushedPixel and @Johni0702 and I am graceful for the time that they invested in this project for the community. We as a user community have no right to demand any progress or even a plan regarding any future releases.
On the other hand I am interested in how we might be able to help continuing this great project into the future.

I have searched a little bit and did not find a official post about the current status or the future of this project. I only found two tweets in this direction: [1] confirms that you ( @CrushedPixel ) are currently not working on a Version for 1.15 and [2] rumors that "a certain SciCrafter picking it up". 

I Just want to post this issue here for people searching for a 1.15 compatible version to keep them updated and maybe as a point to announce something in the future if there is something to announce.

Thanks again for all the hard work
Clemens

[1] https://twitter.com/CrushedPixel/status/1205576730943066113
[2] https://twitter.com/KumiCharizard/status/1206599899967455232

**Comment by Johni0702** [comment]
I was able to work on the ReplayMod at my full time job for the last couple of weeks.
As a result, a 1.15.2 compatible version is now available for download at https://www.replaymod.com/download/.
