### ISSUE TITLE
Can't enter a world

### ISSUE THREAD

**Issue by AverageComet250** [ReplayMod/ReplayMod#108]
Hi, I have been using the replay mod recently on multiMC but I've ran into an issue. when using optifine 1.14.4 F5 and optifabric 0.7.1, I can't open any of my worlds. It does the loading screen, says 100% and then crashes after seeing the void and the replay start. In the multiMC log, it says exited with code -1, instead of 0.Does anyone know whats happening. my fabric api version is 0.4.1+build.245-1.14. the edit was a spelling mistake

**Comment by Johni0702** [comment]
There should be a button in MultiMC to upload your entire log. Please click it and then post the link here.

**Comment by AverageComet250** [comment]
I have six crash reports and four logs. They are in this github repository: 
https://github.com/AverageComet250/ReplayModCrashes

**Comment by Johni0702** [comment]
Looks more like an issue with Optifabric than with the ReplayMod.

**Comment by AverageComet250** [comment]
thanks for the help, but if i do one or the other it works perfectly fine. Does this mean that i currently can't use optifine and the replay mod, or do you know a solution/bypass?

**Comment by Johni0702** [comment]
Are you certain that just Optifabric + Fabric API but without ReplayMod is working fine?
From the crash report it looks like your version of Optifabric isn't compatible with your version of Fabric API.

**Comment by AverageComet250** [comment]
i haven't tested that. I tested optifabric + optifine and Fabric API + Replay Mod. I'll test it now

**Comment by AverageComet250** [comment]
i get the same error/crash with optifabric + optifine + Fabric API. My current API version is: [1.14.4] Fabric API 0.4.1 build 245. What version do you recommend.

**Comment by Johni0702** [comment]
I haven't played MC in quite some time, so idk. In general, the latest version is the best option. If you're already using the latest version, check their pages for any explicit requirements and if there aren't, try reaching out to the optifabric people.

Closing since this isn't RM-specific.
