### ISSUE TITLE
1.8.9 Not working

### ISSUE THREAD

**Issue by Triliton** [ReplayMod/ReplayMod#11]
Hello,

I was wondering why version Replay Mod v1.8.9-2.0.0-b5 wont work.

I use Forge 11.15.1.1738
The other mods i have start fine, like Conquest Reforge mod and more creatures.
But even in the mod list this mod isnt listed. It hasnt been loaded by Forge.

Do i need a different Forge version or is it not compatible with any other mods?

**Comment by CrushedPixel** [comment]
For such issues, please visit the ReplayMod forums and post the full game log, issue description etc.
