### ISSUE TITLE
Cannot save recorded file when i use "Realistic Terrain Gen"

### ISSUE THREAD

**Issue by 1103kash** [ReplayMod/ReplayMod#111]
hi there, thanks for awesome work.
cuz im not native speaker of english, so sorry for my poor language skill...

Im playing minecraft 1.12.2 with Realistic Terrain Gen which add worldtype to minecraft.
and i wanna use replay mod in that world type but i cannot because there are not mentioning of that world type. but im not good at java... i struggled to find how to fix it but icannot.

there are also people who wanna use biomes'o plenty with this mod.

please help me TT

and this is crash report.

[crash-2020-03-23_16.03.30-client.txt](https://github.com/ReplayMod/ReplayMod/files/4393652/crash-2020-03-23_16.03.30-client.txt)

**Comment by Johni0702** [comment]
Known issue with certain third-party mods (in this particular case OTG): #69
See the last paragraph of my first reply over there for a workaround.
