### ISSUE TITLE
can you give us source code of MagicValues.class?

### ISSUE THREAD

**Issue by 1103kash** [ReplayMod/ReplayMod#114]
to make compatible with the mod which adding world type, we have to rewrite magic values....
is there source code of magic values.class or can you give us by paypaling to some extent?

**Comment by Johni0702** [comment]
The `MagicValues` is part of MCProtocolLib. You can find our fork of it here: https://github.com/ReplayMod/MCProtocolLib
And the mapping from MC version to the specific commit: https://github.com/ReplayMod/ReplayStudio/blob/be6a6809fee61fe518141e0c435f738916f30c88/versions/common.gradle#L68-L80

Note that I will not be accepting PRs adding support for specific mods as I do not see that as a viable long-term strategy. You are however ofc free to redistribute modified versions of the mod provided you follow [its license](https://github.com/ReplayMod/ReplayMod/blob/develop/LICENSE.md).
