### ISSUE TITLE
Crash when running with optifine

### ISSUE THREAD

**Issue by Venomfall** [ReplayMod/ReplayMod#115]
I don't know if there's some version of optifabric and optifine that work with replay compared to others, but I had seen old posts on the forums saying that optifine was compatible (even though i'm unable to log into forums due to some bug). For whatever reason, the game will launch fine using optifine and replay, but it will crash upon trying to load into the world. It may be that the latest version of replay isn't compatible with optifine yet, but I couldn't find ANYTHING anywhere about it, so I figured I'd ask here.

Replay Version
```1.14.4-2.2.0-b7```
Fabric Api Version
```0.4.1 Build 245```
Optifine Version
```Optifine 1.14.4 F2```
Optifabric Version
```optifabric 0.7.1```

**Comment by Venomfall** [comment]
Also if you would like logs I can post them, just ask.

**Comment by Johni0702** [comment]
Please post the crash report. Or better, the full client log (which should contain the crash report as well).
Also make sure your Optifine version is compatible with your Optifabric version, i.e. that it works without RM.

**Comment by Venomfall** [comment]
Thanks for the suggestions, turns out it's got more to do with the optifabric and optifine versions, than replay, which is confusing seeing as they're both the most stable ones for 1.14. I guess we can call this one closed then. Thanks for the help.
