### ISSUE TITLE
No "Pause Recording" or "Stop Recording"

### ISSUE THREAD

**Issue by Zenot1c** [ReplayMod/ReplayMod#117]
Hi there! I know this is an old version of the mod, but thought i would still post it:

When running on 1.12.2 Forge, there is no "Pause Recording" or "Stop Recording" buttons upon pressing ESC. How would i get these or is this a bug? Is there a keybind that I can use instead?
![image](https://user-images.githubusercontent.com/60157591/77860560-e6c18080-7207-11ea-8b73-690fb079d4d9.png)
Is this a known issue without a fix, or is this easily fixable?
Thanks in advance!

**Comment by Johni0702** [comment]
> I know this is an old version of the mod

The Start/Stop/Pause/Resume feature was added in `2.2.0-b1`.
