### ISSUE TITLE
[1.11.2] java.lang.IllegalAccessError: tried to access field net.minecraft.client.Minecraft.field_71428_T

### ISSUE THREAD

**Issue by SteveKunG** [ReplayMod/ReplayMod#12]
This line caused this issue : https://github.com/ReplayMod/ReplayMod/blob/1.11.2/src/main/java/com/replaymod/replay/ReplayModReplay.java#L158
http://pastebin.com/fnQ6q3uK

**Comment by liach** [comment]
Weird, this method is already AT'd. https://github.com/ReplayMod/ReplayMod/blob/1.11.2/src/main/resources/META-INF/replaymod_at.cfg#L4

**Comment by SteveKunG** [comment]
Yes, Its already have access transformer. Optifine conflict?

**Comment by SteveKunG** [comment]
Tested with latest Forge 2530 of 1.11.2 this no longer happened.
