### ISSUE TITLE
[1.15] Using Shaders via OptiFabric causes blocks to not render

### ISSUE THREAD

**Issue by drewc5131** [ReplayMod/ReplayMod#122]
On a freshly compiled build of the 1.15.2 branch, i tried rendering a clip using shaders, as that's what I typically do when using replay mod, but the result only showed entities
![image](https://user-images.githubusercontent.com/31282527/78458809-38dc2900-7682-11ea-865e-c8daea5d94e6.png)

Disabling shaders, while still having optifine with optifabric enabled works fine
![image](https://user-images.githubusercontent.com/31282527/78458819-4c878f80-7682-11ea-8b00-a823cf44d2ff.png)

I am using OptiFine 1.15.2 HD U G1 pre13, again, with OptiFabric

**Comment by Johni0702** [comment]
Expected. I haven't done anything with OF on 1.15 yet (will get to it next week). I'm quite frankly surprised it even works with shaders disabled.

**Comment by drewc5131** [comment]
Alright cool. However, I have noticed it does seem to randomly just lock up completely when i render sometimes, I haven't tested without optifine so I dont know if its an issue with optifine or just the mod in general, but just something for you to keep in mind

**Comment by Kas-tle** [comment]
For me it locks up even without shaders. I wish that I had logs for you to post, but unfortunately it just hangs and I have to stop the process, so I don't really get any information in the log.

**Comment by drewc5131** [comment]
> 
> 
> For me it locks up even without shaders. I wish that I had logs for you to post, but unfortunately it just hangs and I have to stop the process, so I don't really get any information in the log.

Thats what I meant, it locks up without shaders as well

**Comment by Xanton19** [comment]
For me, it locks up when I have Optifine with Optifabric installed, no matter with or without shaders. So Optifine and Optifabric are not compatible with Replaymod and lock up. Try rendering in Vanilla, it works for me.

**Comment by DevTime2** [comment]
Replay mod in OBT or CBT?

**Comment by Xanton19** [comment]
@DevTime2 Can you please explain, what you mean with "OBT" and "CBT"?

**Comment by DevTime2** [comment]
> @DevTime2 Can you please explain, what you mean with "OBT" and "CBT"?

Open Beta Test and Close Beta Test

**Comment by Xanton19** [comment]
@DevTime2 Don't take my word for it, but I think it's an open beta because the code in the 1.15 branch is accessible and compilable.

**Comment by DevTime2** [comment]
> @DevTime2 Don't take my word for it, but I think it's an open beta because the code in the 1.15 branch is accessible and compilable.

Ok, thanks

**Comment by Johni0702** [comment]
Is this happening for you with all shaders?
I tried the `(internal)` shaders (please try them as well) and `Sildurs Vibrant Shaders v1.262 Lite` and I'm unable to reproduce the lack of blocks.

OF G1 pre13, Optifabric 1.0.0-beta8

**Comment by Kas-tle** [comment]
@Johni0702 I've tried with internal shaders, as well as the a few of the 1.15 shaders they released. I am able to use the client, but once I start the render with the default settings, the client just freezes up. I tried letting it hang for a few minutes, but pretty much just stayed that way until I forced a stop. I will attempt to compile the latest branch and see if there is any change.

**Comment by Kas-tle** [comment]
I have determined that, in my case and a friend at least (spec wise his computer is much better than mine, in terms of both GPU and CPU. I'm on the very low end for MC with a 2015 macbook, i7-3740QM and iris integrated graphics), we both seem to have the same issue. Setting the render distance to above 8 seems to cause the render to hang sometimes. Whether or not the hanging occurs seems to depend on the length of the render and render distance setting, but going above 12 seemed to consistently cause a hang regardless of render length.

**Comment by drewc5131** [comment]
I haven't tried any other shaders, i am using [BSL 7.1.03.2](https://bitslablab.com/). It's not the most recent version, but the most recent version has this stupid option that you cant change that adds ripples into rain reflections which kinda hurts the style im going for, so i don't upgrade that, but again the pack works fine in game with the same version, so i dont see why that could cause an issue.
I am also using Optifine preview 10 instead of 13, as it is causing some weird graphical effects, but i DID try with 13 and it still is the same issue.

**Comment by Kas-tle** [comment]
@drewc5131 have you tried with default settings (moving ofoption, options, and shaderoptions somewhere else and allowing the configs to regenerate). I believe these are different issues, but definetely would be valuable to check if its some kind of a settings issue. Also, might want to try with the most recent of preview for consistency's sake.

**Comment by Johni0702** [comment]
![](https://i.johni0702.de/llBdz.png)
Hm, even with that specific version of BSL and all default settings it's still rendering the blocks.
@drewc5131 Could you try with all default settings as Kas-tle suggested (and on pre13)? Make sure to keep backups of your current settings so we can actually figure out which one caused it.

**Comment by Kas-tle** [comment]
Well I am also now having this issue with all shaderpacks... for me it was also settings related as setting everything to another folder did the trick... since shaders more or less destroy my computer, it would probably take me a while to track down what exactly is doing this, so I will attach my settings if anyone wants to take a try before I am able to get to it. If you could attach yours as well @drewc5131 we might be able to narrow down the culprit.

[options.txt](https://github.com/ReplayMod/ReplayMod/files/4448324/options.txt)
[optionsof.txt](https://github.com/ReplayMod/ReplayMod/files/4448325/optionsof.txt)
[optionsshaders.txt](https://github.com/ReplayMod/ReplayMod/files/4448326/optionsshaders.txt)

**Comment by Johni0702** [comment]
I can indeed reproduce it with the configs provided by @Kas-tle. Though not with all shaders, e.g. `(internal)` works fine either way but BSL is broken.
I'll try to do some diffing with the configs to figure out which option is responsible.

**Comment by Johni0702** [comment]
Update: Diffing didn't actually yield any result, I was still able to reproduce the issue even with all default configs (instead, it appears to be related to when exactly shaders are enabled, i.e. loading vs menu vs ingame, not entirely sure though as many things could trigger the issue).
Being able to reproduce the issue, I threw the debugger at it and fairly quickly realized what was wrong. Above commit should fix it.

**Comment by Kas-tle** [comment]
Yeah, my bad. I also realized after that for me, it seemed to have to do with where I was on the top timeline before starting the render, so it was just a fluke that the issue went away after changing my configuration. Sorry about that. Will check against these changes.
