### ISSUE TITLE
How i can install the fabric api?

### ISSUE THREAD

**Issue by D1maScherb** [ReplayMod/ReplayMod#128]
I don’t know how to install it, please share a lesson with me. I think it can be installed as a regular mod, but I don’t know where to insert the .jar file. And sorry me for my english :D (im rus)

**Comment by Johni0702** [comment]
> I think it can be installed as a regular mod

You answered your own question. Fabric API (not to be confused with the Fabric Loader) is installed just like any regular mod: You just drop it into your mods folder (and the Fabric Loader will then load it from there).
