### ISSUE TITLE
Skin not rendering.

### ISSUE THREAD

**Issue by yoerithor** [ReplayMod/ReplayMod#129]
Hya, I'm back again :D

When viewing the recording in the replay viewer it shows the skin perfectly fine, but it just shows a Steve skin after render...

Any ideas?
Thanks <3

**Comment by Johni0702** [comment]
Could you explain a bit more how you're getting it to show the steve skin? It doesn't for me.
Also, which version are you using? I'm assuming 39ccf60 but just to be sure (and for the record cause that's not going to be the most recent one for ever).

**Comment by yoerithor** [comment]
Render: https://imgur.com/a/SrOqHzw
replay-viewer/original skin: https://imgur.com/a/XRUfRMY
Yes, still on 39ccf60 1.15.2. With optifabric & optifine. Tried with shaders enabled and disabled, bot the same result.
