### ISSUE TITLE
No Forge Version for 1.14.4

### ISSUE THREAD

**Issue by BlueDuckYT** [ReplayMod/ReplayMod#130]
Fabric might be easier to implement, but it pretty much restricts the usage of it to vanilla Minecraft.  With Forge it would be compatible with most mods and modpacks.

**Comment by Xanton19** [comment]
I have heard that there will not be a forge version of Replaymod, but there is something called [PatchworkMC](https://patchworkmc.net/), which is in the early stages of development. It attempts to run forge mods on fabric in the future.

**Comment by Xanton19** [comment]
[Here ](https://github.com/ReplayMod/ReplayMod/issues/90)is an explanation of why it is not on forge 1.14.4
