### ISSUE TITLE
Rendering GUI isn't show correctly in 1.15.2

### ISSUE THREAD

**Issue by JimHan75d8c5** [ReplayMod/ReplayMod#131]
<img width="1238" alt="1" src="https://user-images.githubusercontent.com/50871214/79295483-612e1800-7f0b-11ea-9de6-2cc512a96128.png">
<img width="1274" alt="2" src="https://user-images.githubusercontent.com/50871214/79295490-62f7db80-7f0b-11ea-874b-1188649668fa.png">

OS: macOS 10.15.4
Minecraft: 1.15.2 with farbic
```  
$ java -version
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)
```

**Comment by Johni0702** [comment]
Which specific version are you using?
Did you resize the window while rendering or was it broken right from the beginning?

**Comment by JimHan75d8c5** [comment]
I'm using commit 39ccf60f15cee1780d13db16bfd99d041a55f0c9.
The window is broken from the beginning.
But I found that `Video Rendered` page can be fixed by resize windows.

**Comment by Johni0702** [comment]
Having difficulties reproducing this.
Could you provide me your current values for:
- "Video Resolution" in the render settings
- "Anti-Aliasing" in the render settings
- "GUI Scale" in MC's video settings
- The size of your Minecraft window (This is visible on the fourth line on right side of the F3 menu. If the timeline is in the way, you can open the Player Overview by pressing `B` which should hide the timeline but still show the F3 menu: https://i.johni0702.de/eehex.png)

If you happen to have access to a non-macOS device, could you check if you can reproduce the issue there?

> But I found that Video Rendered page can be fixed by resizing windows.

So, resizing while it's still rendering doesn't fix it? Only when it's done?

**Comment by JimHan75d8c5** [comment]
- Video Resolution: 2560x1440, 1920x1080
 - Anti-Aliasing: None
 - GUI Scale: Auto
 - Minecraft window size: 2560x1440  (setting in MultiMC is 1280x720)
 - Resizing while it's still rendering doesn't fix it.
 - The window is broken in 1.14.4 & 1.15.2, work fine in 1.12.2.
I will try on Windows later.

**Comment by Johni0702** [comment]
Hm, still cannot reproduce it.

Could you check if the latest version makes any differences? (it fixes an issue with similar symptoms but that should only occur if one holds down the Ctrl key when clicking the render button)

Could you also check whether this was always an issue or just a regression introduced in the 1.15 update by testing the 2.2.0-b7 version ([direct link](https://minio.replaymod.com/replaymod/replaymod-1.14.4-2.2.0-b7.jar))?

**Comment by JimHan75d8c5** [comment]
- a733d301fda9e037e31ad7bb0e12a3c8d16eb762 (1.15.2): broken
- a733d301fda9e037e31ad7bb0e12a3c8d16eb762 (1.14.4): broken
- 2.2.0-b7 (1.14.4): broken
- 2.2.0-b7 (1.12.2): work fine

without holding down `control` : 
![1-2](https://user-images.githubusercontent.com/50871214/79630904-ca21c400-8187-11ea-8bf4-5f7e77643d31.jpg)
![1-3](https://user-images.githubusercontent.com/50871214/79630905-cbeb8780-8187-11ea-8363-6d52c236c169.jpg)
![1-4](https://user-images.githubusercontent.com/50871214/79630907-cee67800-8187-11ea-9172-f291579adc1b.jpg) 
holding down `control` :
![2-1](https://user-images.githubusercontent.com/50871214/79630908-d0b03b80-8187-11ea-8990-f9112754f925.jpg)
![2-2](https://user-images.githubusercontent.com/50871214/79630910-d279ff00-8187-11ea-8abd-6a2e0ee1cfe1.jpg)
![2-3](https://user-images.githubusercontent.com/50871214/79630911-d443c280-8187-11ea-9f3d-3d8ad98adc16.jpg)
![2-4](https://user-images.githubusercontent.com/50871214/79630914-d6a61c80-8187-11ea-9952-529b0f55efae.jpg)

**Comment by JimHan75d8c5** [comment]
Enable "FullScreen" will solve this issue. @Johni0702
