### ISSUE TITLE
Crash while saving replay

### ISSUE THREAD

**Issue by LogicalGeekBoy** [ReplayMod/ReplayMod#134]
In the latest build (replaymod-1.15.2-2.2.0-b7-67-g39ccf60.jar) a tester has reported a crash and loss of replay file while exiting the game. They also tried using the start/stop buttons within the game but these also resulted in the same issue.

[crash-2020-04-13_09.38.37-client.txt](https://github.com/ReplayMod/ReplayMod/files/4488376/crash-2020-04-13_09.38.37-client.txt)

Here is a different user crash report but looks similar to me (may or may not be the same issue):

[REPLAY_CRASH_04_14_2020.txt](https://github.com/ReplayMod/ReplayMod/files/4488404/REPLAY_CRASH_04_14_2020.txt)

**Comment by Johni0702** [comment]
The lost replay file should be in `.minecraft/replay_recordings/raw/`, just in their uncut form (cause cutting is what failed). If the testers would still like to make use of them, one can just move them up into the normal replay_recordings folder and they should start appearing in the normal replay list.

Would be great if I could somehow get my hands on one of the two (the crash reports do indeed look like they're caused the same same bug) raw replay as that would allow me to easily reproduce the issue myself.

**Comment by LogicalGeekBoy** [comment]
The timestamps for the files in the `raw`  folder don't match 100% but we think these are the replays:

* https://drive.google.com/open?id=19wRMO_cqz08Szp6HPd_7HCVzI4BRBTKM
* https://drive.google.com/open?id=1Mg71uNKwGcV6h9vtI5W7bN9dHwoQc6yV

**Comment by Johni0702** [comment]
Tyvm, I'm indeed able to reproduce the issue with the replay in the first zip, that should make fixing it fairly easy.
Second zip didn't contain a replay though, it contained a world. But don't worry about it, one reproduction case should probably be enough for this one.
