### ISSUE TITLE
Crash while rendering

### ISSUE THREAD

**Issue by LogicalGeekBoy** [ReplayMod/ReplayMod#135]
All I know about this crash was that it happened while rendering using the latest build:

[latest.log](https://github.com/ReplayMod/ReplayMod/files/4488412/latest.log)

**Comment by Johni0702** [comment]
There isn't actually any crash in that log file. It just abruptly ends, it's also incomplete in that it's missing stuff at the start.

Do you have any info on how it "crashed" (i.e. did it really crash or was it just frozen and the tester killed it?) and whether there's a crash report somewhere (maybe it just didn't make it into the log) or a "hs_err_pid…" file (which would likely indicate a faulty graphics driver)?

**Comment by kareemAlramlawi** [comment]
here are the logs that I got from startup to crash while rendering:

21:30:06.255
Starting C:\Users\karee\AppData\Roaming\.minecraft\ffmpeg\bin\ffmpeg.exe with args: -y -f rawvideo -pix_fmt bgra -s 1920x1080 -r 60 -i - -an -c:v libx264 -preset ultrafast -pix_fmt yuv420p "test2.mp4"
21:30:08.580
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 4/23/20 9:30 PM
Description: Rendering video

java.lang.RuntimeException: GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT
	at net.minecraft.class_276.method_1239(class_276.java:146)
	at net.minecraft.class_276.method_1231(class_276.java:123)
	at net.minecraft.class_276.method_22596(class_276.java:65)
	at net.minecraft.class_276.method_1234(class_276.java:54)
	at com.replaymod.render.rendering.VideoRenderer.drawGui(VideoRenderer.java:437)
	at com.replaymod.render.rendering.VideoRenderer.updateForNextFrame(VideoRenderer.java:216)
	at com.replaymod.render.capturer.SimplePboOpenGlFrameCapturer.process(SimplePboOpenGlFrameCapturer.java:55)
	at com.replaymod.render.capturer.SimplePboOpenGlFrameCapturer.process(SimplePboOpenGlFrameCapturer.java:13)
	at com.replaymod.render.rendering.Pipeline.run(Pipeline.java:71)
	at com.replaymod.render.rendering.VideoRenderer.renderVideo(VideoRenderer.java:175)
	at com.replaymod.render.gui.GuiRenderSettings$8.run(GuiRenderSettings.java:239)
	at com.replaymod.core.ReplayMod.lambda$runLater$5(ReplayMod.java:493)
	at com.replaymod.core.ReplayMod$$Lambda$1641/371271246.run(Unknown Source)
	at net.minecraft.class_1255.method_18859(class_1255.java:144)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:118)
	at net.minecraft.class_1255.method_5383(class_1255.java:103)
	at com.replaymod.core.ReplayMod$ReplayModExecutor.method_5383(ReplayMod.java:472)
	at com.replaymod.replay.InputReplayTimer.method_1658(InputReplayTimer.java:72)
	at net.minecraft.class_310.method_1523(class_310.java:953)
	at net.minecraft.class_310.method_1514(class_310.java:619)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 839870240 bytes (800 MB) / 3019898880 bytes (2880 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric: Fabric API 0.7.1+build.301-1.15
		fabric-api-base: Fabric API Base 0.1.2+b7f9825d0c
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.5+3b05f68e0c
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea890c
		fabric-climbable-api-v1: Fabric Climbable API (v1) 1.0.0+e40501d40c
		fabric-commands-v0: Fabric Commands (v0) 0.1.2+b7f9825d0c
		fabric-containers-v0: Fabric Containers (v0) 0.1.3+b7f9825d0c
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825d0c
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d0c
		fabric-dimensions-v1: fabric-dimensions-v1 0.3.0+2ad156310c
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.0+fac69e320c
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+003643510c
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.6+ec40b2e10c
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+dfdb52d60c
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.5+e08a73050c
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+ec951ea40c
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d60c
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.3+e08a73050c
		fabric-networking-v0: Fabric Networking (v0) 0.1.7+003643510c
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.4+ec951ea40c
		fabric-particles-v1: fabric-particles-v1 0.1.2+ad2f81bd0c
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.6+f3d8141b0c
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.10+f08b61330c
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.23+9290e2ed0c
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a600c
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d0c
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+12515ed90c
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104900c
		fabric-rendering-v1: Fabric Rendering (v1) 0.1.0+003643510c
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.10+06c939b30c
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+abd915800c
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba70c
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.0.2+915c44630c
		fabricloader: Fabric Loader 0.8.2+build.194
		minecraft: Minecraft 1.15.2
		replaymod: Replay Mod 1.15.2-2.3.0-b1
21:30:08.604
OpenGL debug message, id=1286, source=API, type=ERROR, severity=HIGH, message=Error has been generated. GL error GL_INVALID_FRAMEBUFFER_OPERATION in (null): (ID: 4012793211) framebuffer 4, "" is not complete
21:30:08.604
OpenGL debug message, id=1286, source=API, type=ERROR, severity=HIGH, message=Error has been generated. GL error GL_INVALID_FRAMEBUFFER_OPERATION in (null): (ID: 173538523) Generic error

**Comment by kareemAlramlawi** [comment]
Also after I closed the crash log from the mod, I clicked "render" then it flashed this few times until it fully shown.
![15876673011773731916807450455629](https://user-images.githubusercontent.com/64222733/80137014-4151c080-85ab-11ea-8107-68eb65963a8d.jpg)

**Comment by kareemAlramlawi** [comment]
OK, Minecraft crashed on me here is the rest:

 21:36:35.653
Starting C:\Users\karee\AppData\Roaming\.minecraft\ffmpeg\bin\ffmpeg.exe with args: -y -f rawvideo -pix_fmt bgra -s 1920x1080 -r 60 -i - -an -c:v libx264 -preset ultrafast -pix_fmt yuv420p "test2.mp4"
21:43:33.459

21:43:33.459
Process crashed with exit code -805306369

**Comment by kareemAlramlawi** [comment]
just in case.
![image](https://user-images.githubusercontent.com/64222733/80139169-ad81f380-85ae-11ea-9402-31aaad6613a3.png)

**Comment by Johni0702** [comment]
@kareemAlramlawi Did you by any chance minimize the window while RM was rendering?
For complicated reasons I've never actually done that myself during development and someone reported a similar looking crash which is triggered by minimizing the window: https://github.com/ReplayMod/ReplayMod/issues/140

Also, in general please open a new issue unless you're certain your problem is the same as an existing one. And since we don't actually have the crash report for this one, we can't know if the issue reported by OP is the same as the one you're having (unless you're the person for whom OP has forwarded the logs, in that case you were right to post here).

**Comment by kareemAlramlawi** [comment]
ok sorry, I will delete them here and repost them there.

**Comment by kareemAlramlawi** [comment]
@Johni0702 hmm I never done that. I will tell you more details about it in #140 after around 7 hours.
