### ISSUE TITLE
[Bug] Crash when minimizing game window during render

### ISSUE THREAD

**Issue by i0xHeX** [ReplayMod/ReplayMod#140]
**Steps to reproduce:**

1. Setup paths on your replay
2. Begin rendering 
3. Minimize game window

**Expected behavior:**
Continue rendering

**Unexpected behavior:**
It crashes with weird UI allowing to copy the logs
https://i.imgur.com/5IjI3zc.png
https://i.imgur.com/TDR6JJi.png

https://pastebin.com/Lnwgtsbm

**Info:**
- Windows 10 x64
- Java 14 (OpenJDK)
- Replay Mod 2.3.0 b1 (1.15.2)

**Comment by kareemAlramlawi** [comment]
@Johni0702 Hi again, here is some more details using 60 frames video in this link
because the file is around 200MB:
https://transferxl.com/08XWCvy2gDbF6
