### ISSUE TITLE
[1.15.2]The mod does not record the map

### ISSUE THREAD

**Issue by Lapis-kun** [ReplayMod/ReplayMod#146]
Before using the mod to record any building process, I tested it by just placing and breaking some blocks, but in the replay viewer and in the exported video I only can see my avatar in the void.

[test.zip](https://github.com/ReplayMod/ReplayMod/files/4535161/test.zip)

**Comment by Johni0702** [comment]
That sounds like a conflict with another mod. Do you have any other mods installed?

If you attach the replay file with the seemingly empty world, I'll can check if it's actually empty or just not displaying properly.

**Comment by Johni0702** [comment]
Closing due to lack of useful info.
