### ISSUE TITLE
Reply says 00:00 is recorded and nothing is shows up

### ISSUE THREAD

**Issue by AKASGaming** [ReplayMod/ReplayMod#147]
I spent 30 minutes (To be fair I should have tested to make sure the mod works first) recording a video and it didn't even record. It said "saving replay" for about 3 minutes and when I looked for the file, it said 00:00 and when I clicked it it gets stuck on the Minecraft background loading screen.

![image](https://user-images.githubusercontent.com/25405047/80552902-ae8b9a00-898d-11ea-933e-4c67b942459f.png)

![image](https://user-images.githubusercontent.com/25405047/80553007-f1e60880-898d-11ea-8ec3-2a3091028739.png)

I'm using:

- replaymod-1.15.2-2.3.0-b1.jar
- fabric-api-0.7.1+build.301-1.15.jar
- Fabric Loader: 0.8.2+build.194

Thanks in advance!

**Comment by Johni0702** [comment]
There should be another replay file in `.minecraft/replay_recordings/raw/`. Please upload that file somewhere so I can have a look at it.

**Comment by AKASGaming** [comment]
> There should be another replay file in `.minecraft/replay_recordings/raw/`. Please upload that file somewhere so I can have a look at it.

[https://file.io/1izxbhRA](https://file.io/1izxbhRA
)

**Comment by AKASGaming** [comment]
So, iv'e narrowed it down. It creates 2 files. One is the whole video, and the other is an empty file.

![image](https://user-images.githubusercontent.com/25405047/80646214-f19f4900-8a31-11ea-98d8-af95855c7dbc.png)

**Comment by xxfast** [comment]
An empty 00:00 file is always created from the looks of it - looks like a bug to me
