### ISSUE TITLE
Got corrupted mess when rendering video

### ISSUE THREAD

**Issue by TheReaperLord** [ReplayMod/ReplayMod#148]
[I got this when I rendered it out](https://youtu.be/t_LwbjG35wM) I assume this would be better suited on the forum but I can't log in there for some reason.

**Comment by Johni0702** [comment]
Please attach screenshots of your render settings and the game log of when you rendered it.

**Comment by TheReaperLord** [comment]
[Screenshot](https://imgur.com/a/dtG1WMH)

Command line settings:
-y -f rawvideo -pix_fmt rgb24 -s %WIDTH%x%HEIGHT% -r %FPS% -i - -an -c:v libx264 -preset ultrafast -pix_fmt yuv420p "%FILENAME%"

not sure how to get the log? I assume it is in appdata

**Comment by Johni0702** [comment]
Ah, no need for the log, looks like command line setting is invalid, it should be `bgra` not `rgb24`.
You can reset it by temporarily selecting a different preset.

It should probably be automatically reset when upgrading from an old version. Keeping this issue open until that is implemented.

**Comment by TheReaperLord** [comment]
I'll that to render, first time took roughly 1 and a half hours so will get back if that works, should probably make a smaller test render. 
Not sure why it was changed.
Thanks so much!

**Comment by TheReaperLord** [comment]
That worked! little 10 second render came out fine.
I think this can be closed

**Comment by Johni0702** [comment]
> Not sure why it was changed.

The new version has significantly better render performance with most GPUs.

> I think this can be closed

I'd like to keep this issue open until I've implemented a check which automatically resets the command line argument when upgrading from an older version.
