### ISSUE TITLE
1.15.2 Rendering hung up

### ISSUE THREAD

**Issue by lenrik1589** [ReplayMod/ReplayMod#150]
When pressing Render Rendering Video GUI appears but then game hangs up forever (14h) (the best i could get ~760 frames but other times - 0 frames)
The sad thing is: No crash, no error, it just stops.
![Screenshot from 2020-05-01 00-30-39](https://user-images.githubusercontent.com/48890625/80761411-31a22100-8b43-11ea-92b3-90f281ef0127.png)
java 14; fabric 0.8.2+build.194; Ubuntu 19.10; intel i3-7100u with integrated graphics; ffmpeg version 4.1.4-1build2; fabric api 0.5.1+build.294-1.15

**Comment by OscarleBG** [comment]
I got the same on one of my recordings, but when I try on another one with less camera movement, it does not stop

**Comment by lenrik1589** [comment]
> when I try on another one with less camera movement, it does not stop
Won't do for me sadly :(

**Comment by Johni0702** [comment]
Could you try to use [VisualVM] to grab about 5 or so thread dumps of the game while it is frozen (with at least a second apart each)?

[VisualVM]: https://visualvm.github.io/

Also, would you mind sharing one of the replays with the exact camera path already configured and the value of your render distance setting, so I can check if it happens on my machine as well?

And just to verify: You're using ReplayMod 1.15.2-2.3.0-b1 and no Optifine is involved, correct?

**Comment by lenrik1589** [comment]
http://www.mediafire.com/file/m5e43fzgwcwahs4/ReplayModGithub.zip/file, that version of replay mod, no optifine, but sodium's present

**Comment by Johni0702** [comment]
Could you try it without Sodium? It appears to change the way chunk updates are handled and the RM depends on MC internals in that area (because it wants to wait for all chunks to be loaded/updated before rendering each frame). So, the likelihood for conflict there is quite high (e.g. OF also does something in that area and it did cause the rendering to freeze until I added code to the RM specifically to address OF. seems likely Sodium would need specific handling as well).

**Comment by lenrik1589** [comment]
oh yea, issue resolves w/o sodium but if sodium will support fabric rendering API will it work?

**Comment by Johni0702** [comment]
No, it's specifically Sodium's changes to `ChunkBuilder`'s scheduling which makes [RM's changes](https://github.com/ReplayMod/ReplayMod/blob/8e05a67c5e898b52262ea328fe2af23f593d4b4f/src/main/java/com/replaymod/render/mixin/Mixin_BlockOnChunkRebuilds.java) no longer function properly.

**Comment by jellysquid3** [comment]
I think we could add a small API to Sodium in the near future so other mods can block until all chunk updates are uploaded. We re-implement large swaths of the renderer to get the maximum parallelization of chunk updates, so things are a bit different on our side.

```java
// Get the chunk renderer for the specified world
ISodiumChunkRenderer renderer = SodiumAPI.IMPL.getChunkRenderer(world);
// Block until all chunk updates in the work queue are uploaded
renderer.updateAllDirtyChunks();
```

Would something like this be sufficient for ReplayMod's purposes?

**Comment by Johni0702** [comment]
@jellysquid3 Yup, that'd be great.

**Comment by Marrandino** [comment]
Hey, I am having this exact same problem where minecraft freezes and is "not responding" but does never crash during rendering after making it at most around 800 frames through. However, i do not have sodium, But I do have optifine, and optifabric alongside my fabric, and fabric api. If anyone could please help me with this that would be amazing, I really want these timelapses. Also, I would love to be able to keep shaders.
