### ISSUE TITLE
Bug with gradle

### ISSUE THREAD

**Issue by SergeyMC9730** [ReplayMod/ReplayMod#153]
![image](https://user-images.githubusercontent.com/57207009/80897626-3d513b80-8d2d-11ea-8987-b8edc3f1bf66.png)
I wanted to download a replay mod for 1.15.2, but the site is down, so I decided to compile this mod from the source code and I got a strange error

**Comment by Johni0702** [comment]
The build script relies on git metadata to determine the version to give to the built jar, so you need to clone the repository via git (e.g. `git clone --recursive https://github.com/ReplayMod/ReplayMod.git`) and cannot use the `Download ZIP` button (assuming that's what you did).

**Comment by Johni0702** [comment]
Also just fixed the website. Thanks for notifying me.

**Comment by SergeyMC9730** [comment]
thank you for help!

> The build script relies on git metadata to determine the version to give to the built jar, so you need to clone the repository via git (e.g. `git clone --recursive https://github.com/ReplayMod/ReplayMod.git`) and cannot use the `Download ZIP` button (assuming that's what you did).

thank you for help
