### ISSUE TITLE
[2.3.0-b1+] ReplayMod ModCore init result: -2, previous builds work fine.

### ISSUE THREAD

**Issue by rcmaehl** [ReplayMod/ReplayMod#159]
I am unable to get ReplayMod to load on builds 2.3.0-b1 and newer.
All builds up to 2.2.0-b7 launch fine.
I'm using Minecraft 1.12.2 with Forge 14.23.5.2847 and LiteLoader 1.12.2-SNAPSHOT+jnks-b4

I've quoted all lines from launcher.log and context into pastebin:
https://pastebin.com/raw/P6vvB6kE
(since neither quote nor code have scrollbars)

Please let me know if you need anything else

**Comment by Johni0702** [comment]
The debug.log should contain far more info than the launcher log.

ModCore failing to initialize is currently expected and not an issue (note that the line says "INFO", not "ERROR"), it will even happen when the mod launches properly, it's just not fully implemented yet.
This is probably more to do with the fact that we changed the way we load Mixin. Does it launch fine if you remove LiteLoader?

**Comment by rcmaehl** [comment]
> Does it launch fine if you remove LiteLoader?

Yep :/

Well heck. I guess I'll have to give up a couple mods. Can't find a modern noteblock GUI mod or Tabbed chat mod but I guess I can give those up. Interestingly enough having both Forge and Modloader installed debug.log doesn't generate. I've pasted the log file from 2020-05-09.log.gz in hope it's equilavent:

https://pastebin.com/raw/eM5akpEy

**Comment by Johni0702** [comment]
Ah, LiteLoader includes an old version of Mixin (0.7.5) whereas ReplayMod includes 0.8.

Ordinarily one can work around around the issue by renaming the RM jar to be alphabetically before LiteLoader (thereby causing its version to be loaded first), though I'm not suer if that's going to work given LiteLoader is no ordinary mod. Definitely worth a try though, I guess.
If simply renaming doesn't help, [this](https://github.com/ImpactDevelopment/ImpactIssues/wiki/Adding-LiteLoader#modify-the-json-applies-to-all-versions) might also be worth a try.

Ideally LiteLoader would update its bundled Mixin version but looks like that isn't happening, at least it hasn't for above a year: http://develop.liteloader.com/liteloader/LiteLoader/issues/71


Closing as there's nothing we can do, LiteLoader would have to update. Prior to 2.3.0-b1, RM itself was bundling an older Mixin, causing issues with mods which had newer ones, so going back isn't really an option either.

**Comment by JasonHK** [comment]
It seems that the development of LiteLoader stopped in 2017, so I don't expect it will be updated any time soon.
