### ISSUE TITLE
Rending will only render a single frame

### ISSUE THREAD

**Issue by sattibunny** [ReplayMod/ReplayMod#160]
I am having an issue rendering. I apply my position key frames and Time Key frames and select render but i will only render out one single frame for the duration of my clip (eg 10mins) 

It will play through fine in the replay viewer however. I have included a short video of the render as well as a photo of my settings 

[2020-05-09 18-58-41.zip](https://github.com/ReplayMod/ReplayMod/files/4604253/2020-05-09.18-58-41.zip)

![Capture](https://user-images.githubusercontent.com/62266386/81481480-75261a80-9228-11ea-998e-154c76407577.PNG)

My command line reads    -y -f rawvideo -pix_fmt bgra -s %WIDTH%x%HEIGHT% -r %FPS% -i - %FILTERS%-an -c:v libx264 -b:v %BITRATE% -pix_fmt yuv420p "%FILENAME%"

and i have ffmpeg install in the correct folder
![Capture2](https://user-images.githubusercontent.com/62266386/81481524-bdddd380-9228-11ea-9d67-39a95ae3dd31.PNG)

If i can assist you in any other way or you require any other information please don't hesitate to ask and ill get that to you.

Many thanks in advanced for your help

**Comment by Johni0702** [comment]
By `It will play through fine in the replay viewer however.`, you mean pressing the play button in the second row, right?
Asking because people are often confused by the keyframes and carefully staring at the pixels in your video, they do appear to move, just very slowly.

**Comment by sattibunny** [comment]
Ah no on the second row play button it sticks to one frame also. It will
play on the first rows play button

**Comment by sattibunny** [comment]
But I don't think it moves at all. It certainly doesn't render more than a
frame. Am I setting up the key frames wrong then? Cheers Btw I appreciate
the help

**Comment by Johni0702** [comment]
> But I don't think it moves at all. It certainly doesn't render more than a
frame.

I'm not sure if it's actual movement or just video encoding artifacts but the pixels of the preview in the video you posted do definitely change.

> Am I setting up the key frames wrong then?

Yes. Maybe [this](https://www.replaymod.com/forum/thread/2295#post9900) will help? Otherwise I'd suggest watching some video which explains how it works.
