### ISSUE TITLE
Replay barely loads chunks

### ISSUE THREAD

**Issue by A13XFPS** [ReplayMod/ReplayMod#161]
The replay will only show a few chunks at a time. 

Video example - https://youtu.be/E19hmchtOHI

**Comment by CrushedPixel** [comment]
The video you've posted is private. Please make it unlisted!
Also, can you share the Replay with us by uploading the `.mcpr` file from `.minecraft/replay_recordings` somewhere?

Thanks!

**Comment by A13XFPS** [comment]
Video is now set to unlisted. 

What site could I use to upload the mcpr file?

**Comment by CrushedPixel** [comment]
You can use Google Drive or Dropbox, if you have an account.

**Comment by Johni0702** [comment]
If it's not too large you can also just zip it and attach it right on GitHub.

Anyhow, this sounds and looks pretty much like https://github.com/ReplayMod/ReplayMod/issues/151, which should be fixed for new replays with 2.3.0. Which version are you using?

**Comment by A13XFPS** [comment]
https://drive.google.com/file/d/1cneMnshPBWoSU24Z9jN8GuPaDznLN1It/view?usp=sharing

**Comment by A13XFPS** [comment]
> If it's not too large you can also just zip it and attach it right on GitHub.
> 
> Anyhow, this sounds and looks pretty much like #151, which should be fixed for new replays with 2.3.0. Which version are you using?

I'm using 2.3.0

**Comment by Johni0702** [comment]
The replay says it was recorded with `ReplayMod v1.15.2-2.3.0-b1`, which still had the bug. Since it's a bug with recording, upgrading to a newer version won't fix it, only new recordings will be fixed.

If you need that particular replay, you can likely find a similarly named one in `.minecraft/replay_recordings/raw/` which doesn't have the Start/Stop/Pause/Resume feature applied and therefore also doesn't suffer from that bug.

**Comment by A13XFPS** [comment]
> The replay says it was recorded with `ReplayMod v1.15.2-2.3.0-b1`, which still had the bug. Since it's a bug with recording, upgrading to a newer version won't fix it, only new recordings will be fixed.
> 
> If you need that particular replay, you can likely find a similarly named one in `.minecraft/replay_recordings/raw/` which doesn't have the Start/Stop/Pause/Resume feature applied and therefore also doesn't suffer from that bug.

I downloaded less than a week ago. Is v1.15.2-2.3.0-b1 not 2.3.0?
Should I just move the raw into the other folder so that I can access it in the replay system?

**Comment by Johni0702** [comment]
> I downloaded less than a week ago. Is v1.15.2-2.3.0-b1 not 2.3.0?

No, the "-b1" is short for "-beta1", so plain 2.3.0 is more recent (and has that bug fixed).

> Should I just move the raw into the other folder so that I can access it in the replay system?

Yes.

**Comment by A13XFPS** [comment]
That seems to have worked! 

Thank you so much for the quick responses!

**Comment by Horion06** [comment]
Hi i have same problem but your indications doesn't work for me.

1.7.10 replaymod 2.3.0

So when i rendering video, the chunk load during this final video 

https://youtu.be/DzoIRbZY7zY

(Sorry for my english i french ^^)
