### ISSUE TITLE
Crash starting Replay Mod 1.14.4-2.3.0 with OptiFabric

### ISSUE THREAD

**Issue by CrushedPixel** [ReplayMod/ReplayMod#162]
Reported by Brayn on the ReplayMod Discord. It has been reported that it worked with older RM versions.

Find attached the crash report.

[crash-2020-05-11_04.16.07-client.txt](https://github.com/ReplayMod/ReplayMod/files/4606833/crash-2020-05-11_04.16.07-client.txt)

**Comment by CrushedPixel** [comment]
Just got a second report with the same issue

**Comment by CrushedPixel** [comment]
This has been reported to work in 2.2.0-b7, but not in 2.3.0.

**Comment by Dancbeunny98** [comment]
Will this be fixed?

**Comment by CrushedPixel** [comment]
Probably, yes. Pestering the developers won't make it happen faster, though.
