### ISSUE TITLE
Crash when saving Replay in MC 1.8.9 (RM 2.3.0)

### ISSUE THREAD

**Issue by CrushedPixel** [ReplayMod/ReplayMod#165]
Looks like a bug in ReplayStudio.
The crash happens when leaving the server.

[latest.log](https://github.com/ReplayMod/ReplayMod/files/4609990/latest.3.log)

**Comment by Johni0702** [comment]
Need the raw replay file.

**Comment by Johni0702** [comment]
Closing in favor of #210 which includes a raw replay file.
