### ISSUE TITLE
replay mod 1.15.2 freezing during render

### ISSUE THREAD

**Issue by andyisyoda** [ReplayMod/ReplayMod#167]
replay mod version replaymod-1.15.2-2.3.0-b1
recorded a session in minecraft 1.15.2 then tried to render a simple camera path
i expected a rendered file
the replay mod froze mid render and minecraft froze overall

using optifabric-1.0.0-beta8
fabric-api-0.10.1+build.306-1.15
preview_OptiFine_1.15.2_HD_U_G1_pre13

[latest.log](https://github.com/ReplayMod/ReplayMod/files/4610973/latest.log)

**Comment by Johni0702** [comment]
Try updating your ReplayMod. A similar issue (#156) has been fixed in the 2.3.0 release, you're still using the beta version.

**Comment by andyisyoda** [comment]
wow - this fixed it! thanks so much
