### ISSUE TITLE
Crashing anywhere from 2 to 60% of the way through a render

### ISSUE THREAD

**Issue by TheReaperLord** [ReplayMod/ReplayMod#171]
I've attempted 3 renders, and although it worked last time I tried all 3 failed at various points in the rendering process. There are only a few differences between these attempts and the last working one.
Those two being that these are taken from a server rather than a singleplayer world and I have recently upgraded my video card.

**Comment by CrushedPixel** [comment]
Can you provide the `debug.log`, or, if that doesn't exist, the `latest.log` (taken directly after the bug occurred). These logs are located in `.minecraft/logs`.

**Comment by TheReaperLord** [comment]
[2020-05-12-5.log](https://github.com/ReplayMod/ReplayMod/files/4614740/2020-05-12-5.log)
That should be the one from the roughly 60% then failure attempt, with chat cleared

**Comment by CrushedPixel** [comment]
We really need the full log to be able to see which versions of Fabric and mods you're using. You can remove the chat, but nothing else, please

**Comment by Johni0702** [comment]
You're also using an old version of the ReplayMod. Try updating first.

**Comment by TheReaperLord** [comment]
I didn't remove anything other than chat, that's all that was there, I'll try updating

**Comment by TheReaperLord** [comment]
Yeah sorry about that, I appeared to have replaymod-1.15.2-2.3.0-b1
