### ISSUE TITLE
Game crashing on the latest release 

### ISSUE THREAD

**Issue by neelayplays** [ReplayMod/ReplayMod#174]
I was using the beta release "replaymod-1.15.2-2.3.0-b1" and the game runs fine But when using the Latest version The game crashes for me.

- I am using 
![image](https://user-images.githubusercontent.com/47247438/81788046-89fff800-951f-11ea-8ff7-83106e6ef49d.png)

- What did actually happen? "the game crashed before launching"

- the log [(The Crash Log)](https://pastebin.com/S9qg6LkT)

Hope you can fix this in the next release

**Comment by Johni0702** [comment]
According to screenshot and crash log, you're trying to use the MC 1.12 version of the RM on 1.15.2, the crash is also what I would expect from that combination.

**Comment by neelayplays** [comment]
i feel stupid now
