### ISSUE TITLE
Conflict with default Minecraft hotkeys

### ISSUE THREAD

**Issue by Boobies** [ReplayMod/ReplayMod#179]
The **x** and **c** keys are by default mapped to loading and saving Creative mode hot bars, respectively. These conflict with ReplayMod's default bindings for clearing and opening frames. The net effect is that without the user's intervention, the hot bar stuff does not work out of the box with ReplayMod.

However, I've noticed that while the **l** key is used by ReplayMod, it does not interfere with opening the achievements HUD in the game. Is this is because this key binding only overrides Minecraft's one inside the replay editor? Because if that's the case, a similar approach could perhaps be taken with **x** and **c**.

**Comment by Johni0702** [comment]
Should be fixed by https://github.com/ReplayMod/ReplayMod/commit/fd7b6030f9f34197fbd7a8ff8061c336cb8b8775, released in version 2.4.1.

**Comment by LindaJuffermans** [comment]
In 1.8.9 if ReplayMod has Q assigned to Quick Mode, it cannot be used to drop items in normal gameplay.

Tested with MultiMC, Minecraft 1.8.9, Forge-1.8.9-11.15.1.1722 and ReplayMod 1.8.9-2.5.2
