### ISSUE TITLE
Rendering with Optifine sometimes causes Textures to be swapped

### ISSUE THREAD

**Issue by CrushedPixel** [ReplayMod/ReplayMod#182]
Seems to be caused by an issue binding/modifying the default framebuffer.

https://www.youtube.com/watch?v=We0iXmlP3Po
[ReplayRenderBug.txt](https://github.com/ReplayMod/ReplayMod/files/4649974/ReplayRenderBug.txt)

**Comment by CrushedPixel** [comment]
Reported by Danbearpig#4035

**Comment by Johni0702** [comment]
https://discordapp.com/channels/708304818829262910/709108200632483900/718545270299820082
> I may have made a breakthrough on this issue. I removed the resource pack from the .mcpr file (use 7-zip to open the archive, rename the resourcepack folder to "ignore_resourcepack" and then load the replay). I've tried this so far with three replays that were giving me trouble and have had success each time. I will keep doing this to see if it is a fluke or a consistent solution. My resource pack changes (adds) a lot of custom item textures, but doesn't mess with block textures at all, but may be throwing things off. Still no idea why it only affects the render output.
