### ISSUE TITLE
Download not found in Adfly 

### ISSUE THREAD

**Issue by lombah** [ReplayMod/ReplayMod#183]
![Screenshot (40)](https://user-images.githubusercontent.com/65694253/82516556-65a5ac00-9b1b-11ea-879d-153f3128ac60.png)

**Comment by CrushedPixel** [comment]
Yeah, AdFly sucks, we know. There's a Patreon campaign that we want to use to replace AdFly: https://patreon.com/replaymod

If you have trouble with AdFly, use the Mirror link from the Downloads page!
