### ISSUE TITLE
1.8.9 Technic Launcher Forge Optifine with texture packs won't save.

### ISSUE THREAD

**Issue by ItCameFr0mMars** [ReplayMod/ReplayMod#185]
So I am using technic launcher with forge. I also have optifine and am using texture packs. Whenever I disconnect from a server, this error comes up while saving. 
[crash-2020-05-12_16.46.55-client.txt](https://github.com/ReplayMod/ReplayMod/files/4663128/crash-2020-05-12_16.46.55-client.txt)

**Comment by Johni0702** [comment]
The crash log does not match your description, it's for Fabric on 1.15.2. Which is it?

Either way, please also attach the following two files:
> - The debug.log, or, if that doesn't exist, the latest.log (taken directly after the bug occurred). These logs are located in `.minecraft/logs`.
>
> - If Replay Files aren't being saved properly, please provide the raw recording from `.minecraft/replay_recordings/raw`

**Comment by ItCameFr0mMars** [comment]
I will try to get those for you.

**Comment by ItCameFr0mMars** [comment]
The version is forge 1.8.9. There must have been some naming issue
[latest.log](https://github.com/ReplayMod/ReplayMod/files/4668604/latest.log)
https://drive.google.com/file/d/1JbUquvgslwmLLd6EkoGTBxFe3wH3y8XZ/view?usp=sharing
Here are those files

**Comment by Johni0702** [comment]
The log you linked seems somewhat incomplete, it doesn't contain any of the usual information which I'd expect. Most importantly though, it does not contain the error. Maybe the technic launcher somehow breaks it, could you try the vanilla launcher or MultiMC?

I can also save the replay you sent just fine, so it's not the usual Start/Stop/Pause/Resume feature which is at fault here. That however also means that I'm unable to reproduce it as is.
