### ISSUE TITLE
Exiting the Player View with Shift.

### ISSUE THREAD

**Issue by AgentAgrimar** [ReplayMod/ReplayMod#19]
Exiting the player view with "Shift" doesn't work if the key is being used for another bind, and doesn't work when you Sneak with a different bind..

**Comment by CrushedPixel** [comment]
This is because the sneak keybinding is used to exit spectator mode in the ReplayMod - simply use the key that sneaking is bound to.

In the future, please post in the [ReplayMod Forums](https://replaymod.com/forum) instead of opening a GitHub issue :)
