### ISSUE TITLE
Equirectangular rendering renders a hand in every direction

### ISSUE THREAD

**Issue by CrushedPixel** [ReplayMod/ReplayMod#196]
![unknown](https://user-images.githubusercontent.com/10288753/82754618-5e59f900-9dce-11ea-87e6-45494313569c.png)

**Comment by Johni0702** [comment]
Versions? Other mods?

**Comment by CrushedPixel** [comment]
[2020-04-27-4.log](https://github.com/ReplayMod/ReplayMod/files/4673739/2020-04-27-4.log)

Here's the log.
Bug was reported by "Minecraft 360", they claim the bug to have disappeared with a restart of Minecraft.

**Comment by Johni0702** [comment]
That log does not even mention the RM.

**Comment by CrushedPixel** [comment]
Garg, people.

**Comment by Johni0702** [comment]
Probably because of OF and fixed by 8d8295.
