### ISSUE TITLE
Crash when rendering a camera path that goes above Y=255

### ISSUE THREAD

**Issue by CrushedPixel** [ReplayMod/ReplayMod#197]
For some reason, the log doesn't contain the crash itself, but should give enough info to consistently reproduce the bug.

[latest (25).log](https://github.com/ReplayMod/ReplayMod/files/4678054/latest.25.log)

This is the video up to the point where it crashes:
[clipcompressed.mp4.zip](https://github.com/ReplayMod/ReplayMod/files/4678057/clipcompressed.mp4.zip)

**Comment by ZytraX** [comment]
i found the issue, would like to add the clip is saved up to the point of the crash where block textures are corrupted
https://gph.is/g/46qQWYX

**Comment by ZytraX** [comment]
> i found the issue, would like to add the clip is saved up to the point of the crash where block textures are corrupted
> https://gph.is/g/46qQWYX

![image](https://user-images.githubusercontent.com/65913910/82830354-116a4580-9ee8-11ea-84c0-eaf38e1c89db.png)
