### ISSUE TITLE
how to use ffmpeg command?

### ISSUE THREAD

**Issue by lumixraku** [ReplayMod/ReplayMod#20]
I've edit my clips and prepare to export, but crashed a lot of times. When I start game again I lost all the postion keyframes and time keyframes. I want to try ffmpeg command to export video file. I wonder what is the input file for ffmpeg command? 

ffmpeg -y -f rawvideo -pix_fmt rgb24 -s %WIDTH%x%HEIGHT% -r %FPS% -i - %FILTERS%-an -c:v libx264 -preset ultrafast -pix_fmt yuv420p "%FILENAME%"

I'm really confused about this "-i - %FILTERS%".   What is the input file for ffmpeg?  I've read the log, and found the input source is 'pipe'.

**Comment by CrushedPixel** [comment]
Please go to the [ReplayMod Forums](https://replaymod.com/forum) and create a proper bug report.
