### ISSUE TITLE
Issues when the recording player rides a horse

### ISSUE THREAD

**Issue by CrushedPixel** [ReplayMod/ReplayMod#203]
Reported by MyNameIsJT.

Video of the issue:
[2020-06-01_10-47-17.mp4.zip](https://github.com/ReplayMod/ReplayMod/files/4711002/2020-06-01_10-47-17.mp4.zip)

Log file:
[2020-06-01-1 (1).log](https://github.com/ReplayMod/ReplayMod/files/4711005/2020-06-01-1.1.log)
The user said this also happens on ReplayMod 2.3.1, although this log is from an older version.

They said they have *not* used the start/pause recording features when recording the replay.

The replay file in question: https://drive.google.com/file/d/1pzs-c9JlAXEw4jv4NYw8fcwqD55TYW1v/

> Yes, it's fine at the start, I first noticed it when I skipped back at one point, suddenly everyone was like this. 
My process is a bit odd, I create a few points throughout the timeline, and then go through it to add points every 30 or 60 seconds depending, to smooth things out.
When I first added the points, I hadn't skipped back, so everything was ok. I then started at the start and added points at the 30 second intervals. I got distracted around 10 minutes and skipped back to 9:30, then the problem started.

**Comment by Johni0702** [comment]
How about without OF (and other mods but especially OF)?

**Comment by CrushedPixel** [comment]
Yes, the same behaviour occurs without any other mods
