### ISSUE TITLE
Issues when the recording player rides an entity at the start of the recording

### ISSUE THREAD

**Issue by CrushedPixel** [ReplayMod/ReplayMod#204]
Could be related to #203.

Reported by rusted:
> Now my replays are void. Entities are shown but there's nothing else. Any ways to fix?

> okay found the problem. if you start recording while sitting on boats or horses or something like that, it won't record it properly

I couldn't get them to send me a log file or a replay recording, but it sounds simple enough to reproduce, so I'm still opening this issue.

**Comment by Johni0702** [comment]
Cannot reproduce.
![](https://i.johni0702.de/fMqgO.png)
https://paste.ee/p/xM7O0
