### ISSUE TITLE
Freeze frame at the start of the rendered video

### ISSUE THREAD

**Issue by CrushedPixel** [ReplayMod/ReplayMod#207]
Reported by Charxter:

> Recently I've been using replaymod a lot more (1.15.2) and the first bit of time is always a still frame for (X) amount of time & then it jumpcuts to the actual replay.

Rendered video that shows the issue:
https://youtu.be/ezrKxHqKIMs

Log: 
[latest.log](https://github.com/ReplayMod/ReplayMod/files/4713449/latest.log)

Replay File with path preset:
[2020_06_01_12_21_26_2.mcpr.zip](https://github.com/ReplayMod/ReplayMod/files/4713450/2020_06_01_12_21_26_2.mcpr.zip)

**Comment by Johni0702** [comment]
Sounds like they don't know how the bottom timeline works.
The timeline JSON in the replay doesn't appear to match the video but the first keyframe is at 13s, which fits with my suspicion.

**Comment by CrushedPixel** [comment]
Yes, indeed, that's the misunderstanding! Thanks for pointing that out.
