### ISSUE TITLE
Mega 3d to voxels to minecraft 1.12.2 region files.

### ISSUE THREAD

**Issue by HakkaTjakka** [ReplayMod/ReplayMod#208]
Hi. Thanks for the Great ReplayMod. 

I have a question.
Are you and/or others interested in a (large scale) voxel generator.
It converts (large, like google 3d earth data) 3d objects (.obj, google 3d downloaded with javascript program) to (sized) voxel data. Very fast. Like in the hundreds of thousand blocks per second. 
Then for the demo the voxels are converted into region files, of 512x256x512 blocks and saved in minecraft 1.12.2 region files. 
You also can code with the voxel data and/or 3d data into 3d space by programming the blocks into position, including mobs, multi command domino triggered command blocks that also can create whole structures when triggered, like in the demo with building coral reefs into the aquariums.
So the world of minecraft can be programmed, with 2d sources and/or 3d sources like .obj files, then coded like you want into region files.
Its a preliminary prototype machine mainly build in c++, and has many integrated possibilities, like super large canvas to plot the worlds on, from top view, but later in real time 3d view. Like the 3d objects also already can do.
Then next step is like rendering very large posters on hires from all the google 3d objects, you also can convert the (generated/loaded) world into 3d object structure, then they also can be rendered on very large posters. A whole world could be printed in any perspective like you want.
A demo world converted from google 3d earth is on: mc5.turbohost.nl:30004

I'm offering you all here a program that has great potential. And i'm looking for people who want to make a commercial version out of it, from commandline (like ffmpeg commands) and/or by menu. Now the program only operates through adapting source code and using keyboard. You need to reverse engineer the source if you have no guideline on how to operate the whole thing, because it needs lots of diff. steps. A manual will be written to reproduce what i did and how the system works and can be used.

You may negatively replay to my offer, its up to you. You can see things the negative way or the positive. I'm offering you a great c++ program to work with on .nbt files, zipped/raw, reading writing to/from disk/memory, .mca files creating, programming region files, 3d to voxel converter (very fast) to region files, super large scrolling editable canvas, shaders geometry/fragment/vector, recording/loading external and internal ffmpeg player, build in cuberite minecraft server, open cd, auto youtube downloading/subtitling, 2d gaming, maze creator, shader over hundreds of textures from canvas blown up super large. 3d viewer, .obj loader/writer, 2d maps downloader direct from internet and/or from disk. Google Earth 3d download script in javascript. Converter .obj to .nbt. Supersized large posters of mega 3d objects like minecraft worlds/google 3d data. Blow up textures/internet images/movies up over hundreds of screens or plot thousands of them and/or program canvas for source for minecraft worlds.

I like to hear some of your (positive i hope) reactions. I'm willing to adapt the program to the wishes of other users for free. Tia. 

mc5.turbohost.nl:30004

![image](https://user-images.githubusercontent.com/66055060/83573401-b5c53b00-a52b-11ea-8c63-459aa8b100b1.png)

**Comment by Nemos59** [comment]
I don't think this is the place to promote yourself and/or what you're doing, and this is not what the replaymod was made for. It was originally made by CrushedPixel to make cool montages of his epic shots from a different perspective when playing Quakecraft on the Hypixel server.

**Comment by HakkaTjakka** [comment]
Yeah. I love negative reactions.

https://www.youtube.com/watch?v=BcUfDZcraB0

https://www.youtube.com/watch?v=e7IMldMbdlw

If people want to join this project mgs me.

**Comment by CrushedPixel** [comment]
This is very off-topic and has nothing to do with the ReplayMod. Please stop creating alt accounts and creating issues here.
