### ISSUE TITLE
Crash when saving replay in 1.8.9-2.3.1

### ISSUE THREAD

**Issue by Nemos59** [ReplayMod/ReplayMod#210]
Quoting Xitharis:

Found a big problem for replay mod 1.8.9

Problem: Auto-start OFF/ON button doesn't work and will always be recording. Also starting recording manually starts an error because it is already auto recording, causing a dupe.
MC Version: 1.8.9 (most popular pvp version)
Replay Version: 2.3.0 and 2.3.1, but a few older versions are also somewhat problematic.

Crash report + latest.log + raw recording in zip file
[RM 2.3.1 in Minecraft 1.8.9 crash.zip](https://github.com/ReplayMod/ReplayMod/files/4732872/RM.2.3.1.in.Minecraft.1.8.9.crash.zip)

**Comment by Zitharis** [comment]
*bump
