### ISSUE TITLE
Signs don't show their text

### ISSUE THREAD

**Issue by SchredDev** [ReplayMod/ReplayMod#213]
I have some oak signs in the background of a scene, but they just appear blank during the replay. Why could that be? I didn't find much by googling except for [this ](https://www.replaymod.com/forum/thread/547)post from 2015 that claims the problem was fixed.

I am using Minecraft 1.15.2 and replay mod v. 2.3.1 for that version.

**Comment by Johni0702** [comment]
Cannot reproduce.
![](https://i.johni0702.de/mxuN7.png)

**Comment by SchredDev** [comment]
Ah my bad. Something must have broken that particular recording, as the controls were inversed too. It's working fine now.
