### ISSUE TITLE
Out of order Timeframes

### ISSUE THREAD

**Issue by WilsontheWolf** [ReplayMod/ReplayMod#223]
Hello there. When I attempt to preview my replay I get this error. 
![image](https://user-images.githubusercontent.com/33164598/84573903-88b12d80-ad60-11ea-90b9-b8d1433095bb.png)
However, none of my timeframes are red as seen in this gif:
![mc](https://user-images.githubusercontent.com/33164598/84573948-d62d9a80-ad60-11ea-88ca-7b950bab9679.gif)
I manually jumped to all of my timeframes and they all seem to be in the proper order.
I can't seem to figure out why this occurs.
I'm on Minecraft 1.15.2
My mod list is here 
![image](https://user-images.githubusercontent.com/33164598/84574016-31f82380-ad61-11ea-8daf-567844ea6736.png)
This should be my replay file
[2020_06_12_19_19_52.mcpr.cache.zip](https://github.com/ReplayMod/ReplayMod/files/4774980/2020_06_12_19_19_52.mcpr.cache.zip)
If you need anything else please feel free to contact me.

**Comment by Johni0702** [comment]
The replay file is the file ending with `.mcpr`, it'll also contain your path and as such will be pretty useful for diagnosing this.
The `.mcpr.cache` folder contains just temporary data but not the important bits.

**Comment by WilsontheWolf** [comment]
[2020_06_12_19_19_52.mcpr.zip](https://github.com/ReplayMod/ReplayMod/files/4775010/2020_06_12_19_19_52.mcpr.zip)

**Comment by Johni0702** [comment]
Your second time keyframe is really close to your third one, so that's why you're not seeing the red part, try zooming in at 02:33

**Comment by WilsontheWolf** [comment]
Yep, that was the issue. Thanks
