### ISSUE TITLE
Replay switches to first person in the middle of a path

### ISSUE THREAD

**Issue by jaminvanderberg** [ReplayMod/ReplayMod#225]
Replays will suddenly switch into first-person mode in the middle of a path. This tends to happen the most often when you enter a bed or open chests. It doesn't happen all the time, but it happens quite frequently and it can really disrupt the flow of a replay.

**Comment by Johni0702** [comment]
Would be great if you could attach a replay with a path during which it is happening, so one can easily reproduce it.

**Comment by jaminvanderberg** [comment]
Here's the most recent one where I've had it happen: https://drive.google.com/file/d/18PolA_iPVAA80MyNGhw8Ke7M_zs8ip8-/view?usp=sharing

There's two instances, the first is about 3 seconds in and the second is just after I assemble the second portal. When rendered, there's just a few frames where it breaks from the path and shows a first-person view of staring into the portal. I believe I may have paused just before entering the portal to avoid replaying an unloaded dimension, but I wouldn't expect it to go into first-person because of this. You should be able to see this even playing the camera path within ReplayMod itself.

I have more egregious examples where it happens repeatedly when entering beds/opening shulkers, but those replays are a few weeks old and will take a bit to find.

**Comment by jaminvanderberg** [comment]
Here's one where it happens a few times while opening shulker boxes: https://drive.google.com/file/d/1AedSoBDjKXISwgdwLDyFnErNovvqTFox/view?usp=sharing
