### ISSUE TITLE
[RM. V. 2.3.1] chunks are not loading in replies. visiting another dimension while recording solves the problem temporally 

### ISSUE THREAD

**Issue by Rebilium** [ReplayMod/ReplayMod#226]
so recently reply mod for some reason is not loading chucks it happens randomly, and after recording few sessions i noticed that if go to the nether and go back it while recording, solves the problem and everything load again.

reply mod Files : 

1. https://www.mediafire.com/file/fuv7vafdwdrysfq/2020_06_16_05_20_08.mcpr/file

2. this files contain a session on which i accidentaly went to the nether
https://www.mediafire.com/file/a97086nj8nsmjh2/roof_mob_farm.mcpr/file

Mods i use : https://imgur.com/a/T8DZ6Iq

previously i was using an older version of Optifine, changed it to a newer one. didn't help.
last thing that might be useful, is that i had an older version of reply mod and it didn't occur. it happened on this version. [2.3.1]

if there anything else to provide let me know!
Thanks!

**Comment by Johni0702** [comment]
Does this also happen without any third-party mods? If not, please try to find the minimal configuration with which it happens.
You should probably also update fabric api.

> it happens randomly

Random during recording, i.e. consistently for some replays but not for others?
Or is it random each time you open a replay?
In the latter case, does jumping to the end of the replay and back help?

**Comment by Rebilium** [comment]
i'll try to follow each question with an answer,
1. Does this Also happen without any 3rd-party mods ?
- its hard to say because in order to test that i need to keep recording and then stop and go check the reply video. so i can't know which video will have this problem or not.

2. Random during recording, i.e. consistently for some replays but not for others?
- yes completely random. there are no indication what so ever that a video would have this issue or not.

3. Or is it random each time you open a replay?
No, if a video have this issue it will always have the issue no matter what i change or do (i tried removing all the unnecessary mods, it didn't help at all) . others normal replies aren't effected no matter how much i play it back.

4. In the latter case, does jumping to the end of the replay and back help?
- i've been recording non stop to create a reply video with this issue, unfortunately they all come up normal replies. i haven't changed anything just to get one with this issue.

Notes;
1. Local Disk has 16 -13 GB out of 100 GB. i didn't have any issues in the past with much less memory on the disk.
2. i've noticed that most of the affected/corrupted replies are longer than 30 min, but not all of them. e.g. i've recorded 4 replies with 1 hour each and 2 had the problem, one of them uploaded in my recent post, the other one i decided to delete it before i wrote my first post.

i will be recording in different locations, singe/multi player, long/short replies with the same settings hopefully i can get one where i go to the end and jump back.

2 additional bugs:
1. camera path turns to off automatically. but only sometimes. Randomly.

2. some replies has the player skin normally till i jump into the nether. the player loses its outer skin layer as shown in this replies and its stays the same. same thing when i jump to the end but once i come back, this skin goes back to normal or might stay without outer layer. not sure if all this helps but i hope so.

**Comment by Johni0702** [comment]
Could you check if there's a replay with the same name as the broken replay at `.minecraft/replay_recordings/raw/2020_06_16_05_20_08.mcpr` and if so, upload that as well?

For unrelated bugs, please open separate issues (so they can be dealt with independently) and explain them over there.

> camera path turns to off

I don't understand what that means.

Btw, `replay`, `reply` and `video` are three different things. This mod records and plays replays and allows you to setup a camera path to render into a video. This message is a reply to your message.
I'm assuming till now you used all of them to mean replay.

**Comment by Rebilium** [comment]
https://www.mediafire.com/file/fuv7vafdwdrysfq/2020_06_16_05_20_08.mcpr/file

> For unrelated bugs, please open separate issues (so they can be dealt with independently) and explain them over there.

> For unrelated bugs, please open separate issues
will do.

About the Camera Path. in the reply mod settings there is an On/Off option for the Camera Path, to be visible or not in the reply (i assume this is the right word,lol) 

thanks for the grammar listen :P. English is not my native Language.

**Comment by Rebilium** [comment]
i finally got it. and yes jumping to the end and back fixes the issue.
reply file : https://www.mediafire.com/file/jtxldhfue1h6tz7/2020_06_18_14_15_06.mcpr/file
reply file from .minecraft/replay_recordings/raw/ directory : https://www.mediafire.com/file/7ybfqag4lbnwk9o/2020_06_18_14_15_06.mcpr/file
