### ISSUE TITLE
Rendering problem.

### ISSUE THREAD

**Issue by WolfgangProh** [ReplayMod/ReplayMod#228]
So, I am new to replaymod and wanted to make a edit. Everything works fine, till I get to rendering the video. I click on rendering, but nothing happens... I even hear the sound of the rendering button, but nothing happens. Maybe my settings are wrong or something like that. But I haven't found the issue.

**Comment by Nemos59** [comment]
possible duplicate of #206

**Comment by Johni0702** [comment]
Duplicate of #206
