### ISSUE TITLE
[RM. V. 2.3.1] Maps are not rendered on replays

### ISSUE THREAD

**Issue by xxfast** [ReplayMod/ReplayMod#232]
Maps in item frames are not rendered in the replay viewer

Replay viewer
<img width="1259" alt="Screen Shot 2020-06-20 at 5 42 09 pm" src="https://user-images.githubusercontent.com/13775137/85196391-62216280-b31d-11ea-85af-25787ecd24b4.png">

In game
<img width="1399" alt="Screen Shot 2020-06-20 at 5 56 27 pm" src="https://user-images.githubusercontent.com/13775137/85196698-5fc00800-b31f-11ea-9cd5-c5847a4f1388.png">

**Mod version:** 2.3.1
**Game version:** 1.15.2

**Comment by T-x-T** [comment]
I had the same issue when starting the recording mid-session. Do you have a automatic recording enabled (and if not can you test it with it enabled)?

**Comment by Johni0702** [comment]
Yeah, they did start it mid session (or paused it or ended it early). I know what causes this (a bug in ReplayStudio's SquashFilter) and have already fixed it locally.
