### ISSUE TITLE
Minecraft crashes on startup with replay mod is loaded with carpet mod 1.16 rc1

### ISSUE THREAD

**Issue by razgriz5000** [ReplayMod/ReplayMod#235]
Replay mod version: replaymod-1.16-2.3.1-7-gdc9fcb1
Carpet mod, fabric, and fabric-api are all on current versions.  Crash log in provided txt.  I don't know enough if this is a problem with replay mod or carpet mod.  

Carpet Mod: https://github.com/gnembon/fabric-carpet/releases 

[repalymod-crashes-with-carpet-mod.txt](https://github.com/ReplayMod/ReplayMod/files/4809946/repalymod-crashes-with-carpet-mod.txt)

**Comment by Johni0702** [comment]
I had a long look at this and I'm really not sure who's in the wrong here.
The easiest solution is a specific change in carpet, so I've opened an issue for it over there: https://github.com/gnembon/fabric-carpet/issues/341

**Comment by Johni0702** [comment]
Should be fixed as of Carpet 1.3.33

**Comment by razgriz5000** [comment]
Confirmed working with Carpet 1.3.33.  Thank you for looking into this.
