### ISSUE TITLE
Replay Mod Crashes while Rendering

### ISSUE THREAD

**Issue by richardyin99** [ReplayMod/ReplayMod#236]
1. replaymod-1.12.2-2.3.1, but I have the same issue for replaymod-1.12.2-2.2.0-b7.
2. I was rendering a 2 hour 30 minute clip into a 1 minute 30 second final product. I left my computer alone while rendering, and did not tab out.
3. I expected the video to export properly
4. Replay Mod crashed during rendering, and the video file was corrupted.
[debug.log](https://github.com/ReplayMod/ReplayMod/files/4810306/debug.log)

**Comment by Johni0702** [comment]
Looks like something has eaten up all the available RAM. Could you try without any other mods? Also make sure there isn't something else running in the background which already uses most of it.

**Comment by HightechCaveman** [comment]
I don't have any other mods. Literally just Optifine, fabric stuff, and Replaymod.
I need Optifine for what I'm needing to do

**Comment by PixelCrusherCrusher** [comment]
![Naamloos](https://user-images.githubusercontent.com/68374484/87652316-58d8b980-c754-11ea-8c19-5cb393265d45.png)
