### ISSUE TITLE
Notification: 1.16 Fully Released Today

### ISSUE THREAD

**Issue by alexis-evelyn** [ReplayMod/ReplayMod#238]
I'm just letting you know 1.16 fully released today. Thanks!

**Comment by Nemos59** [comment]
I guess the devs already know about it

**Comment by Johni0702** [comment]
Yes, very much aware of it. There's even already a ReplayMod snapshot for 1.16-rc1 (which should also mostly work for 1.16, ignoring Mojang's shenanigans) available to VIP Patrons.
