### ISSUE TITLE
How do you find 1.16 release

### ISSUE THREAD

**Issue by GavinPistashio** [ReplayMod/ReplayMod#239]
Im probably just an idiot but on a thread: [https://github.com/ReplayMod/ReplayMod/issues/238](here) it says that 1.16 full release is today but when I went to [https://www.replaymod.com/download/](here) the latest is 1.15.2 how do you find 1.16 release? thanks.

**Comment by Johni0702** [comment]
You don't atm unless you're a Patron on VIP level, see my reply on the thread you linked.
