### ISSUE TITLE
Allow renaming of replays to different capitalizations

### ISSUE THREAD

**Issue by LaniJW** [ReplayMod/ReplayMod#242]
I noticed that renaming a recording from say `Broken` to `BROKEN` doesn't work probably because there's a `.toLowerCase()` check for the name string.
Current Replay Mod version for MC version 1.8.9

**Comment by Johni0702** [comment]
Cannot reproduce.
![](https://i.johni0702.de/9Gsk9.png)

**Comment by LaniJW** [comment]
[Works for me](https://mega.nz/folder/D6pVAQDS#F6bxJa6h9dK_tByTDEyAQw). Maybe you have to append append something to the start or end?

**Comment by Johni0702** [comment]
I don't get your reply. It does not in any way seem to relate to the initial issue description and I don't even see anything wrong with it.

**Comment by LaniJW** [comment]
I'm very sorry about that. That was the folder for another bug report. I'm very sorry for sending the wrong one. [This](https://mega.nz/folder/byhX3CzL#Lm7Zg5kPTd2qykFwx__bvA/folder/euohDQQL) is the right one. (Let's hope this goes right.)

**Comment by Johni0702** [comment]
Which operating system are you using? Could it be that it doesn't allow for two files with the same name but different capitalization?

**Comment by LaniJW** [comment]
Windows and that was the issue. Sorry about that.
