### ISSUE TITLE
When does 1.16 release on public?

### ISSUE THREAD

**Issue by GalaxyGamingBoy** [ReplayMod/ReplayMod#243]
When cause I want to do some timelapses but I don't have money.

**Comment by Nemos59** [comment]
You can expect a release anywhere from a few weeks to a few months. You can also compile the mod for 1.16 by yourself, but expect bugs.

**Comment by CrushedPixel** [comment]
Whenever we deem it stable, we won't give an official date, as that sets everyone up for disappointment if we can't meet it.
