### ISSUE TITLE
Gradle build error

### ISSUE THREAD

**Issue by mondis1337** [ReplayMod/ReplayMod#245]
When gradlew :1.16.1:build it gets two different errors:
First error:
![1error](https://user-images.githubusercontent.com/55624582/86269712-96313900-bbe3-11ea-9791-d745d58ca802.png)
Second error:
![2error](https://user-images.githubusercontent.com/55624582/86269721-98939300-bbe3-11ea-9dc1-9846361fe67c.png)

**Comment by Johni0702** [comment]
Looks like your jGui clone might be outdated/incomplete (to verify, check `jGui/preprocess.gradle.kts`).
From the README:
> Make sure your sub-projects are up-to-date: `git submodule update --init --recursive`
