### ISSUE TITLE
Gradle build error

### ISSUE THREAD

**Issue by GalaxyGamingBoy** [ReplayMod/ReplayMod#246]
When I try to build the jar file it gives me this error:
---------------------------------------------------------------------------------------------
FAILURE: Build failed with an exception.

* What went wrong:
Could not initialize class org.codehaus.groovy.reflection.ReflectionCache

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
-----------------------------------------------------------------------------------------------------------------
Idk what to do pls help!

**Comment by Johni0702** [comment]
If I had to guess, I'd blame ForgeGradle. If you don't want me to guess:

> Run with --stacktrace option to get the stack trace.

**Comment by GalaxyGamingBoy** [comment]
> If I had to guess, I'd blame ForgeGradle. If you don't want me to guess:
> 
> > Run with --stacktrace option to get the stack trace.

I want it to be on fabric how can I do that?
