### ISSUE TITLE
ReplayMod Crashed

### ISSUE THREAD

**Issue by HeyItzRage26** [ReplayMod/ReplayMod#255]
So i was recording my builds to make a timelapse, but when i stopped the recording it juz crashed. I had to leave the game cuz i had to go. Is there anyway to retrieve the recording?

I juz copied the crash report
Here it is:
---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 7/12/20 9:54 PM
Description: Saving replay file

java.nio.file.FileSystemException: C:\Users\asus-khoo\AppData\Roaming\.minecraft\.\replay_recordings\2020_07_12_20_05_25.mcpr -> C:\Users\asus-khoo\AppData\Roaming\.minecraft\.\replay_recordings\raw\2020_07_12_20_05_25.mcpr: The process cannot access the file because it is being used by another process.

	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileCopy.move(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.move(Unknown Source)
	at java.nio.file.Files.move(Unknown Source)
	at com.replaymod.editor.gui.MarkerProcessor.apply(MarkerProcessor.java:124)
	at com.replaymod.recording.packet.PacketListener.lambda$channelInactive$9(PacketListener.java:248)
	at com.replaymod.recording.packet.PacketListener$$Lambda$3360/1723591979.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 322032472 bytes (307 MB) / 811708416 bytes (774 MB) up to 1251213312 bytes (1193 MB)
	CPUs: 4
	JVM Flags: 5 total; -Xmn128M -Xmx1205M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+UseConcMarkSweepGC
	Fabric Mods: 
		fabric: Fabric API 0.14.0+build.317-1.15
		fabric-api-base: Fabric API Base 0.1.2+b7f9825d0c
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.5+3b05f68e0c
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea890c
		fabric-climbable-api-v1: Fabric Climbable API (v1) 1.0.0+6ffe71e20c
		fabric-command-api-v1: Fabric Command API (v1) 1.0.2+2aebb7ff0c
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+2e0c4ff50c
		fabric-containers-v0: Fabric Containers (v0) 0.1.3+b7f9825d0c
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825d0c
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d0c
		fabric-dimensions-v1: fabric-dimensions-v1 0.3.0+2ad156310c
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.0+fac69e320c
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+2f23104b0c
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+2f23104b0c
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+0121bd900c
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.0+2af3af910c
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+2af3af910c
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.0.0+451a3d520c
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.5+e08a73050c
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+ec951ea40c
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d60c
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.3+e08a73050c
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+d487f0ee0c
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.2.1+e7a4edb30c
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.5.1+3e5587510c
		fabric-particles-v1: fabric-particles-v1 0.2.1+b2771bde0c
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.6+f3d8141b0c
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.10+f08b61330c
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.23+9290e2ed0c
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a600c
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d0c
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+12515ed90c
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104900c
		fabric-rendering-v1: Fabric Rendering (v1) 1.0.0+2a034f0a0c
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.10+06c939b30c
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+abd915800c
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba70c
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.1.0+3e5587510c
		fabricloader: Fabric Loader 0.8.9+build.203
		minecraft: Minecraft 1.15.2
		mm: Manningham Mills 2.0
		optifabric: Optifabric 1.0.0-beta8
		org_slf4j_slf4j-api: slf4j-api 1.7.30
		org_slf4j_slf4j-simple: slf4j-simple 1.7.30
		org_zeroturnaround_zt-zip: zt-zip 1.14
		replaymod: Replay Mod 1.15.2-2.3.2
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre23
	OptiFine Build: 20200607-215525
	Render Distance Chunks: 13
	Mipmaps: 3
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Builder's QOL Shaders V2.4.1.zip
	OpenGlVersion: 4.5.0 NVIDIA 376.54
	OpenGlRenderer: GeForce 820M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

Pls help
if i cant retrieve den F

**Comment by Johni0702** [comment]
Looks like you ran two Minecraft instances at the same time. Never do that, it's neither supported by MC itself nor by the RM and data loss may occur. If you need to run multiple Minecraft instances at the same time, always use a different `.minecraft` folder for each (how you do that depends on which launcher you're using).

If you're lucky you might find your replay at `C:\Users\asus-khoo\AppData\Roaming.minecraft.\replay_recordings\raw\2020_07_12_20_05_25.mcpr`. If you do, you can move it into the regular `replay_recordings` folder and may be able to load it (though if you it loads, there's no guarantee that it's complete).

**Comment by HeyItzRage26** [comment]
But i did'nt use Multiple?

**Comment by Johni0702** [comment]
> The process cannot access the file because it is being used by another process.

Well, it says there was another process process using the replay file, so far that has always been because people opened multiple instances of MC. If that's not the case for you then I highly suggest you get rid of whatever the other processes was cause it's breaking stuff.
