### ISSUE TITLE
Rendered video is twitching

### ISSUE THREAD

**Issue by CrushedPixel** [ReplayMod/ReplayMod#260]
ReplayMod 2.4.0, Minecraft 1.8.9, no other mods present

Video:
https://gyazo.com/f3d860ab9ac39a1ecfb91337b9a4a78b

Replay File:
https://drive.google.com/file/d/1bZUFKG0JIANh0hE49rIARY3MnzXLwNV5/view

Asked for log, yet to be sent by the reporter
Reported by anjeriko#2188

**Comment by CrushedPixel** [comment]
Looks like it's related to #264

**Comment by Johni0702** [comment]
Eh, yeah, pretty sure this is the same. It's not the video itself which is twitching, it's just the spectated entity.
Closing in favor of the other one cause it has more info.
