### ISSUE TITLE
Cannot be used on the boat launcher

### ISSUE THREAD

**Issue by CPXMC** [ReplayMod/ReplayMod#262]
[crash-2020-07-18_08.21.05-client.txt](https://github.com/ReplayMod/ReplayMod/files/4941365/crash-2020-07-18_08.21.05-client.txt)

**Comment by Johni0702** [comment]
Report this to the boat launcher, it looks like their Java build doesn't properly support `java.nio.file.Files.createTempFile` and they need to fix that. Nothing we can do about it.
