### ISSUE TITLE
Jittering Entities in Rendered Output for RM 2.4.0-1.15.2

### ISSUE THREAD

**Issue by Danbearpig82** [ReplayMod/ReplayMod#264]
Jittering entities bug affecting ReplayMod 2.4.0 for Minecraft 1.15.2. This jittering is independent of any other mods, game settings, or world, and only affects this version and possibly 2.4.0 for Minecraft 1.8.9 (I have not tested). Issue is not seen when viewing camera path, only in rendered output. Replay speed does not affect the issue.

[YouTube Demonstration of Issue](https://youtu.be/AKYmRUrrMxI)

For each test I used MultiMC Launcher, and created a new world, changing no settings except to put in seed "Replay". Walked for 30 seconds and rendered at 1x speed. No issues with RM 2.3.2-1.15.2 or for RM 2.4.0-1.16.1. Issue is consistent for multiple users so far in RM 2.4.0-1.15.2.

**Comment by unholymac** [comment]
I'm also getting this issue, need this video out before friday and i can't upload something jittering :(

**Comment by Johni0702** [comment]
@unholymac I probably won't have time to look at this before the next weekend, so you'll either have to debug and fix it yourself or downgrade to 2.3.2 for rendering.

**Comment by unholymac** [comment]
Okay thank you i have degraded and that has fixed my issue <3
