### ISSUE TITLE
Crash when opening replay viewer

### ISSUE THREAD

**Issue by Keetarin** [ReplayMod/ReplayMod#28]
[crash-2018-04-25_12.27.41-client.txt](https://github.com/ReplayMod/ReplayMod/files/1948369/crash-2018-04-25_12.27.41-client.txt)

**Comment by Johni0702** [comment]
<https://www.replaymod.com/forum/thread/2118>

Please use the forum for bug reporting, response time tends to be significantly shorter over there.
