### ISSUE TITLE
Valkyrien Warfare + Replay mod = crash at game loading 

### ISSUE THREAD

**Issue by Resuz** [ReplayMod/ReplayMod#29]
I posted this on both VW and R-mod GitHub
[crash-2018-05-19_17.29.44-client.txt](https://github.com/ReplayMod/ReplayMod/files/2019555/crash-2018-05-19_17.29.44-client.txt)

**Comment by Johni0702** [comment]
This is VW's issue, they should not be using [`@Overwrite`](https://github.com/SpongePowered/Mixin/wiki/Introduction-to-Mixins---Overwriting-Methods#12-with-great-power-comes-great-possibility-to-screw-things-up) and [seem to be aware of that](https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/blob/0e74ea1b4f1c301a09710ea534e863032b193a00/src/main/java/valkyrienwarfare/mixin/client/renderer/MixinEntityRenderer.java#L64).
