### ISSUE TITLE
How to make the saved camera path information in overall replay videoes.

### ISSUE THREAD

**Issue by ZiuChen** [ReplayMod/ReplayMod#296]
Due to the Mod setting, the camera path information saved in a playback can only be read in this playback. I want to use the same camera path for rendering in different videos, but it doesn't work after replacing the files in different playback caches. I would like to ask how to implement the above functions.

**Comment by Johni0702** [comment]
There's this tool which was built to do just that: https://github.com/Nemos59/ReplayTimelineTransfer
With https://github.com/ReplayMod/ReplayMod/issues/318 it'll also be possible to do this from within the mod.
