### ISSUE TITLE
Optifine compatibility [1.11]

### ISSUE THREAD

**Issue by Rapolis** [ReplayMod/ReplayMod#3]
Earlier your mod supported this mod, I want shaders. I want them. I can't record cinematics otherwise without it! I use 1.11 and I don't know why it started this problem since you updated to 1.11. Please fix and thank you.

**Comment by CrushedPixel** [comment]
The ReplayMod 1.11 is compatible with Optifine and Shaders. If you encounter any issues, you should probably describe them instead of making unhelpful demands.
Please fix and thank you.

**Comment by pacmangraphics** [comment]
Upgrade to 1.14.4 using MultiMC (see fabric and fabric api docs how to install for MultiMC and/or MC launcher)

Then use:

fabric-api-0.3.2+build.226-1.14.jar
Optifabric-Mod-1.14.4.jar
OptiFine_1.14.4_HD_U_F3.jar
replaymod-1.14.4-2.2.0-b7.jar
