### ISSUE TITLE
No sound after breaking a block

### ISSUE THREAD

**Issue by TheChocolateOre** [ReplayMod/ReplayMod#301]
If you place a block, the sound plays fine, but when you destroy it (creative mode), there is no sound. I didn't test this for survival mode though.

There is an older version of ReplayMod (I don't remember its numbering though) that this problem is not present.
Is this problem related to fabric?

I know that ReplayMod doesn't export sound, but you can still manually record it and then sync it in editing.

Replay Mod v2.4.1 (Is present in 2.4.0 too)
Minecraft 1.16.1
Fabric 0.6.1.45

**Comment by Johni0702** [comment]
Should be fixed as of RM 2.4.3 (8ffb98e).

**Comment by TheChocolateOre** [comment]
Yeah, all good, I tested it.
