### ISSUE TITLE
Add shortcut to move camera path cursor at the beginning

### ISSUE THREAD

**Issue by TheChocolateOre** [ReplayMod/ReplayMod#304]
Most of the times, if not all, you would like to review your camera path, so you have to manually place the cursor at the beginning. Sometimes, you might move a keyframe along by missclicking and as a consequence, mess things up. And sometimes, the cursor won't quite reach the beginning, so you would have to zoom in the timeline, and repeat.

I would like to add a little bit more on the cursor dragging. I noticed, that you can only drag a cursor while your mouse is on top
of its timeline. If you get out of it in the middle of the process, the cursor stops. I think the software would feel more responsive, if you could still move the cursor even if you miss stepped a little (or a lot) and went out of the borders. Right now, if you are about to move the cursor large distances, you have a decent chance of that happening, giving a feeling of an app freeze. Also, this would fix the problem of not being able to position the cursor, exactly at the beginning. I believe the same applies for keyframe dragging too.

**Comment by Johni0702** [comment]
> By default, the Camera Path starts from the Cursor Position on the Keyframe Timeline. By clicking while holding the Ctrl key (Cmd key on Mac), you can however start from the beginning regardless of the Cursor Position.

https://www.replaymod.com/docs/#replaying-paths-time
