### ISSUE TITLE
Website cannot be accessed

### ISSUE THREAD

**Issue by MAX-XiaoKui** [ReplayMod/ReplayMod#307]
ERR_CONNECTION_TIMED_OUT
ERR_TIMED_OUT
If I use VPN on HTTP it says this:
![image](https://user-images.githubusercontent.com/53287753/89114851-74adc080-d4b3-11ea-8838-eeb3bf379bda.png)
Using VPN with HTTPS has no effect.

**Comment by Johni0702** [comment]
Should be working again.
