### ISSUE TITLE
Hotkey to place keyframes

### ISSUE THREAD

**Issue by Johni0702** [ReplayMod/ReplayMod#312]
One for position (even when spectating), one for time, one for both and one for spectator. Latter two can probably be bound to NONE by default cause the first two are probably good enough for most people.

**Comment by Johni0702** [comment]
Oh, I see, those get generated by Lombok based on these annotations:
https://github.com/ReplayMod/ReplayMod/blob/23e51d7099c173d7bce210b62c077a0d6c5fdcee/src/main/java/com/replaymod/simplepathing/SPTimeline.java#L66

I should really get rid of it, it's nothing but trouble and only saves a few auto-generatable lines. You'll probably have to install its IntelliJ plugin for IntelliJ to be able to see those methods.

**Comment by Johni0702** [comment]
And please don't forget about
> One for position (even when spectating)

That's why I originally opened this issue cause there's currently no way to do this at all.

**Comment by TheChocolateOre** [comment]
Wait, I lost you there. I assume you already reviewed my PR. What do you mean by spectating? If I understand correctly, it's when you right click into an entity, right? I added an action for adding a position keyframe under the "I" key. Won't that work, spectating or not?

**Comment by TheChocolateOre** [comment]
Lombok did the trick, all good. To test my changes I need to produce a .jar. I go with the artifact root? I'm in IntelliJ. What module should I pick and what will the main class be?

**Comment by Johni0702** [comment]
> Wait, I lost you there. I assume you already reviewed my PR. What do you mean by spectating? If I understand correctly, it's when you right click into an entity, right? I added an action for adding a position keyframe under the "I" key. Won't that work, spectating or not?

I looked at the commit linked by GitHub above.
What I'm after is a way to add a position (**not spectator**) keyframe while spectating an entity. Such that one gets the exact position of the entity but doesn't actually spectate it (i.e. no hands and no following of its position).
What the current button and the hotkey in your commit do is always add a spectator keyframe whenever you're spectating an entity, I want a way to instead put a position keyframe though.

> To test my changes I need to produce a .jar. I go with the artifact root? I'm in IntelliJ. What module should I pick and what will the main class be?

No, you don't need a jar to test in intellij. See the README. With the updated loom, it should auto-generate run configs.
If you want a jar for testing outside of intellij, see the README.

**Comment by TheChocolateOre** [comment]
I updaded it.
