### ISSUE TITLE
Support vanilla post-processing

### ISSUE THREAD

**Issue by Johni0702** [ReplayMod/ReplayMod#321]
Used to be only useful for spectating spiders/endermen/etc. but might actually become more useful in the future with fabulous graphics.

**Comment by TheChocolateOre** [comment]
Ray Tracing?

**Comment by Johni0702** [comment]
No, pretty sure they don't support ray tracing.
This is what I'm talking about: 
https://www.reddit.com/r/Minecraft/comments/hkm40f/minecraft_116s_fabulous_graphics_option_allows/
