### ISSUE TITLE
Start/Stop/Pause/Resume breaks chunks under certain circumstances

### ISSUE THREAD

**Issue by Johni0702** [ReplayMod/ReplayMod#329]
Likely related to the specific server implementation.

https://cdn.discordapp.com/attachments/709108200632483900/742120608086884503/2020_08_09_14_53_08.mcpr

**Comment by LindaJuffermans** [comment]
[2020_09_28_10_38_49.zip](https://github.com/ReplayMod/ReplayMod/files/5293562/2020_09_28_10_38_49.zip)
relates to https://discordapp.com/channels/708304818829262910/709108200632483900/760152157273063424

**Comment by Johni0702** [comment]
Duplicate of #139
