### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by RealDelTrexx** [ReplayMod/ReplayMod#330]
I finally understood how to render the pathway that i wanted and the mod completed the render file. When I went to view the video the whole video is full of static and it really upset me because i already spend a whole day trying to get it to work. If anyone knows why this is happening please help!
![Screenshot (60)](https://user-images.githubusercontent.com/69447833/89753331-75d78280-da9d-11ea-94a3-3a74464d01c3.png)

**Comment by Haeherfeder** [comment]
First, there are missing information, but could it be that your laptop/pc is not fast enough to play the video, and the file is ok?

**Comment by Johni0702** [comment]
Yeah, version info would be important. As well as the log.

This looks like something I've already fixed. If it does indeed still happen on the latest version, it'd be interesting to know if it shows in the preview as well?
