### ISSUE TITLE
virus

### ISSUE THREAD

**Issue by virusscanner** [ReplayMod/ReplayMod#331]
I've did some testing with replaymod.

Why the hell does replaymod install opera browser on the computer?
What is all the stuff in the %appdata%\local\temp directory?

Further exploration shows the in the background installed stuff (by replaymod), consumes lots of cpu and network.

So, can you tell me (us) what is happening there?

Are you mining bitcoins or so?

**Comment by Johni0702** [comment]
We do not do anything when Minecraft is closed and generally only stuff in the background which you would reasonably expect (e.g. checking for updates once at the start of the game, saving the last replay, etc.).
We do not install Opera nor do we put stuff into `%appdata%\local\temp`.

That all sounds like you get the mod from a third party site which didn't just give you the mod but also a bunch of other stuff with it.
The only legitimate site from with you should download the ReplayMod is https://www.replaymod.com/download/.

See also https://stopmodreposts.org/

**Comment by virusscanner** [comment]
Then some other software program is using the replaymod? Because the file names holds the string 'replaymod', and all kind of files, like opera installer are all the same date/time stamp.
I've deleted the stuff, and now my computer runs normal again. Before like on 1% or so.

**Comment by Johni0702** [comment]
> Then some other software program is using the replaymod?

Probably. Where ever you got your ReplayMod from, they probably just took the normal one, added a bunch of their own stuff and then packaged the whole thing to look like the legitimate one in the hopes that people wouldn't notice.

**Comment by virusscanner** [comment]
Aha, ok. I will do some more testing.... Then i'm gonna find them.
