### ISSUE TITLE
1.16.2 ReplayMod translations aren't working

### ISSUE THREAD

**Issue by mtatko** [ReplayMod/ReplayMod#335]
### All ReplayMod GUIs don't display text correctly 😢 

![image](https://user-images.githubusercontent.com/60148744/90639478-009f4680-e22f-11ea-9cfc-ad7d19ba88bc.png)

![image](https://user-images.githubusercontent.com/60148744/90639482-01d07380-e22f-11ea-9b19-1b7750aa61a4.png)

**Comment by Johni0702** [comment]
Which **specific** version is this?

**Comment by mtatko** [comment]
> Which **specific** version is this?

Latest mc-1.16.2 branch build

**Comment by Johni0702** [comment]
In that case, did you `git submodule update --init` before building?

**Comment by mtatko** [comment]
> In that case, did you `git submodule update --init` before building?

No, I didn't. I'll try it and let you know.

**Comment by mtatko** [comment]
`git submodule update --init` fixed the issue. Closing.
