### ISSUE TITLE
Replaymod crashes when Labymod are too in the mod folder

### ISSUE THREAD

**Issue by Minecodes** [ReplayMod/ReplayMod#336]
The Replaymod crashes every time when i start it with Labymod.

Here is the Log from Labymod why it's crashing: https://hastebin.com/iqoyajalir

**Comment by Nemos59** [comment]
That's normal, LabyMod is not compatible with the ReplayMod

**Comment by Minecodes** [comment]
Thank you

**Comment by Minecodes** [comment]
But can someone make support for it?

**Comment by Johni0702** [comment]
The crash report itself doesn't actually say much about why it went wrong, could you post the full game log?

> But can someone make support for it?

Depends on the issue. The LabyMod team does not provide their source code for others to look at, so unless it's something obvious visible from the outside (which is why I'm asking for the log), there's not much we can do and it'd be up to them to fix it.

**Comment by Minecodes** [comment]
Here is the full Minecraft Log: https://hastebin.com/unomudazuz.md

**Comment by Johni0702** [comment]
That doesn't include any crash though.

**Comment by Minecodes** [comment]
What folder is it in? I got this log from the logs folder.

**Comment by Johni0702** [comment]
https://fabricmc.net/wiki/player:tutorials:logs_ml:windows
(this should apply even for non-fabric)

**Comment by Minecodes** [comment]
Thats the log from the last try to start Labymod with Replaymod: https://hastebin.com/towovudafu.sql

**Comment by Johni0702** [comment]
That's just the crash report again.
Try to find a file which starts like https://hastebin.com/unomudazuz.md but also includes https://hastebin.com/towovudafu.sql.

**Comment by Minecodes** [comment]
But i have't an other

**Comment by Johni0702** [comment]
Then try to get it directly from your launcher. How you do that depends on which launcher you're using but there should generally be an option to "Show console after game starts" or something like that.

**Comment by Minecodes** [comment]
it was an addon, thank you for the help
