### ISSUE TITLE
Render GUI is cropped on Retina screens

### ISSUE THREAD

**Issue by Andrews54757** [ReplayMod/ReplayMod#338]
The render gui does not account for the double-resolution of retina Macs, resulting in a cropped GUI in the bottom left corner 1/4th the size of the game window.

<img width="966" alt="Screen Shot 2020-08-21 at 12 59 46 PM" src="https://user-images.githubusercontent.com/13282284/90915939-3ae32200-e3ae-11ea-9f19-85fde656c244.png">

**Comment by Kloetzchengrafikk** [comment]
Please fix that! it's so annoying to restart minecraft always after rendering something...

**Comment by JacksonChen666** [comment]
@Kloetzchengrafikk umm.. just resize the window after you manage to click the done button when it's done rendering. does not require a restart of the game to operate correctly again after rendering.

**Comment by Kloetzchengrafikk** [comment]
Hmm. For a few months now, Minecraft automatically switches to full screen when I start it (it came suddenly).
For some reason I can't make the window any smaller either, as this menubar doesn't come down from the top when I move my cursor up.

(Mac with m1 Chip)
