### ISSUE TITLE
Rapidly going left then right crashes the game

### ISSUE THREAD

**Issue by countingsort** [ReplayMod/ReplayMod#34]
When viewing a replay going right left right left (ie. spamming adadadad on standard controls) crashes the game after you've build up a certain speed.

**Comment by CrushedPixel** [comment]
Thanks for your report! Could you please open a bug report in the ReplayMod Forums? http://replaymod.com/forum
Make sure to include the ReplayMod version you're using and the full crash report, so we can fix the issue.

**Comment by countingsort** [comment]
I'd rather not register in a forum which doesn't even manage to escape the search query.

**Comment by CrushedPixel** [comment]
In that case we can't help you.
