### ISSUE TITLE
The method getBottom() is undefined for the type CubicOpenGlFrame

### ISSUE THREAD

**Issue by gawinwong** [ReplayMod/ReplayMod#345]
I wanna know how to get six direction of a frame, but when I turn to EquirectangularToRGBProcessor, just found that the method getBottom() is undefined for the type CubicOpenGlFrame, could someone tell me the implementation of rawFrame.getLeft() rawFrame.getRight() rawFrame.getFront() rawFrame.getBack() rawFrame.getTop() rawFrame.getBottom()

**Comment by Johni0702** [comment]
They're automatically generated by Lombok.
Lombok is a compiler plugin (more of a hack really, it requires specific support for each compiler and an IDE plugin) which generates plain old getters/setters and a bunch of other stuff from annotations:
https://github.com/ReplayMod/ReplayMod/blob/23e51d7099c173d7bce210b62c077a0d6c5fdcee/src/main/java/com/replaymod/render/frame/CubicOpenGlFrame.java#L8-L9

You're not the first one to be confused by that, so I think it's time to finally get rid of it. The benefits of not auto-generating the getters really doesn't outway the confusion and other issues it has caused.

**Comment by Johni0702** [comment]
https://github.com/ReplayMod/ReplayMod/commit/16c759f1ddd4ea8d50181042f39b045c384d3d95
