### ISSUE TITLE
Load replays into Replay Viewer most recently modified first

### ISSUE THREAD

**Issue by Johni0702** [ReplayMod/ReplayMod#346]
Currently it does whatever the OS gives us which happens to be alphabetically most of the time, which is exactly the inconvenient way around.

**Comment by TheChocolateOre** [comment]
Is an Order By button fissible here or too much unnecessary work? Most of the time I work with the creation order, even if I edit a previous replay, I expect it to hold its position.

**Comment by Johni0702** [comment]
This is about load order only. Display order is not going to change (for now).
The current load order is more or less undefined (tends to be alphabetically though). The current display order is already based on the creation date, regardless of the load order.
It's just that atm the oldest replays happen to load first, so you always have to wait for all of them to have loaded just to be able to open the one you just recorded.

**Comment by TheChocolateOre** [comment]
Oh.. you are talking about cache algorithms, for behind the scenes. Now, I get it.
