### ISSUE TITLE
Just search the entire .minecraft folder for ffmpeg.exe

### ISSUE THREAD

**Issue by Johni0702** [ReplayMod/ReplayMod#347]
Cause people routinely manage to put somewhere other than `.minecraft/ffmpeg/bin/ffmpeg.exe`.

**Comment by LindaJuffermans** [comment]
Does this work for other launchers, e.g. when my instance is in `c:\Users\lyn\AppData\Roaming\gdlauncher_next\instances\FTB Interactions 2.0.9\`?
If my instance **is** in a different launcher's instance folder, will it still also look for ffmpeg.exe anywhere in `c:\Users\lyn\AppData\Roaming\.minecraft\`?

**Comment by Johni0702** [comment]
It'll search the folder which MC uses to store all its stuff (`MinecraftClient.runDirectory`). So, yes to the first question, no to the second one.
