### ISSUE TITLE
Add center cross in spectate mode

### ISSUE THREAD

**Issue by TheChocolateOre** [ReplayMod/ReplayMod#357]
Right now, the spectate mode renders no cursor at the center.
The cross seems to be strictly bounded by a 36x36 rectangle at 1920x1080. I'm not sure about its blend mode though. Seems like a 
negative or negative-overlay at 50%..?

![2020-08-05_10 17 36](https://user-images.githubusercontent.com/50585073/92027100-bf4c8200-ed6a-11ea-978e-5d3fb93a4e63.png)

**Comment by Nemos59** [comment]
why having to render the cross, if the inventory will not be rendered? that will look odd

**Comment by TheChocolateOre** [comment]
It helps the viewer focus better (I'm biased here, but I make building tutorials and the cross really helps). I doubt that a few pixels in the center will make it odd. Anyway, I was hoping moving towards screen record-ish with replay mod. But, that would require to solve the walking animation (right now it's like sliding in ice), inventory, hp, hunger..etc.. I will continue putting it manually.
