### ISSUE TITLE
Forge version for 1.16

### ISSUE THREAD

**Issue by PlazmaKG** [ReplayMod/ReplayMod#360]
Is there any plans of making a Forge version of ReplayMod for 1.16? I'd use Fabric but literally every other mod I use requires Forge.

**Comment by Nemos59** [comment]
ReplayMod will not use Forge, it's much simpler to use Fabric.

**Comment by Johni0702** [comment]
This lists some of the reasons if you want more than just a "no": https://www.reddit.com/r/feedthebeast/comments/c0wkph/modmakers_how_likely_are_you_to_use_fabric_over/er8z4hr/?utm_source=reddit&utm_medium=web2x&context=3
