### ISSUE TITLE
Render queue not persisted if name of existing job is changed

### ISSUE THREAD

**Issue by Johni0702** [ReplayMod/ReplayMod#362]
> If I create a new set of paths, click [Render Camera Path] (floppy disc icon) -> [Add Current Configuration] -> change name -> [Add to Queue] ... that persists.
But if I open Render Queue, and edit the name of an EXISTING item, that does not persist.

**Comment by LeigerGaming** [comment]
Ah, I see I should have created it as a bug report here :)
Thanks for copying my Discord post over. I'll follow this for updates!
