### ISSUE TITLE
Skin layers missing in first person view

### ISSUE THREAD

**Issue by LindaJuffermans** [ReplayMod/ReplayMod#363]
Minecraft 1.16.2, ReplayMod 2.4.4, no other mods
The outer skin layer shows in 3rd person view but not in 1st person view. Same observation in rendered video.
![3rd-person](https://user-images.githubusercontent.com/31929183/93178382-70bcc180-f734-11ea-9ec5-8b4b37772bcb.png)
![1st-person](https://user-images.githubusercontent.com/31929183/93178391-73b7b200-f734-11ea-8792-d893d198b696.png)

**Comment by Johni0702** [comment]
My skin doesn't have an outer layer on the hand, could you attach your replay file?

**Comment by LindaJuffermans** [comment]
Github doesn't support .mcpr...
[2020_09_15_09_16_09.zip](https://github.com/ReplayMod/ReplayMod/files/5224281/2020_09_15_09_16_09.zip)
