### ISSUE TITLE
Keyframe shortcuts don't work

### ISSUE THREAD

**Issue by TheChocolateOre** [ReplayMod/ReplayMod#378]
They are bound to I, O, 0, but they don't seem to work. Am I missing something?

Minecraft 1.16.3
ReplayMod 2.4.5

**Comment by Johni0702** [comment]
[2.4.5](https://github.com/ReplayMod/ReplayMod/milestone/2) is not [2.5](https://github.com/ReplayMod/ReplayMod/milestone/1)
New features and major changes will generally go into 2.5 (MC 1.16.3 support being the notable exception cause it only required minor changes), which is still WIP.

(Side note: being bound to `0` means not being bound by default. It's not the same as being bound to `Keyboard.KEY_0`)

**Comment by TheChocolateOre** [comment]
My bad, I thought closed issues ship immediately..
