### ISSUE TITLE
Immersive Portals Mod Not rendering correctly

### ISSUE THREAD

**Issue by DavidChen-cxl** [ReplayMod/ReplayMod#380]
Immersive portals mod (github.com/qouteall/ImmersivePortalsMod) allows the player to seamlessly travel between dimensions and see the surroundings of the destination through the portal. However, replay mod no longer renders correctly once the player travels through the portal, neither does it render the other side of the portal ("see-through" feature), as is shown in the following screen recording & rendered video: drive.google.com/drive/folders/1EDfQAjRNnsc1arqrbAlUyHW70HiYc0Wr?usp=sharing
Is this possible to fix? 

Game version: 1.16.3 fabric loader 0.10.0 build 208
Mod list:
fabric api 0.22.0 build.408
replaymod 2.4.5
immersive portals 0.36
optifabric 1.6.4
optifine 1.16.3_HD_U_G3
carpet mod 1.4.11
voxelmap 1.10.11
worldedit 7.2.0-beta-05

**Comment by Johni0702** [comment]
Possible? Yes. Feasible? Ehhh....

It's probably mostly on IP, it would have to structure its networking and world handling in such a way that it would still function correctly when all client-bound packets are recorded and later replayed with a different main player than it was recorded with (packets for the recording player's entity and its movement are automatically injected by the RM, so long as the recording player doesn't change dimensions, that should be good enough).

You also must not use any of RM's "ReplayStudio" features (the Start/Stop/Pause/Resume recording buttons, the Edit function and Quick Mode), those all assume there to only be one world and would require deep integration with IP, which isn't going to happen.
