### ISSUE TITLE
RLcraft incompatibility 

### ISSUE THREAD

**Issue by Dragonlord1005** [ReplayMod/ReplayMod#389]
Whenever I run replay mod alongside rlcraft, it loads the game, but the buttons added in by the replay mod don’t show up, meaning that I can’t view the recordings I made

**Comment by Nemos59** [comment]
can you send the `.minecraft\logs\latest.log` file please?

**Comment by Johni0702** [comment]
https://www.replaymod.com/docs/#troubleshooting-compatibility-custom-main-menu
