### ISSUE TITLE
Automatic "render all keyframes" button in keyframe manager

### ISSUE THREAD

**Issue by Abwasserrohr** [ReplayMod/ReplayMod#397]
The keyframe manager could have a "render all keyframes" button that then would open the render settings window once to set all the video render settings, to select the file folder and the file type. The file name could be the same as the name of the saved keyframes.

Instead of the "Render" button, it could have a button that allows to add all the stored keyframes with the settings from the window with the settings into the render queue, like "Add to queue".

Hope that makes sense. At the moment, I have like 5 - 10 different keyframes in the keyframe manager, having a button to add all of them in one step to the render queue could be a huge time saver. =)

**Comment by Johni0702** [comment]
The Render Queue will receive significant usability improvements in 2.5.0 which should do more or less what you're looking for.
In particular:
- (https://github.com/ReplayMod/ReplayMod/issues/168) There's a button to add selected keyframe presets (the GUI will support multi-select) to the render queue. When clicked, it'll open the render settings window once for each preset. It will use the name of the preset to derive the output file name, so if that's the only thing you want to change between them, then you can just spam the Add to Queue button.
- (https://github.com/ReplayMod/ReplayMod/issues/317) The queue will be persisted when you close the replay, so you can prepare the queues of multiple replays without having to immediately render them.
- (https://github.com/ReplayMod/ReplayMod/issues/349) Selecting multiple replays in the Replay Viewer screen (will also support multi-select) will replace the Load button with a button to render the queues of all selected presets.

There were also some changes to the general render queue flow (even if you don't use any of the above) as explained in https://github.com/ReplayMod/ReplayMod/issues/349#issuecomment-683402601. These do not relate directly to your request, I'm just mentioning them for completeness sake.

**Comment by Abwasserrohr** [comment]
Oh sorry, didn't look into the already closed issues. 👍
