### ISSUE TITLE
Replays are blank?

### ISSUE THREAD

**Issue by CalciumLad** [ReplayMod/ReplayMod#402]
When I open a replay to edit it, it’s usually completely blank. Sometimes a chunk might load, occasionally it will all load, but mostly it will have no blocks, no player, nothing. Entering quick mode and leaving will cause the player to appear, but as soon as you press play it goes away. Idk if this is something with my Minecraft settings or the mod itself

**Comment by awesomecoder3000** [comment]
Maybe you don't spawn near the player, try going to the player menu, and clicking the player's face.
