### ISSUE TITLE
why do the npc don't show

### ISSUE THREAD

**Issue by StarGalaxianVoid** [ReplayMod/ReplayMod#405]
why this no work
![Screen Shot 2020-11-05 at 12 48 43 PM](https://user-images.githubusercontent.com/67572797/98199586-6cf43100-1f66-11eb-8e93-1fcc1da968b9.png)

**Comment by Johni0702** [comment]
Could have any number of reasons, from the fact that you're using an old version which might have had bugs recording them (try updating), to the fact that you're using other mods which might interfere (try without any other mods).
