### ISSUE TITLE
1.16.4

### ISSUE THREAD

**Issue by Johni0702** [ReplayMod/ReplayMod#406]
Most likely just a protocol version bump (only packet that changed is server-bound).

**Comment by awesomecoder3000** [comment]
Do you know when you will release v2.5.0? (For 1.16.4)

**Comment by Johni0702** [comment]
Probably in about a week if no major issues are found during beta testing.
RM 2.4.5 should be compatible with 1.16.3 except for "ReplayStudio" feature (that is: quick mode, spectator keyframes, edit, start/stop/pause/resume recording).

**Comment by awesomecoder3000** [comment]
Thank you so much!
