### ISSUE TITLE
Optifine incompatibility issue

### ISSUE THREAD

**Issue by cocofish82111** [ReplayMod/ReplayMod#413]
![2020-11-15_22 48 29](https://user-images.githubusercontent.com/62784199/99188121-44094280-2795-11eb-8117-5c2cf957186f.png)
![2020-11-15_22 48 09](https://user-images.githubusercontent.com/62784199/99188124-466b9c80-2795-11eb-8d74-9ce319a45586.png)

I'm a texture pack maker. As you can see, while in the replay, I can't see the exact texture which is made through Optifine's CTM. But CIT things like the car are normal.

Just take an example, these crossing on the road is the furnace but textures replaced by Optifine. The crossing block's properties file(files used for optifine's function) is like: 
`matchTiles=textures/block/furnace_
method=fixed
tiles=textures/0extra_building_block/03
name=03`
which means when the furnace's name (furnace can have names by renaming in the anvil) is 03, its texture is replaced.

In the singleplayer game, it appears normal, but in the replay, it is broken. Other things using this feature like hopper are broken too. Maybe it is because in the replay mode the container block's names are not applied.(My personal guess)
Hope you can fix it. It means a lot to me in a sense. :D

Minecraft 1.16.4   OptiFine HD U G5   Fabric   replaymod-1.16.4-2.5.0

**Comment by Johni0702** [comment]
Did you touch the Start/Stop/Pause/Resume button while recording that replay?
If you did, then I have an idea as for how the names might have been lost (and as a workaround, you can just not use those buttons until that's fixed).
Otherwise I can't help you cause Optifine is proprietary, so I am neither allowed to look at its source code nor to fix any issues in it. You're at the mercy of its author in that case.

**Comment by cocofish82111** [comment]
I don't pause any button while recording the replay.
While in the replay viewer, things appear the same no matter what behavior I do (be in spectator mode, set keyframes then pause the play button, render video, in rendered video )
![image](https://user-images.githubusercontent.com/62784199/99903734-3c035280-2d01-11eb-8b9a-accb690a3785.png)
