### ISSUE TITLE
Issue with RM 2.5 on 1.15.2

### ISSUE THREAD

**Issue by RaderRMT** [ReplayMod/ReplayMod#414]
In the Replay Viewer, we can see the chat input when opening the chat. Keybinds are also not working properly, we have to use a mouse button (left or right) after pressing the keybind to make them work.
Logs do not show anything wrong.

**Comment by LindaJuffermans** [comment]
Yesterday someone reported the chat opening on 1.16.4 but I wasn't able to reproduce.

**Comment by drewc5131** [comment]
Can confirm this is happening on 1.14.4 as well. which is a major problem because due to #386 not being fixed yet i need to use this version :\
