### ISSUE TITLE
Server-side recording for "Open to LAN" multiplayer?

### ISSUE THREAD

**Issue by Resuz** [ReplayMod/ReplayMod#42]
Currently if I share my world to lan, all other players will be not recorded if they are at big distance from me. I heard that server-side recording is development, but I was wondering if it also work with client Minecraft versions in order to support "Open to LAN"? Would be neat.

**Comment by Johni0702** [comment]
> I heard that server-side recording is development

No, sorry, there are currently no plans of implementing server-side recording.

**Comment by Adogs1** [comment]
> > 听说服务器端录制是开发
> 
> 不，对不起，目前没有实施服务器端录制的计划。

Now？
