### ISSUE TITLE
Spectating entities doesn't work in 1.8.9

### ISSUE THREAD

**Issue by LindaJuffermans** [ReplayMod/ReplayMod#432]
I tried with RM 2.3.0, 2.4.0, 2.4.3 and 2.5.1; I get the crosshair when I look at a cow but no amount of right-clicking switches to spectating from the cow's view. No other mods loaded. Forge 11.15.1.1722 (recommended).

**Comment by ItsMrCube** [comment]
Can confirm, I'm having the same problem.
