### ISSUE TITLE
ReplayMod provides/requires outdated mixin subsystem 0.7.10 on MC 1.11.2 and older

### ISSUE THREAD

**Issue by mpfaff** [ReplayMod/ReplayMod#438]
The ReplayMod is conflicting with another mod, SkyBlockcatia, which requires mixin subsystem version 0.7.11

**Comment by RaderRMT** [comment]
ReplayMod uses Mixin 0.8 if i remember correctly, so SkyBlockcatia's Mixins are outdated

**Comment by Johni0702** [comment]
Mixin 0.8 only works on MC 1.12+, so I just kept whatever version we had for pre-1.12. And apparently there's a 0.7.11, while we're still on 0.7.10.
I doubt they actually need 0.7.11, so if they had specified their requirements in a more relaxed way, then it would probably just work. But oh well, guess I'll bump our bundled version to 0.7.11 in the next release.
For the time being, you can try renaming the jar files such that RM gets loaded after SkyBlockcatia.

**Comment by mpfaff** [comment]
I was able to modify the compiled jar for SkyBlockcatia to lower the requirement to 0.7.10 and it works flawlessly.
