### ISSUE TITLE
API for developers to play cutscenes in their mods?

### ISSUE THREAD

**Issue by diabolical17** [ReplayMod/ReplayMod#439]

**Comment by Johni0702** [comment]
Please elaborate.

**Comment by diabolical17** [comment]
Developers create camera paths in game. Then press export as replay file. They can then, using the library, import the replay file (from a resource pack/path) and play it. 

The chunks from the replay file will be loaded temporarily and any players/entities loaded aswell.

Then the developer can play, pause, rewind, speed up, slow down etc. via code.

**Comment by diabolical17** [comment]
See this: https://github.com/raphydaphy/CutsceneAPI

An example, but its for 1.14, and very outdated.

**Comment by Johni0702** [comment]
From the game's PoV, replays appear to be a (more or less) regular server. And just like you cannot be connected to two servers at the same time, you cannot play a replay while connected to another server or single player. That seems like a deal breaker for what you want or am I missing something?

**Comment by diabolical17** [comment]
Personally, i'm suggesting this for a massive single player mod i've been working on. It relies heavily on story. Even if it requires the player to leave the world silently then play the replay, then re-join seamlessy, it would work.

If the case is that the player needs to leave the world to play the cutscene, the loading scene can easily be replaced with mixins.

**Comment by Johni0702** [comment]
Hm, I don't think that's useful enough in general to warrant creating an API for it.
Seems easier and much more flexible to just update that other project.

If you want to play with it nonetheless, here's a piece of code which loads a replay from a file, plays it until there's a world, then does some processing (here you could continue playing the replay and move the player as required for your cutscene) and then, some time later, closes the replay (before recursively loading the next one): https://github.com/ReplayMod/ReplayMod/blob/57c7362e3417ec563235a3e41a300e4a2ab9a709/src/main/java/com/replaymod/render/gui/GuiRenderQueue.java#L217-L257

**Comment by diabolical17** [comment]
Awesome thanks :+1:
