### ISSUE TITLE
Replay speed/rendering

### ISSUE THREAD

**Issue by TakeshiKS** [ReplayMod/ReplayMod#44]
Small issue - I seem to be missing all the data in my replaymod-render and replaymod-online .cfg files. The only thing I know for sure I'd need these for is to change the render framerate with replaymod-render.cfg for the purpose of smooth slow-mo video. (I'm also assuming I have to raise my framerate within Minecraft in order to have any benefit from a higher-frame replay, but this is a simple task.) Regardless, I'd like to learn why this data is missing and what I can do to restore it.

Secondly, a request - this is a higher priority to me, being that I have only once had the desire to do a super slow video. As a builder who does timelapses of (sometimes very large!) projects, 8x speed just doesn't cut it. I'd love to see options for 16x, 32x, and 64x implemented. Seems to me to be a pretty easy code modification, but being *extremely* green at this I'm afraid I'd just mess something up if I were to try it myself; not to mention I don't even know where to look within the mod directory to find the proper location for these arguments.

Any feedback would be much appreciated. Thanks!

**Comment by CrushedPixel** [comment]
Your assumptions are wrong - you can render videos with up to 120fps using the ReplayMod without touching any configuration files or code. This should be more than enough for any purpose. If you want to have slow-motion or super fast speed (64x is easily doable), you can control this using Time Keyframes. I explain all of it in this [tutorial video](https://www.youtube.com/watch?v=3aCrj9g2TqE).

Also, please use the [ReplayMod Forums](https://replaymod.com/forum) in the future, as we don't actively monitor the GitHub issues.
