### ISSUE TITLE
Incompatible mods

### ISSUE THREAD

**Issue by XJaramilloWEBX** [ReplayMod/ReplayMod#440]
I'm very sorry if I have spelling mistakes but I use a translator.

Well I have one or more like two cases and it is that replay mod crashes when inserting two mods that are very essential for me:

Galacticraft-Planets-1.12.2-4.0.2.280
GalacticraftCore-1.12.2-4.0.2.280
MicdoodleCore-1.12.2-4.0.2.280
malisiscore-1.12.2-6.5.1

I use TLauncher as a launcher and before the loading screen even appears, two windows appear, one of them has a game code and the other a warning that I have crashed.

**Comment by RaderRMT** [comment]
Use the legal launcher.
