### ISSUE TITLE
License

### ISSUE THREAD

**Issue by calloutplayed** [ReplayMod/ReplayMod#441]
I uploaded this mod in curseforge and metioning that it's not mine it's yours I had did that because this mod is not found  other websites . So I but that had said this to me :
This project has been reported for IP license non-compliance. 
The terms stated in the original project license specify conditions which you haven't met:
https://github.com/ReplayMod/ReplayMod/blob/develop/LICENSE.md

**Comment by RaderRMT** [comment]
The ReplayMod devs does not want the mod to be on CurseForge.

**Comment by Johni0702** [comment]
As I already said in the CF comments, "metioning that it's not mine it's yours" is not how copyright works.

As the message from CF says, you have to comply with the license (that's the text which they and I linked to you, and not just the short summary which you quoted at me on CF). You cannot just re-upload mods (or anything really) unless you've been explicitly granted permission to do so (either by a law or via a license), and this permission is usually coupled to certain conditions which you have not met (nor even read, I'd guess).

I have also already explained why I don't think it should be on any other website (it'll get outdated), so I'm not going to elaborate on that again.
