### ISSUE TITLE
ReplayMod-1.7.10-2.5.1 crashes on startup

### ISSUE THREAD

**Issue by LindaJuffermans** [ReplayMod/ReplayMod#443]
Clean installation with Forge 1.7.10-10.13.4.1558 (recommended) and ReplayMod-1.7.10-2.5.1-jar
[fml-client-latest.log](https://github.com/ReplayMod/ReplayMod/files/5719443/fml-client-latest.log)

No issues found with ReplayMod-1.7.10-2.5.0-jar

**Comment by Johni0702** [comment]
Grrrr, probably ForgeGradle again. The 2.5.1 jar is missing random files again (note how it's only 2.5MB whereas the 2.5.0 one is 10.5MB).

I have rebuilt 1.7.10-2.5.1 locally and replaced the broken download. I have not tried to run the new jar (merely checked that it now has the expected size) but given 2.5.0 works, 2.5.1 will probably work as well.

**Comment by LindaJuffermans** [comment]
Verified
