### ISSUE TITLE
Cache folder attribute issue on ReplayMod

### ISSUE THREAD

**Issue by artdeell** [ReplayMod/ReplayMod#449]
So, i'm running Minecraft on a heavily modded Linux machine, and when I join the world with recording enabled, i instantly see that mod can't start the recording.

After examining logs i found out that there are two problems:
1. Messed up NIO on my system
2. Replay Mod doesn't try to catch FileSystemException when trying to make the cache folder invisible.

Since messed up NIO can only be solved by a VM update, i am contacting the mod maintainers.

Version: 2.5.1 for Minecraft Forge 1.12.2
Code line: 257 in com.replaymod.core.ReplayMod.getCacheFolder

**Comment by Johni0702** [comment]
> Replay Mod doesn't try to catch FileSystemException when trying to make the cache folder invisible.

Huh, which file system is this running on and what exactly is the error it is throwing?
Based on the JavaDoc I would expect that method to throw an `UnsupportedOperationException` and testing on my machine (ext4) seems to confirm that.

> Since messed up NIO can only be solved by a VM update, i am contacting the mod maintainers.

Why would the mod maintainers be able to help with your JVM. Shouldn't you contact your distribution / JVM vendor instead?

**Comment by artdeell** [comment]
Mod maintainers can add the catch clause

This exception is extremely rare, and the reason is that the restrictions do not allow me to set any kinds of attributes.
By the way

It was on Android.

**Comment by Johni0702** [comment]
Please contact your distribution / JVM vendor then.
I will not add blanket catch clauses as a dirty workaround to bugs in niche 3rd party software, that's just asking for actual issues to go unnoticed.

As is, I don't see anything which is actually wrong with the mod itself.

**Comment by artdeell** [comment]
No modmakers want to assist in terms of bringing their mods to mobile platforms...

**Comment by Harsh-bot-beep** [comment]
Hmm ArtDeell Is Researching On Replay Mod For POJAV Launcher :eyes:
