### ISSUE TITLE
Random GUI elements missing

### ISSUE THREAD

**Issue by andybot89** [ReplayMod/ReplayMod#460]
There is no "Replay Center" button on the title screen.
There is no "Start Recording" button on the pause menu.
There is no "Pause Recording" button on the pause menu.
There is no "Log into your replay mod account" popup on first startup.
There is no keybind option that allows for changing the "Start recording" keybind.

**Comment by andybot89** [comment]
UPDATE: Optifine was causing this issue.

**Comment by andybot89** [comment]
UPDATE 2: I just removed optifine from my mods folder and this issue still persists.

**Comment by Johni0702** [comment]
> There is no "Replay Center" button on the title screen.
> There is no "Log into your replay mod account" popup on first startup.

The Replay Center and all other online features have been removed because we lack resources to maintain them.

> There is no "Start Recording" button on the pause menu.
> There is no "Pause Recording" button on the pause menu.

That's Optifine or some other mod, though so far it's always been Optifine. Or you have explicitly disabled recording for singleplayer / servers.

> There is no keybind option that allows for changing the "Start recording" keybind.

There never has been.
