### ISSUE TITLE
"Render All" Button is Grayed-Out

### ISSUE THREAD

**Issue by redstonecreeper8** [ReplayMod/ReplayMod#466]
I have several camera paths stored in my render queue; however, the option to render all of them seems permanently disabled. This defeats the primary purpose of the queue. Is this a bug or is there something I'm doing incorrectly? I can't find any information about this behavior online.

**Comment by RaderRMT** [comment]
Select all elements in the queue then press the Render All button

**Comment by Johni0702** [comment]
Duplicate of #447
