### ISSUE TITLE
incompatiblity

### ISSUE THREAD

**Issue by makerio90** [ReplayMod/ReplayMod#468]
also incompatible with https://github.com/rebane2001/livemessage

**Comment by Johni0702** [comment]
That mod is using an old version of Mixin. It needs to update to at least 0.8 to work with the ReplayMod.
If the mod doesn't actually depend on the old version of Mixin, you may be able to work around the issue by renaming either jar file is such a way as to change the order in which they're being loaded (e.g. rename `replaymod-1.12.2-2.5.1.jar` to `aaareplaymod-1.12.2-2.5.1.jar`)
