### ISSUE TITLE
Redesign hotkey buttons

### ISSUE THREAD

**Issue by Johni0702** [ReplayMod/ReplayMod#469]
![](https://cdn.discordapp.com/attachments/708311773450731591/804140701297278986/2.jpg)
I really like this suggesting.
It adds a background so the hotkey buttons are easier to read regardless of what's underneath them, moves them to the right so they don't overlay chat and vice versa, and makes them scrollable which is particularly helpful on small screens. There's even space to add a filter.

**Comment by Jg2525** [comment]
Virus
