### ISSUE TITLE
The rendered file has weird stutters on leaves with shaders

### ISSUE THREAD

**Issue by Marcell0101** [ReplayMod/ReplayMod#472]
Since the forum doesn't work I am posting this here, not exactly sure if this is the right place for it.
I used shaders (Sildur's Vibrant Shaders v1.281 Extreme VL) while rendering, and the leaves occasionally stuttered. Here is the rendered footage: https://www.youtube.com/watch?v=T20ZnAhXMRA
I rendered on 2560x1080, 60 Fps, 20 mbps (also happened on 10).
The ReplayMod version I have is the latest, the jar file name is replaymod-1.16.4-2.5.1
To have shaders and optifine I used a mod called optifabric-1.9.2
Minecraft is on 1.16.5
I tried providing as much info as I could, I'm not sure if this is a bug, or I am using the mod wrong, or my computer is bad (I have been having some weird issues lately), but thanks for any help!

**Comment by RaderRMT** [comment]
that's an issue with your shader
