### ISSUE TITLE
Keybind conflict in 1.8.9

### ISSUE THREAD

**Issue by LindaJuffermans** [ReplayMod/ReplayMod#478]
In 1.8.9 if ReplayMod has Q assigned to Quick Mode, it cannot be used to drop items in normal gameplay.

Tested with MultiMC, Minecraft 1.8.9, Forge-1.8.9-11.15.1.1722 and ReplayMod 1.8.9-2.5.2

(no relevant details in log, just adding for completeness)
[2021-02-18-1.log](https://github.com/ReplayMod/ReplayMod/files/6004541/2021-02-18-1.log)

**Comment by Johni0702** [comment]
Basically back-porting of https://github.com/ReplayMod/ReplayMod/commit/fd7b6030f9f34197fbd7a8ff8061c336cb8b8775 to prefabric era and dealing with any forge shenanigans (the reason it was 1.14+ in the first place) on the way.
