### ISSUE TITLE
Show time stretching/compression (relative to current speed) via colored bars in keyframe timeline

### ISSUE THREAD

**Issue by Johni0702** [ReplayMod/ReplayMod#482]
> Sometimes, when I turned on playback of replay timeline, the slider of the keyframe timeline started to jump. I couldn't figure out why, even the timeline sync hotkey couldn't fix it. This was because one time-keyframe has been shifted 450 milliseconds to the right, which caused time stretching before the keyframe and compressing time after it. Could you make additional colored lines to represent time compression or time stretching? It would be very helpful to see all unplanned displacement in time.
> ![](https://cdn.discordapp.com/attachments/708311773450731591/814158574678835213/speed_time.jpg)

**Comment by RaderRMT** [comment]
maybe also show the speed when hovering the bars with the mouse?
