### ISSUE TITLE
Conflict with mod dualhotbar

### ISSUE THREAD

**Issue by SakuraTao2007** [ReplayMod/ReplayMod#485]
RM 2.5.2
dualhotbar: latest
Minecraft version: 1.12.2

[dualhotbar.zip](https://github.com/ReplayMod/ReplayMod/files/6054400/dualhotbar.zip)

**Comment by Johni0702** [comment]
What is the issue?
If it crashes, please provide the `.minecraft/logs/latest.log` file. If it misbehaves, please explain.


Likely source: https://github.com/RebelKeithy/DualHotbar (that's the source linked for the 1.x version which is GPLv3 according to CF, there's a 2.0.0 version on CF which seems to violate GPL by being ARR and nor having any source links)
