### ISSUE TITLE
Chunks not showing in replay

### ISSUE THREAD

**Issue by LindaJuffermans** [ReplayMod/ReplayMod#489]
ReplayMod-1.6.4-2.5.2 SP

[Missing-Chunks-Raw-Recording.zip](https://github.com/ReplayMod/ReplayMod/files/6077607/Missing-Chunks-Raw-Recording.zip)

**Comment by itzJOHv** [comment]
https://www.mediafire.com/file/zi87e23gc3br1vl/replay.zip/file (uploaded to mediafire cuz it's too big for GH)

**Comment by Johni0702** [comment]
Don't see any missing chunks with either of those recordings (using RM 1.16.4-2.5.2). Either the issue was caused by another mod, something non-deterministic or it's not obvious which chunks are missing.
