### ISSUE TITLE
Game crashes when trying to render a video

### ISSUE THREAD

**Issue by tinbolw** [ReplayMod/ReplayMod#493]
Mod Version: 2.5.2
OS: macOS Big Sur 11.2.3

When trying to render a clip from the mod, the game starts it then it crashes.

Crash log: [crash-2021-03-17_17.10.07-client.txt](https://github.com/ReplayMod/ReplayMod/files/6160451/crash-2021-03-17_17.10.07-client.txt)

**Comment by 19175** [comment]
Just a random user but looking at your log it seems that ffmpeg is missing a library, maybe try re-installing it?
