### ISSUE TITLE
1.16 for forge?

### ISSUE THREAD

**Issue by MrSunnyTop** [ReplayMod/ReplayMod#499]
I was checking the site and it seems anything above 1.12.2 is Fabric, so I was wondering if there was a forge 1.16 version?

**Comment by RaderRMT** [comment]
No, and there will never be. Fabric is the only way to go.

**Comment by Johni0702** [comment]
I have wasted too many hours (possibly even days by now) wrestling with ForgeGradle and other stupid Forge peculiarities, and I don't agree with how Forge itself is developed either (see also points 1 and 2 of [this reply](https://www.reddit.com/r/feedthebeast/comments/c0wkph/modmakers_how_likely_are_you_to_use_fabric_over/er8z4hr/)).
So, for the foreseeable future I will not spend any time on the new (i.e. 1.13+) Forge (bad enough that I still have to deal with 1.7.10-1.12.2 Forge from time to time), and will stay with Fabric only.

ReplayMod is free software though, anyone is welcome to port it to the new Forge (shouldn't even be too difficult, the preprocessor already supports FG3). I just don't want to have to deal with it nor maintain it.

**Comment by MoSchaub** [comment]
There is a port https://github.com/unhappychoice/ReplayMod/releases/tag/1.0.0-beta2
