### ISSUE TITLE
Hotkey buttons are ignored if there is something clickable under them

### ISSUE THREAD

**Issue by RaderRMT** [ReplayMod/ReplayMod#500]
When you have Minecraft in a small window, showing the hotkeys can make 2 rows of buttons, like this:
![image](https://user-images.githubusercontent.com/41066767/112981358-5b9d0280-915b-11eb-872b-791b2577c577.png)

Let's say I want to open the Player Overview from here. I click on the `Player Overview` button and... nothing. It moved the cursor on the Keyframe Timeline to the position of the mouse cursor, totally ignoring the `Player Overview` button, same thing for any buttons unless there's no clickable things under them (like buttons or timelines).

**Comment by Johni0702** [comment]
Don't think this is worth fixing as it still leaves the issue of buttons going out of bounds which is more severe. Will probably just go with #469 to fix both.
