### ISSUE TITLE
Game Crash When Loading Replay

### ISSUE THREAD

**Issue by Unusual-Danger** [ReplayMod/ReplayMod#502]
While playing in a multiplayer server i decided to record. While attempting to load up the save the game crashed with this crash report. 
[crash-2021-04-02_16.02.59-client.txt](https://github.com/ReplayMod/ReplayMod/files/6251525/crash-2021-04-02_16.02.59-client.txt)

**Comment by RaderRMT** [comment]
Remove baritone. Reading the documentation would've allowed you find the issue by yourself.
