### ISSUE TITLE
found a bug

### ISSUE THREAD

**Issue by dolphin-cat** [ReplayMod/ReplayMod#508]
found a bug

**Comment by RaderRMT** [comment]
🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 
you know that you have to write what's the bug when opening the issue, so that the devs don't have to ask what the issue is...

**Comment by dolphin-cat** [comment]
the idea is for someone to see it and ask for the bug, then say the probelm

**Comment by RaderRMT** [comment]
> 
> 
> the idea is for someone to see it and ask for the bug, then say the probelm

that's the worst thing to do
