### ISSUE TITLE
Game Crashes During Render with Normal Minecraft Launcher

### ISSUE THREAD

**Issue by punsintended** [ReplayMod/ReplayMod#517]
Mod Version: 2.5.2
OS: macOS Big Sur 11.2.3

This is the first time that the mod has ever crashed for me during rendering.
[crash-2021-05-06_19.29.08-client.txt](https://github.com/ReplayMod/ReplayMod/files/6438163/crash-2021-05-06_19.29.08-client.txt)

**Comment by Johni0702** [comment]
Looks like macOS does not allow for `:` in file names under certain circumstances.
