### ISSUE TITLE
Replay does not show up in lunar client

### ISSUE THREAD

**Issue by Nacandcheese** [ReplayMod/ReplayMod#518]
I was playing Skywars on Hypixel with replay mod recording. I got a cool recording, and spent 10+ minutes painstakingly editing the video. I was going to convert to .mp4 but when I returned to the replay screen I was greeted with this amazing issue:
![image](https://user-images.githubusercontent.com/56834638/117548069-80a55080-aff8-11eb-9056-70d6987f15fc.png)
Despite the fact that my replay is clearly in the replay file, I cannot see the replay in the client at all.
![image](https://user-images.githubusercontent.com/56834638/117548106-a4689680-aff8-11eb-8778-3d7d8d7b63e0.png)
What I assume it would be is the file being corrupt, but I am not sure what to do. I cannot clearly see any way to uncorrupt it, and I do not want to attempt to recreate this video.

Minecraft version: 1.8.9

**Comment by RaderRMT** [comment]
ask lunar. this issue can be closed.

**Comment by LindaJuffermans** [comment]
Please report this to https://github.com/LunarClient/ReplayMod/issues

**Comment by hashblen** [comment]
This is a Lunar Client Issue. Please ask there : https://github.com/LunarClient/ReplayMod/issues

**Comment by Nacandcheese** [comment]
Alright. Thanks for letting me know, I will move it over there.
