### ISSUE TITLE
Unreasonable amount of memory used

### ISSUE THREAD

**Issue by Youmiel** [ReplayMod/ReplayMod#519]
The client took too much JVM memory when I was working on my replay recordings. Sometimes the client would encounter an OutOfMemory Error after several loads.
<br>
**Ways to Reproduce**
1. Launch Minecraft client with replay mod(with profiler is better).
2. Prepare some replay recordings, long-term recordings(for example, over 1h time-elapse recordings) are better for reproducing this issue.
3. Load, drag the timeline and exit replay repeatedly.
4. The memory occupation goes up, the client will become laggy or encounter a OutOfMemory Error.
5. With JProfiler, it shows that the instances of com.replaymod.replaystudio.util.Location, java.util.TreeMap$Entry and java.lang.Long taked most of the memory in JVM(with -Xmx4G)<br>
At start:<br>
![1](https://user-images.githubusercontent.com/70473080/117559203-edcaeb80-b0b5-11eb-8720-2a06ef4eac98.png)
After several loads:<br>
![2](https://user-images.githubusercontent.com/70473080/117559205-ef94af00-b0b5-11eb-9707-c8f757474ecf.png)
<br><br>
**System Details**
Minecraft Version: 1.16.5
Operating System: Windows 10 (amd64) version 10.0
Java Version: 11.0.2, Oracle Corporation
Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
JVM Memory up to 4062MB
<br><br>
**Mod List**
fabricloader@0.11.1
fabric-api@0.30.0+1.16
replaymod@1.16.4-2.5.2
notenoughcrashes@2.1.4+1.16.1
raisesoundlimit@0.0.1-SNAPSHOT
modmenu@1.14.15
spark@1.5.2
optifabric@1.9.2
OptiFine_1.16.5_HD_U_G7<br>

<br>
I'm just a gamer and a beginner in Java, that's all the informations I can give.

**Comment by TheAwesome98-Real** [comment]
For “just a gamer”, you’re a lot more knowledgeable than others I know. I think those classes that take up the most amount of memory are badly optimised (or the ones that run it), but I don’t know because I haven’t read the source code yet.

**Comment by Youmiel** [comment]
Cannot reproduce with latest version of Replay. However, I would reopen this issue if the same problem happens again.
