### ISSUE TITLE
Rendering comes out very distorted

### ISSUE THREAD

**Issue by MamitaLena** [ReplayMod/ReplayMod#52]
![rendering problem](https://user-images.githubusercontent.com/38843148/52926383-21fe3a00-32fb-11e9-9fa5-47f3bee2f856.PNG)
![rendering error2](https://user-images.githubusercontent.com/38843148/52926390-288cb180-32fb-11e9-8134-a2e3dc7de32f.PNG)

Sometimes the files come out fine, sometimes they look like these screen captures entirely or only in part. The video usually jerks a little and then begins to distort. Sometimes midway it will render correctly again. I can't figure out what is causing it. I have windows 10, the latest java version, using 1.12.2 Minecraft, and the latest ffmpeg installed. Thank you.

**Comment by Johni0702** [comment]
This is a known issue with Windows Media Player. Try a different player and it'll play fine.

**Comment by MamitaLena** [comment]
I have tried several players and even in Cyberlink Power Director, the same occurs.

**Comment by Johni0702** [comment]
Please check whether the artifacts show up in the preview during rendering.

If they don't, then it's either an issue with ffmpeg which we're using to encode our frames into a video or with the video players you tried (which ones specifically? might just be that they internally all use the same decoder as WMP).

If you decide to open an issue with ffmpeg, you'll need to know that the "Command Line Arguments" in the render settings is what we're calling ffmpeg with and ffmpeg's output is logged to the `export.log` file in your `.minecraft` folder. If you open one with any of your video players, they can probably use the content of those two as well.

**Comment by MamitaLena** [comment]
It doesn't occur during the preview. The preview looks perfect and then when it renders some of the videos look good and then there is a little jerk and it begins to distort, some render fine,

 and some are distorted throughout. I have tried to do different things to be able to predict whether or not it will happen but it appears to be rather random although usually if a video fails once it will again no matter how many times I try to render it.
There have been some crashes during rendering... 

[crash-2019-02-17_19.30.04-client.txt](https://github.com/ReplayMod/ReplayMod/files/2883135/crash-2019-02-17_19.30.04-client.txt),

[crash-2019-01-25_19.31.59-client.txt](https://github.com/ReplayMod/ReplayMod/files/2883139/crash-2019-01-25_19.31.59-client.txt)


[2019-02-19-1.log.gz](https://github.com/ReplayMod/ReplayMod/files/2883219/2019-02-19-1.log.gz) I believe this is the log for the file below.


[2019_02_19_23_40_02.zip](https://github.com/ReplayMod/ReplayMod/files/2883221/2019_02_19_23_40_02.zip) This one works partway and then distorts toward the end.

**Comment by CrushedPixel** [comment]
Can you upload one of the video files for review? Please use a service like Dropbox/Google Drive, which doesn't re-encode the video, so we can get the original file.

**Comment by MamitaLena** [comment]
Do you have an email address I can send it to?

**Comment by CrushedPixel** [comment]
Just share the link here.

**Comment by MamitaLena** [comment]
https://drive.google.com/file/d/1HeOPkFEXPqHJzhiDj17FDxnNQRbwRfNJ/view?usp=sharing

**Comment by CrushedPixel** [comment]
Your video plays *perfectly fine* on my machine (macOS with QuickTime Player), just as Johni suspected.

It is a very large file, however, which is probably why your video players have problems properly displaying them. In any case, when editing the video (e.g. with Premiere or Sony Vegas) or uploading it to YouTube, there won't be the distortion artifacts you described.

You might want to consider rendering with slightly lower quality to lower the file size - you don't really need the "best quality" preset, the "default quality mp4" preset should suffice for pretty much all use cases.

**Comment by MamitaLena** [comment]
Well, sorry to trouble you with it. I still don't understand why some of the videos come out fine and others don't but I will have to have my husband try them on his mac...maybe it's an intel problem. Anyway, we got through the project and managed with the clips that did work. They really wanted high quality for this project. Here is a link so you can see what we were doing... https://www.youtube.com/watch?v=WT4DKllNlTw
Thanks again for checking that for me though! Best regards, Coleen
