### ISSUE TITLE
Incompatible with enhanced block entities

### ISSUE THREAD

**Issue by Samisaprogrammer** [ReplayMod/ReplayMod#532]
Chests, signs, and bells are invisible. I am using the latest cursforge version of both.

**Comment by Samisaprogrammer** [comment]
Only installed mods are fabric api, fabric-language-kotlin, replay mod, enhanced block entities and mod menu.

**Comment by RaderRMT** [comment]
did you try without enhanced block entities?

**Comment by Samisaprogrammer** [comment]
Yes, chests, signs, and bells are all visible without enhanced block entities. But if you remove replay mod and don't remove enhanced block entities they are still visible.

**Comment by Johni0702** [comment]
![](https://i.johni0702.de/ZBM7Q.png)

> I am using the latest cursforge version of both.

We're not publishing the ReplayMod via CurseForge. And "latest version" is not helpful, those can change and give no reliable info about which version you're actually using cause it assumes that you did not on accident download an older version (and that you did actually download from CurseForge in the first place, which is questionable given we don't publish there), and no updates have been released between you downloading and your post being read.

**Comment by Samisaprogrammer** [comment]
I meant i downloaded fapi and Enhanced block entities from curseforge.

**Comment by Samisaprogrammer** [comment]
Also im pretty sure you need to turn on enhanced block entities in video settings.

**Comment by Johni0702** [comment]
Appears to be on by default (would be weird if a mod was off by default, might as well just not install it then):
![](https://i.johni0702.de/4QwZE.png)

**Comment by Samisaprogrammer** [comment]
Well im not sure what the issue is for me then

**Comment by skyshade121** [comment]
This bug also occurs for me.

**Comment by ProfanedBane** [comment]
So myself and a few of my friends have ran into this issue whilst using large amounts of client mods.

I've encountered some interesting behavior whilst trying to find the exact mods needed to reproduce the issue as @Johni0702 appears to not be encountering the issue at all.
Using this setup:
- Minecraft 1.16.5
- Fabric Loader 0.11.6
- Fabric API 0.37.0+1.16
- Enhanced Block Entities 0.4
- Replay Mod 1.16.4-2.6.0

I've tested both a FRESH install/instance using MultiMC alongside my current setup with all mods bar the above disabled.
The fresh install does not encounter any issues much like Johni, however my already existing setup with all other mods removed DOES encounter the visibility issue outlined by Sam.

I wasn't able to reproduce the bug by changing any settings within Minecraft so I'm curious what kind of state/configuration changes are causing this to happen.

**Comment by ProfanedBane** [comment]
Alright I've found seemingly how to reproduce it.
The above mod setup is susceptible and I imagine the setup Johni has is too.

You need to go into Resource Packs and then reorder Vanilla to be above Fabric Mods, after which the glitch happens and cannot be reverted unless you manually edit Minecraft's options.txt to remove 'vanilla' from the resourcepack list.

Found this out from comparing all the configs from my bugged setup and my fresh setup, and the presence of
`resourcePacks:["replaymod_lang","Fabric Mods","vanilla"]`  was the only difference. Changing this line to ``resourcePacks:["replaymod_lang","Fabric Mods"]`` fixes the issue.

Unsure if this issue lies on ReplayMod's side or Enhanced Block Entities' so I'll see about reposting these findings on their github

**Comment by ProfanedBane** [comment]
To add onto this, it appears to be fixable ingame by pressing the down arrow on the default resource pack as much as it'll allow you then saving. Perhaps there's some weird priority issue with the Replaymod invisible resource pack.

**Comment by Johni0702** [comment]
Thanks for taking the time to look into this!

> You need to go into Resource Packs and then reorder Vanilla to be above Fabric Mods, after which the glitch happens

This happens for me even without ReplayMod installed. So please do report this on Enhanced Block Entities' issue tracker.
As far as I can tell, that is all there is to this. EBE simply breaks when the bottom-most pack is anything other than the vanilla "Default" pack. It doesn't actually matter what's there instead - Fabric Mods, Programmer Art or ReplayMod's internal pack - it'll break in any case.

And I'll change the way RM injects its internal pack in 2.6.1 so it's not simply an invisible pack which makes the sort buttons confusing to anyone not aware of what's going on.
