### ISSUE TITLE
Cannot find recovered recording in Replay Viewer

### ISSUE THREAD

**Issue by Hotprism** [ReplayMod/ReplayMod#538]
So I accidentally deleted a recording but I recovered it and it appears in my folder as its there but when I open replay viewer in game it doesn't appear. I am using the modpack called RLCraft which is in version 1.12.2

**Comment by Sebast04** [comment]
Would probably help if you provide more information

**Comment by Johni0702** [comment]
Closing due to lack of info, I'm guessing whatever you used to recover it just didn't produce a valid file.
