### ISSUE TITLE
Replay conflict with Optifine

### ISSUE THREAD

**Issue by IAFEnvoy** [ReplayMod/ReplayMod#542]
When I play Minecraft 1.16.5 with Fabric 0.11.6, it will crash because of these two mods. And I find that if I delete mixins in fabric.mod.json file in replay ,it can work but it cannot replay in the main menu.

**Comment by DaCubeKing** [comment]
You can use optifine alternatives (that are much better than optifine): https://gist.github.com/LambdAurora/1f6a4a99af374ce500f250c6b42e8754

or you can downgrade to optifabric 1.11.1 (not preferred)
