### ISSUE TITLE
rendering doesnt starts...

### ISSUE THREAD

**Issue by CamillaLee** [ReplayMod/ReplayMod#543]
every time when I try to start to render the game stop like this forever...
no matter how long I wait the number wouldnt change and when I click anywhere it says the game doesnt response... what should I do..?

![제목 없음](https://user-images.githubusercontent.com/79464981/125060241-1fc4f200-e0e7-11eb-9be3-4fcaeb9253b8.png)

[latest.log](https://github.com/ReplayMod/ReplayMod/files/6790490/latest.log)
[debug.log](https://github.com/ReplayMod/ReplayMod/files/6790495/debug.log)

**Comment by RaderRMT** [comment]
that's a forge log for 1.16.5
the replaymod only works on fabric, and we do not provide support for the 1.16.5 forge port.
