### ISSUE TITLE
Use gpu to render

### ISSUE THREAD

**Issue by Horange321** [ReplayMod/ReplayMod#553]
Using CPU to render is very slow. I hope I can choose to use GPU to render. Thanks

**Comment by RaderRMT** [comment]
read ffmpeg's documentation for command line arguments. this has nothing to do with the replaymod.

**Comment by Johni0702** [comment]
I don't even know what you think that means. It's already using the GPU to render the scene, because it's just using Minecraft to render the scene and Minecraft makes use of the GPU, otherwise it'd be orders of magnitudes slower...
For encoding, yeah, check ffmpeg's documentation.
