### ISSUE TITLE
Put scrollbar back in replay viewer?

### ISSUE THREAD

**Issue by L33Tech** [ReplayMod/ReplayMod#556]
Please put the scrollbar on the right back in the replay viewer, it was very helpful. Thanks!

**Comment by RaderRMT** [comment]
what scrollbar?

**Comment by L33Tech** [comment]
This scrollbar on the right here.
![Untitled drawing(2)](https://user-images.githubusercontent.com/36166244/127945962-b2d83e7a-82cc-4fce-9255-3d5636f9cf10.png)

In the newest update, it vanished.

**Comment by L33Tech** [comment]
Thank you for fixing!
