### ISSUE TITLE
The official website of the mod is not opened (https://www.replaymod.com)

### ISSUE THREAD

**Issue by SeagalKru** [ReplayMod/ReplayMod#56]
Hello!
What happened to the official mod site: https://www.replaymod.com?
Why is it unavailable?

**Comment by Johni0702** [comment]
Looks like its sql server died and monitoring didn't pick it up, thanks for notifying us. Should be back now.

**Comment by SeagalKru** [comment]
Again the site does not work!

**Comment by CrushedPixel** [comment]
Fixed, thanks for notifying. We really should add a cronjob to restart mysql...

**Comment by SeagalKru** [comment]
Hello!
What happened to the official mod site: https://www.replaymod.com?
Why is it unavailable?

**Comment by WhiteKnightSTU** [comment]
Most Likely due to CrushedPixel no longer running the program the site will not be paid for by him for hosting the mod, Have you checked all the version repositories on GitHub to see if the .jar versions are in here?
