### ISSUE TITLE
Compatibility issue with REI(RoughlyEnoughItems) requiring game to be relaunched

### ISSUE THREAD

**Issue by MHFDoge** [ReplayMod/ReplayMod#560]
There seems to be some compatibility issue with ReplayMod and RoughlyEnoughItems requiring that you relaunch the game after you use really any of REI's provided information menus(recipes, uses, etc.) making it so that when you close one of those REI menu's, you can no longer interact with the game window to any extent I could think of. This problem arose after I added ReplayMod to the game and is not present without that mod. Game information is as follows:
1. Game version: `1.17.1` running under Fabric loader build `0.11.6`
2. ReplayMod version: `2.6.0`
3. Other mods: Required library `architectury-2.1.18`, Required library `cloth-config-5.0.34`, Possibly required library `fabric-api-0.36.0`, `RoughlyEnoughItems-6.0.267-alpha`
No log included because there is nothing that shows up in the logfile when this occurs.

If you believe this is a problem with REI and not ReplayMod let me know and I will attempt to contact them about this.
Thank you.

**Comment by bling-yshs** [comment]
same

**Comment by Nite7800** [comment]
I've been having the same problem, glad it isn't just me tho.

**Comment by Johni0702** [comment]
Corresponding REI issue: https://github.com/shedaniel/RoughlyEnoughItems/issues/595
