### ISSUE TITLE
Labymod crashing with Replay mod

### ISSUE THREAD

**Issue by rlelchev** [ReplayMod/ReplayMod#567]
I got Labymod installed on forge and wanted to use ReplayMod with it and the game crashes at startup

**Comment by RaderRMT** [comment]
the replaymod is not compatible with labymod

**Comment by rlelchev** [comment]
What do you mean?

**Comment by Johni0702** [comment]
LabyMod is All Rights Reserved, meaning that they don't allow anyone else to do anything to their code, there's nothing I can do. Report any and all issues to them.
