### ISSUE TITLE
1.12 first person error when using optifine and carry on mod

### ISSUE THREAD

**Issue by MiceweekZ** [ReplayMod/ReplayMod#570]
![2021-08-19_13 45 56](https://user-images.githubusercontent.com/75073815/130015313-0de2e33e-0772-4c7e-8699-55b26c52f4ad.png)
![2021-08-19_13 46 10](https://user-images.githubusercontent.com/75073815/130015317-bb5cc28b-62f5-41ab-a645-7a75dfb11119.png)

**Comment by Johni0702** [comment]
Optifine is no longer supported due to the sheer amount of stupid issues it causes.
