### ISSUE TITLE
Stuck on "Loading terrain" when using a 1.8.9 replay in 1.17

### ISSUE THREAD

**Issue by DaCubeKing** [ReplayMod/ReplayMod#578]
Minecraft gets stuck on loading terrain when loading a replay made in 1.8.9 on 1.17
![image](https://user-images.githubusercontent.com/61074688/131440353-3d78fa06-872b-43af-9bcc-280deea1fc6a.png)

Log: [latest.log](https://github.com/ReplayMod/ReplayMod/files/7081126/latest.log)

Replay I'm Using: https://gofile.io/d/zH5Lw8

**Comment by drewc5131** [comment]
Can also confirm this is an issue for me as well.

**Comment by fullhamalti** [comment]
Can confirm ReplayMod 2.6.1 on Minecraft 1.16.5

Work with ReplayMod 2.5.2 on minecraft 1.8.9+

**Comment by Johni0702** [comment]
Cannot reproduce.
The original replay can no longer be downloaded because it has expired and two replays I had lying around (one SP, one Hypixel) open fine on 1.16.4-2.6.1.

**Comment by Johni0702** [comment]
Never mind. It works fine on Java 8, but breaks when I switch to Java 17.
