### ISSUE TITLE
No matter which version you use, only the black screen will be output.

### ISSUE THREAD

**Issue by KonohanaSakuya2680** [ReplayMod/ReplayMod#584]
No matter what I do, all I get is a black-painted video. Therefore, the encoding is very fast.

Minecraft:1.12.2
replaymod:2.6.1 or 2.5.2 or 2.3.1 or 2.1.4 or 2.2.0-b7
Optifine:1.12.2_HD_U_G5

I don't want to remove Optifine. Because I will be trouble.

**Comment by RaderRMT** [comment]
optifine is known to cause a lot of issues. try without it nonetheless

**Comment by KonohanaSakuya2680** [comment]
So how do you apply a shader? I was planning to use it to make a PV, so I'm in trouble if I can't use it.

**Comment by KonohanaSakuya2680** [comment]
> optifine is known to cause a lot of issues. try without it nonetheless

Surprisingly, even if I pulled out Optifine, it was still black.

**Comment by RaderRMT** [comment]
what launcher are you using?

**Comment by KonohanaSakuya2680** [comment]
default Minecraft launcher

**Comment by KonohanaSakuya2680** [comment]
Also, when I output the blend, nothing was displayed.

**Comment by KonohanaSakuya2680** [comment]
It became possible to render by shooting with a single, but when the camera starts moving, the screen becomes soil for a moment and the video becomes white.

**Comment by KonohanaSakuya2680** [comment]
[crash-2021-09-17_16.48.57-client.txt](https://github.com/ReplayMod/ReplayMod/files/7183715/crash-2021-09-17_16.48.57-client.txt)
I tried to output a Blend file and it crashed.

**Comment by KonohanaSakuya2680** [comment]
Finally, when I set all camera settings to default and rendered in single player, I was able to render successfully with Optifine installed.
