### ISSUE TITLE
Can't change fly speed while the replay is paused

### ISSUE THREAD

**Issue by Fadenfire** [ReplayMod/ReplayMod#590]
Trying to change the fly speed using the scroll wheel in the replay viewer won't work if the replay is paused. The fly speed can be changed normally when the replay isn't paused and the modified speed with remain if the replay is paused, but the speed cannot be changed from the current value while the replay is paused.

**Comment by Johni0702** [comment]
Which ReplayMod and Minecraft version is this?

**Comment by Fadenfire** [comment]
Replay mod 2.6.1 on minecraft 1.8.9. It also occurs in 1.12.2, but it does not occur in 1.17.1. My operating system is macOS 11.5.1.
