### ISSUE TITLE
How to join 2 replays together

### ISSUE THREAD

**Issue by ErrorBot1122** [ReplayMod/ReplayMod#592]
How do you do this???

I looked in the [forms](https://www.replaymod.com/forum/thread/667) and found lots of answers, but they don't really explicitly tell me how to do it. I also did a little searching and found [Replay Studio](https://github.com/ReplayMod/ReplayStudio) but it dose not have a [wiki](https://github.com/ReplayMod/ReplayStudio/issues/5#issuecomment-398792723). So what do i do???

P.S. I would also like to learn more about the [Replay Studio](https://github.com/ReplayMod/ReplayStudio) API becuse i'm thinking about making a mod for mincraft.

P.P.S. Also please send me some good tutoriels of how to use java to make mods (I'm manily a [javascript dev](https://github.com/ErrorBot1122))

**Comment by RaderRMT** [comment]
Duplicate of #554 again

**Comment by ErrorBot1122** [comment]
but is there a way to use it with [Replay Studio](https://github.com/ReplayMod/ReplayStudio)

**Comment by ErrorBot1122** [comment]
I found out how to do it, you can't :-1:, sadly you have to use you editing software to stich the replays together, but if  you still want a smooth transition do this:

_**Credit to Kepler-17c#1190 for answering the question!!!**_
> When you want to render a video, you need to set up a camera path. That path can be saved to the keyframe repository (which you can open with the hotkey X or via the menu located in the bottom left corner). When you have it saved, you can click "copy" (copies it to the clipboard as text), then open your other replay, go to the keyframe repository and click "paste" (you can also use STRG+C and STRG+V).
> From the keyframe repository you can then load the path, remove everything but the last keyframes, shift the end of the path to the start of your video timeline and continue the path from there.
> That way, when you render both clips, you have a section, where both show about the same thing. Overlay it and transition in your video editor.

or the TL;DR:

> You can transfer the camera path via the keyframe repository (hotkey X)
