### ISSUE TITLE
How to use Replay Studio in replay mod. 

### ISSUE THREAD

**Issue by ErrorBot1122** [ReplayMod/ReplayMod#593]
I made an [issue](https://github.com/ReplayMod/ReplayStudio/issues/15#issuecomment-931944658) about a question I had in the [Replay Studio Repo](https://github.com/ReplayMod/ReplayStudio) and the responder ([Johni0702](https://github.com/Johni0702)) said:

> You don't. If you can't figure out how to use something without a wiki, then you probably shouldn't be using it.
> > is there an app or mod to easily use this "API"??

> **_As I said in the other issue, this library is used primarily by the ReplayMod, and the ReplayMod exposes all maintained parts of this library somewhere in its user interface._**

So does any of you know where the interface for replay studio functions could be???

P.S: Thanks to [Johni0702](https://github.com/Johni0702) for "Answering" my original [question](https://github.com/ReplayMod/ReplayStudio/issues/15)

P.P.S: Also what is that why do I have to make a weird space, just to make a double qoute

**Comment by RaderRMT** [comment]
> So does any of you know where the interface for replay studio functions could be???

you can try and find it by yourself. shouldn't be that hard as you're also a developer

**Comment by ErrorBot1122** [comment]
@RaderRMT I'm not really a dev, I'm a _**Javascript**_ Dev

**Comment by Kepler-17c** [comment]
You access it via the "edit" button from the replay viewer list.

**Comment by Kepler-17c** [comment]
Also, please use the Discord for support - this is the issue and feature tracker.

**Comment by ErrorBot1122** [comment]
I did that a while back and I just showed a button to clip the replays

**Comment by ErrorBot1122** [comment]
oh okay

**Comment by Kepler-17c** [comment]
> I did that a while back and I just showed a button to clip the replays

Yes, that's the GUI for the replay studio cutting feature.

**Comment by RaderRMT** [comment]
> 
> 
> @RaderRMT I'm not really a dev, I'm a _**Javascript**_ Dev

I'm sorry for you

**Comment by ErrorBot1122** [comment]
OOOOOOHHHHHHHHHHHHHH!!!!! Thx @Kepler-17c, again
