### ISSUE TITLE
Finishing a new replay and saving it deletes `.mcpr.tmp` folders of other replays

### ISSUE THREAD

**Issue by Abwasserrohr** [ReplayMod/ReplayMod#598]
Hello there. 👋

I had two ReplayMod instances open, one recording and with one creating new timelines using the Keyframe Repository. But after saving the created (new) recording, the `.mcpr.tmp` folder of the replay I'm currently editing suddenly disappeared with all files stored there, like the `timelines.json`.

I know it's probably not suggested to use two instances at once, but it's still unexpected that the saving process deletes other tmp folders I guess.

ReplayMod v2.6.1
Minecraft 1.17.1

**Comment by RaderRMT** [comment]
running 2 instances using the same `.minecraft` folder can already cause unexpected behaviours and is not recommended by Mojang.
