### ISSUE TITLE
error saving replay: decoding

### ISSUE THREAD

**Issue by Nikita11790** [ReplayMod/ReplayMod#60]
Hello! I love replay mod and the new things that you have added
(stoping starting and pausing)
but when I leave the server to edit my replay it doesn't save and I get a error
https://paste.gg/p/anonymous/c90b4a4d1b8344acb8078325f28d5107
Here is my log file!
https://paste.gg/p/anonymous/e2ddeaf56a9240ecaafc3b67dd8b1d10
Sorry if I missed any info! 
Hope this is not caused by user error. :)

**Comment by Johni0702** [comment]
Is that a vanilla recording (i.e. no third-party content mods)?

**Comment by Johni0702** [comment]
This should be fixed as of 2.2.0-b5.
