### ISSUE TITLE
Problems with the website

### ISSUE THREAD

**Issue by GabubuAvailable** [ReplayMod/ReplayMod#603]
Hello. I went on your page to download the ReplayMod Mod for Minecraft but... ![Screenshot_20211107-071753_Samsung Internet.jpg](https://user-images.githubusercontent.com/88589756/140633368-015cd89b-06c0-4cd2-89c8-fac56173afc7.jpg)

Do you know guys why it happens?

**Comment by Johni0702** [comment]
The SQL server sometimes dies and fails to recover on its own.
Should be back now.
