### ISSUE TITLE
game hard crash when trying to open a replay

### ISSUE THREAD

**Issue by Undertale46** [ReplayMod/ReplayMod#605]
whenever I'm trying to open up a replay file, it always gives me this message
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_746.method_31548()" because "this.field_3712.field_1724" is null
when looking at the crash report i can't understand what is wrong (because I'm not one to understand this stuff) it has nothing to do with corrupted files, because none of my mods/resource packs are corrupted

Solution:
if you're using baritone get rid of it as it is conflicting with the replay feature

**Comment by Kepler-17c** [comment]
Do use Baritone?

**Comment by Kepler-17c** [comment]
If you do, please try without it.

And consider using the ReplayMod Discord server (<https://discord.gg/5GR7RSb>) - it makes interaction a lot easier.

**Comment by Undertale46** [comment]
> If you do, please try without it.
> 
> And consider using the ReplayMod Discord server for support requests (https://discord.gg/5GR7RSb) - it makes interaction a lot easier.

okay, i'll try it without baritone

**Comment by Undertale46** [comment]
> If you do, please try without it.
> 
> And consider using the ReplayMod Discord server for support requests (https://discord.gg/5GR7RSb) - it makes interaction a lot easier.

it was with baritone
