### ISSUE TITLE
Can't render with Sodium

### ISSUE THREAD

**Issue by TheChocolateOre** [ReplayMod/ReplayMod#611]
The render button is gray/locked.
Everything is in their latest version.
On the site it states: 

> Compatible Sodium version for Minecraft 1.17.1 (works with Iris 1.1.2)

When I remove the iris-and-sodium mod it renders fine.

**Comment by Kepler-17c** [comment]
A fix has been proposed to Sodium by Johni, but they have it merge it yet.
In the meantime, find an adjusted version on the ReplayMod download page.

**Comment by TheChocolateOre** [comment]
So basically, until the fix is merged, I can't use Sodium with ReplayMod?

**Comment by Kepler-17c** [comment]
Read the second line, please.

**Comment by Kepler-17c** [comment]
Johni made an adjusted Sodium version, that includes the fix, based on the Sodium for Iris. So you can use Sodium & Iris with ReplayMod.
I have done so successfully multiple times. It works flawlessly.

**Comment by TheChocolateOre** [comment]
Can you please point me to that adjusted version?

**Comment by Kepler-17c** [comment]
Sorry I did just see your reply right now. The download is available at https://www.replaymod.com/download/

I recommend you use the Discord server at https://discord.gg/5GR7RSb for future support.

**Comment by Bros112** [comment]
Very helpful thanks

**Comment by Astro950** [comment]
How would I solve this if I am using the new replay mod option in lunar client 1.20.1?

**Comment by Kepler-17c** [comment]
@Astro950 The issue this ticked was made for was resolved a while ago as Sodium merged the proposed changes and is now compatible.
Did Lunar make it possible to load 3rd party Fabric mods or did they make their own version of ReplayMod like Badlion?
If you can load any Fabric mod with it now, just download the normal Sodium. If they made their own version, I have no idea what they messed up.
