### ISSUE TITLE
1.18

### ISSUE THREAD

**Issue by cootshk** [ReplayMod/ReplayMod#616]
When is a 1.18 release (preferably compatible with sodium) going to come out?

**Comment by Johni0702** [comment]
There is no fixed release date for a 1.18 RM version.
I'm currently aiming for shortly after when 1.18.1 is projected to release (that's somewhere around next Thursday/Friday), so there doesn't have to immediately be another update. But if 1.18.1 doesn't make the projected release date, then RM 1.18 will probably release around that time anyway.
