### ISSUE TITLE
Issues ReplayMod supported for version 1.18.1

### ISSUE THREAD

**Issue by abelblue3** [ReplayMod/ReplayMod#624]
I encounter issues with the file for the ReplayMod is causing the MC launcher to crash and not be able to execute the application (as I investigated that no other mods are affecting the launcher to stop working).

**Comment by Kepler-17c** [comment]
Please use the official Discord server at https://discord.gg/5GR7RSb for support requests. That makes it easier for everyone to help you.

I'll take a guess on your issue: Do you use Optifine?  
If so: It breaks ReplayMod (again). Please use Iris, Sodium and other replacement mods instead.  
In the support channel, you find a pin with instructions.
