### ISSUE TITLE
Crach when I open a replay

### ISSUE THREAD

**Issue by gagaos** [ReplayMod/ReplayMod#628]
Crach when I open a replay 

The replay files are attached (in the URL). If you need anything else ask me.

https://www.mediafire.com/file/fbox4q6j0tmob58/replay_recordings.zip/file

**Comment by gagaos** [comment]
My log https://paste.ee/p/d4Gec

**Comment by RaderRMT** [comment]
Remove Baritone

**Comment by gagaos** [comment]
Thank you. But I don't see what's wrong with Baritone.

**Comment by Johni0702** [comment]
https://github.com/cabaletta/baritone/issues/2619
