### ISSUE TITLE
Cannot open replay file 1.18.1 2.6.3

### ISSUE THREAD

**Issue by SomeoneWasTaken** [ReplayMod/ReplayMod#637]
When trying to open a replay file, the game crashes after it tries to load in.
first i thought it was because the replay was 2 Hours whitch is too long but i splitted it into many 10 min. Videos, still didnt work.

Maybe it got interrupted with some of theese folowering mods:
>appleskin-fabric-mc1.18-2.2.0
>architectury-3.3.5
>bobby-3.1.0
>Capes-1.2.2+1.18
>cloth-config-6.1.48-fabric
>fabric-language-kotlin-1.7.1+kotlin.1.6.10
>iris-shaders 1.18.1-1.1.3 (built-in Sodium mod)
>lambdynamiclights-2.1.0+1.17
>lithium-fabric- 1.18.1-0.7.6
>multiconnect-1.5.7
>phosphor-fabric-mc1.18.x-0.8.1 (performance optimation for lightning)
>RoughlyEnoughItems-7.1.357
>sodium-extra-mc1.18-0.3.7
>wthit-fabric-4.4.0
>Xaeros_Minimap_21.23.0_Fabric_1.18
>XaerosWorldMap_1.19.0_Fabric_1.18

**Comment by Johni0702** [comment]
Since you didn't provide the actual crash report, I can only guess that it's because ReplayMod is not currently compatible with multiconnect: #558
