### ISSUE TITLE
Hand missing in 1.18.x

### ISSUE THREAD

**Issue by Kepler-17c** [ReplayMod/ReplayMod#638]
The hand misses in 1.18.1 completely.

In 1.18 it's missing as soon as shaders are enabled (works with shaders disabled in Iris).

Tested versions:  
- MC 1.18 / 1.18.1  
- RM 2.6.2 / 2.6.3
- Shaders BSL & SEUS

**Comment by arlodu** [comment]
Found the hand to be present when spectating player in 1.18.1 (Iris/Sodium) but missing when shaders are enabled.
Not present at all in 1.18.1 (optifine/optifabric)
Not present at all in 1.17.1 (optifine/optifabric)

Tested versions: 

- MC 1.17.1 / 1.18.1
- RM 2.6.1 / 2.6.3
- Sodium 0.4.0-alpha5 / 0.4.0-alpha5.rev.76d0e6e
- Shaders BSL, Complementary, Sildurs
- Test on two separate PCs with different setups

**Comment by Johni0702** [comment]
> The hand misses in 1.18.1 completely.

Could you double check this?
I can reproduce the hand missing with Iris shaders enabled but not under any other circumstance (not considering Optifine here because I won't waste my time on it).

**Comment by Kepler-17c** [comment]
Seems I got something mixed up - sorry.

I just re-tested:
- only ReplayMod: works
- RM + Sodium: works
- RM + S + Iris 1.1.5 no shader: works
- RM + S + I 1.1.5 with shader: missing
- with Iris 1.2.0 same as 1.1.5
