### ISSUE TITLE
Crash when saving reply file

### ISSUE THREAD

**Issue by LogicalGeekBoy** [ReplayMod/ReplayMod#64]
Hey,

I've been using ReplyMod for a while and love it! Today I experienced a crash and thought I'd send over the details. The stacktrace is included in the details section below. I started the game with replaymod recording as a usually do but as I played I realised I won't need the recording and so I clicked the Stop Recording button in the in game menu. Everything was fine but when I later quit the game, the saving replay file message appeared and after a short time this crash message came up. 

This is for 1.14.3 on Fabric and the only other mod I have installed is Optifine.

I hope this is useful <3

Logic

<details>
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 13/07/19 10:07
Description: Saving replay file

java.io.IOException: decoding
	at com.replaymod.replaystudio.io.ReplayInputStream.fillBuffer(ReplayInputStream.java:233)
	at com.replaymod.replaystudio.io.ReplayInputStream.readPacket(ReplayInputStream.java:184)
	at com.replaymod.editor.gui.MarkerProcessor.apply(MarkerProcessor.java:146)
	at com.replaymod.recording.packet.PacketListener.lambda$channelInactive$8(PacketListener.java:220)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Value 46 has no mapping for key class com.replaymod.lib.com.github.steveice10.mc.protocol.data.game.entity.EntityStatus.
	at com.replaymod.lib.com.github.steveice10.mc.protocol.data.MagicValues.key(MagicValues.java:1094)
	at com.replaymod.lib.com.github.steveice10.mc.protocol.packet.ingame.server.entity.ServerEntityStatusPacket.read(ServerEntityStatusPacket.java:35)
	at com.replaymod.lib.com.github.steveice10.packetlib.tcp.TcpPacketCodec.decode(TcpPacketCodec.java:41)
	at com.replaymod.replaystudio.studio.protocol.StudioCodec.decode(StudioCodec.java:42)
	at com.replaymod.replaystudio.io.ReplayInputStream.fillBuffer(ReplayInputStream.java:229)
	... 4 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.14.3
	Operating System: Mac OS X (x86_64) version 10.12.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1842168696 bytes (1756 MB) / 3489660928 bytes (3328 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 7 total; -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric: Fabric API 0.3.0+build.187
		fabric-api-base: fabric-api-base 0.1.0+59147463
		fabric-commands-v0: fabric-commands-v0 0.1.1+25fd0c52
		fabric-containers-v0: fabric-containers-v0 0.1.2+25fd0c52
		fabric-content-registries-v0: fabric-content-registries-v0 0.1.1+05f11b75
		fabric-crash-report-info-v1: fabric-crash-report-info-v1 0.1.0+59147463
		fabric-events-interaction-v0: fabric-events-interaction-v0 0.1.0+59147463
		fabric-events-lifecycle-v0: fabric-events-lifecycle-v0 0.1.0+59147463
		fabric-item-groups-v0: fabric-item-groups-v0 0.1.0+f0d56800
		fabric-keybindings-v0: fabric-keybindings-v0 0.1.1+7dfef87c
		fabric-loot-tables-v1: fabric-loot-tables-v1 0.1.0+43028fa6
		fabric-mining-levels-v0: fabric-mining-levels-v0 0.1.0+bdffbb2c
		fabric-models-v0: fabric-models-v0 0.1.0+59147463
		fabric-networking-blockentity-v0: fabric-networking-blockentity-v0 0.1.1+25fd0c52
		fabric-networking-v0: fabric-networking-v0 0.1.2+200eb5c2
		fabric-object-builders-v0: fabric-object-builders-v0 0.1.1+39ff57de
		fabric-registry-sync-v0: fabric-registry-sync-v0 0.2.2+f0d56800
		fabric-renderer-api-v1: fabric-renderer-api-v1 0.1.0+02a46d5b
		fabric-renderer-indigo: fabric-renderer-indigo 0.1.7+029ec62e
		fabric-rendering-data-attachment-v1: fabric-rendering-data-attachment-v1 0.1.0+02a46d5b
		fabric-rendering-fluids-v1: fabric-rendering-fluids-v1 0.1.0+dc4c57c2
		fabric-rendering-v0: fabric-rendering-v0 0.1.1+6dad974e
		fabric-resource-loader-v0: fabric-resource-loader-v0 0.1.1+59147463
		fabric-tag-extensions-v0: fabric-tag-extensions-v0 0.1.1+c189dc5c
		fabric-textures-v0: fabric-textures-v0 0.1.4+792c1c35
		fabricloader: Fabric Loader 0.4.8+build.155
		mm: Manningham Mills 1.6
		net_fabricmc_stitch: stitch 0.2.1.61
		optifabric: Optifabric 0.3.1
		org_slf4j_slf4j-api: slf4j-api 1.7.26
		org_slf4j_slf4j-simple: slf4j-simple 1.7.26
		org_zeroturnaround_zt-zip: zt-zip 1.13
		replaymod: Replay Mod 1.14.3-2.2.0-b4
</details>

**Comment by Johni0702** [comment]
You should update your RM, this has been fixed in -b5 iirc.

**Comment by LogicalGeekBoy** [comment]
oh of course, I updated that for my other profile. Sorry, I'll do that, thanks for the fast reply :+1:
