### ISSUE TITLE
Crash when opening save file dialog

### ISSUE THREAD

**Issue by ayangd** [ReplayMod/ReplayMod#65]
All things are ready to be rendered, opened the rendering dialog. When pressing the save file name (Which I assume opening the save file dialog), it crashes.
Crash log: https://pastebin.com/3mvsmSnW

**Comment by Johni0702** [comment]
This should be fixed as of 2.2.0-b1.
From the changelog:
```
- Fix crash when selecting video output location on Windows
```

**Comment by ayangd** [comment]
I think this mod needs some kind of auto update. People downloaded this mod from the other day, then you fix it, then they don't know if there is an update. Then, people will just send crashes with previous versions.

Consider making a template of a bug/crash issue and tell people to include their version.

**Comment by Johni0702** [comment]
>I think this mod needs some kind of auto update. People downloaded this mod from the other day, then you fix it, then they don't know if there is an update. Then, people will just send crashes with previous versions.

I'm strictly opposed to including any kind of auto-update in any mod (unless it's an auto-updater mod). This kind of stuff should be left to the launcher or said dedicated mod. Unfortunately I'm not aware of and standardized solution which would allow us to just supply one metadata file with available versions and where to get them and which will work across launchers.

There even is an update notifier built into forge (the emerald on the Mods button) but it's sub-optimal in multiple ways:
- People don't know that it exists
- If you're on a stable release, there isn't any way to get notified of pre-releases
- With lots of mods, it's basically always active and (even if they know what it means) people start ignoring it

>Consider making a template of a bug/crash issue and tell people to include their version.

The amount of bugs reported via github is too low for me to bother with that. And on the forum I've got reply templates (and no same way to add issue templates anyway).

**Comment by ayangd** [comment]
Imagine people made keyframes for straight 3 hours, and the game crashes...

**Comment by Johni0702** [comment]
Ah, yes, the irony, I added auto-saving in 2.2.0-b1.
Then again, why haven't they been saving manually for the whole three hours? Oh, right, no one reads the docs, so they didn't know that one can save camera paths.

So, how should we try to get people to update if forge's builtin notification doesn't do it? Is there some widely used auto-updater mod which we could integrate with?

**Comment by ayangd** [comment]
I saw some mod notify the user with chat.
