### ISSUE TITLE
Replaymod/bobby bug 1.17.1

### ISSUE THREAD

**Issue by TiboOpGithub** [ReplayMod/ReplayMod#651]
You closed my issue but I still haven't been able to fix the problem. I'm using the latest version of bobby and replaymod for 1.17.1 and it still doesn't work. 
My mods:
![image](https://user-images.githubusercontent.com/95926002/147871920-b9210efc-21b9-40bf-b111-06d4ebd288ca.png)
video: https://youtu.be/hQfY_fd3MGE

**Comment by Johni0702** [comment]
Ah, you didn't specify 1.17.1 in the last issue, so I assumed 1.18 where the issue was already fixed. I've just released Bobby 2.1.0 which backports all the applicable Bobby 3.x (MC 1.18) changes to MC 1.17.

**Comment by TiboOpGithub** [comment]
Thank you very much!

**Comment by DefomCode** [comment]
I have the same problem on 1.20.1 with the latest version of bobby and replay.
