### ISSUE TITLE
Softlock

### ISSUE THREAD

**Issue by Richienb** [ReplayMod/ReplayMod#656]
1. Open a replay recording
2. Press <kbd>Esc</kbd> if cursor is visible
2. Press <kbd>F1</kbd>
3. Press <kbd>T</kbd>
4. Press <kbd>F1</kbd>
4. Press <kbd>Esc</kbd>
5. Press <kbd>F1</kbd>

This combination will cause <kbd>F1</kbd> to cease showing the UI until these keys are pressed:

1. <kbd>F1</kbd> if player nametags are not visible
2. <kbd>T</kbd>
3. <kbd>F1</kbd>

**Comment by RaderRMT** [comment]
try pressing escape then F1

**Comment by Richienb** [comment]
@RaderRMT I updated the reproduction to more accurately reproduce the bug I was after. In the reproduced situation, your solution does not resolve the issue.

**Comment by RaderRMT** [comment]
Doesn't sound like a bug though. There are 2 "F1" in the Replay Viewer, one for the game and one for the ReplayMod UI

**Comment by Richienb** [comment]
> There are 2 "F1" in the Replay Viewer

How do I switch between them?

**Comment by RaderRMT** [comment]
open/close the chat
