### ISSUE TITLE
Item in player hand when it shouldn't be there bug

### ISSUE THREAD

**Issue by Nighthawk27** [ReplayMod/ReplayMod#658]
Hello! I'd like to report a bug that happened to me recently that I've never seen before! In the replay file, when my player threw and item to another player, I dropped the item but the item did not leave my hand in the replay, and stayed there until I switched inventory slots again (which wasn't for a while). So it showed me having an item in my hand that, in game, I did not have anymore and was an empty hand slot. This happened every single time at the same spot without fail no matter how much I reloaded it so I think it's something to do with the recording itself. That is all, thank you!

**Comment by Johni0702** [comment]
Which version (Minecraft and ReplayMod) did you observe this on?
Does it happen every time you drop an item or just at that specific time in this one replay? If it's the latter, please attach the replay.
