### ISSUE TITLE
Game crashes when typing in the renaming replay section in the top-right "saving replay file..." window after leaving a world.

### ISSUE THREAD

**Issue by WalleyeGuy8371** [ReplayMod/ReplayMod#659]
Video of the crash occurring.
https://user-images.githubusercontent.com/97816037/149644947-8a4e6c74-fec2-45d0-b4bf-e99754c6ff5a.mp4

**Comment by Kepler-17c** [comment]
Please use the official Discord at https://discord.gg/5GR7RSb for support.

What other mods do you use?

**Comment by Johni0702** [comment]
Duplicate of #635
