### ISSUE TITLE
My game wont load the mod whether it be the technic launcher or normal Minecraft launcher.

### ISSUE THREAD

**Issue by Bantoo1231** [ReplayMod/ReplayMod#66]
[2019-07-29-4.log.gz](https://github.com/ReplayMod/ReplayMod/files/3441634/2019-07-29-4.log.gz)

**Comment by Johni0702** [comment]
The RM bundles an older version of the Mixin library than another mod requires. Try renaming its file to start with z, so it loads after the other mod.

**Comment by Bantoo1231** [comment]
Err, what does that mean? Which folder do I need to rename?

**Comment by Johni0702** [comment]
The ReplayMod jar file which you downloaded from replaymod.com starts with `r` whereas the one from the other mod starts with `s` (iirc) which puts it after the RM in the load order causing the older mixin bundled with the RM to be loaded. By renaming the RM jar to start with `z`, the more recent mixin bundled with the other mod should be loaded instead.

**Comment by Bantoo1231** [comment]
Thank you, that helped. All I had to do was stick a 'z' at the start xD

**Comment by Chris221** [comment]
[latest.log](https://github.com/ReplayMod/ReplayMod/files/3499766/latest.log)
I'm having some strange issue where it wont load the mod at all. I currently have it with a z at the start. I've tried it with nothing but the mod and forge, still nothing. Any thoughts?

**Comment by Johni0702** [comment]
@Chris221 Same thing but the other way around. LiteLoader ships a Mixin version which is older than what the RM requires. Since liteloader isn't a normal forge mod, you can't just rename its jar file to change the load order, instead you'll have to ask on their issue tracker.
