### ISSUE TITLE
crash on trying to load replay (1.18.1, latest download)

### ISSUE THREAD

**Issue by PseudonymPatel** [ReplayMod/ReplayMod#662]
Attached are two crash logs. Tried to take quick test replay of me on the nether roof building and breaking a couple blocks (multiplayer sever). Stopped recording while still connected to server, from pause menu. 1st log (earlier one) is from trying to open it right after disconnecting. 2nd crash (later in time) is from after I reopened minecraft after the first crash.
Please note that I have a mods installed that could be incompatible, like carpet mod, worldedit, wurst client, sodium/lithium/phosphor. Let me know if I can provide any more information/triage help.

[crash-2022-01-18_13.20.43-client.txt](https://github.com/ReplayMod/ReplayMod/files/7891509/crash-2022-01-18_13.20.43-client.txt)
[crash-2022-01-18_13.22.48-client.txt](https://github.com/ReplayMod/ReplayMod/files/7891510/crash-2022-01-18_13.22.48-client.txt)

**Comment by Kepler-17c** [comment]
Please try without Wurst and reply on the official support Discord server at <https://discord.gg/5GR7RSb> if that doesn't work.

**Comment by Johni0702** [comment]
https://github.com/cabaletta/baritone/issues/2619
