### ISSUE TITLE
An option for not unloading the chunks around the camera (when rendering)

### ISSUE THREAD

**Issue by commandblock2** [ReplayMod/ReplayMod#664]
It would be pretty cool to have an option for not unloading the chunks around the camera when the player goes far away from the camera or enters another dimension.
And also reloads the chunks when the player re-enter the view distance of the camera.

Not sure if it would be useful to many people, but for cases like:
- rendering a video of building a 2 dimensional farm
- when you only want the process of building something but accidental death or forgetting to take materials makes you leave your desired recording place.
![untitled](https://user-images.githubusercontent.com/21105626/150327978-6efdd64f-1687-4145-83f7-a3de8b439098.gif)

It might be implemented in the way of injecting the function for handling Chunk Data packet, but afaik it seemed to be a bit of different when it comes to different versions, at least on 1.8.9/1.16.5 it is different. Just asking, what would be the proper way of doing this if it has to use different logic, is there an example or something I can reference? Thanks in advance.

**Comment by Johni0702** [comment]
This is just how Minecraft works and imo it's out of scope for RM to mess with. It's also by no means easy to fix on modern versions and incredibly complicated once you bring respawning or the nether into the picture.

For 1.16.5+ there's [Bobby](https://modrinth.com/mod/bobby) which can keep chunks loaded as long as you stay in the same dimension and (with RM only in 1.17+) also re-load them from its cache when you respawn (either after death, or after returning from the nether).
