### ISSUE TITLE
CurseForge does not recognize Sodium Compatible Replay Mod

### ISSUE THREAD

**Issue by WigglePig** [ReplayMod/ReplayMod#671]
**Version - 1.18.1**
**Fabric Version - 0.12.12**
**Replay Mod Version - Compatible Sodium 0.4.0-alpha6 for Minecraft 1.18.1 (compatible with Iris 1.1.5+)**
**Sodium Version - 0.4.0-alpha6**

When I try to install Replay Mod for 1.18.1 and drop it into my mods folder, CurseForge does not even recognize it.  I load up the game, and the Replay Viewer button is missing.  I am using Sodium and a few other mods, and I made sure to install the sodium-compatible version.  I even tried only installing Sodium and Replay Mod, and that didn't work.  My best guess to why this is happening is that both Sodium and Replay Mod (sodium compatible version) start with the same naming convention: `sodium-fabric-mc1.18.1-0.4.0-alpha6+...`

Any solutions?

**Comment by Kepler-17c** [comment]
Please use the official support Discord at <https://discord.gg/5GR7RSb> next time.

What you have is only the ReplayMod compatible Sodium. It has a small fix, that is pending for the official version.

**Comment by DaCubeKing** [comment]
You need to also download replay mod. The sodium download is just sodium. It does not include replay mod.

**Comment by WigglePig** [comment]
Oh, that makes so much more sense!  Thank you.
