### ISSUE TITLE
I can't explain this.

### ISSUE THREAD

**Issue by RewardedIvan** [ReplayMod/ReplayMod#673]
I just pressed play camera path and this happened (ignore the pause menu that's just obs being weird).
After this it just crashed.
I don't have logs cause of `MultiMC stopped watching the game log because the log length surpassed 100000 lines....` and the last log was a hour ago..
At least replay mod recovers it, but still it should not happen.

https://user-images.githubusercontent.com/67065165/151666047-6d751d26-ad5f-4e19-8878-27b530fae755.mp4

**Comment by Johni0702** [comment]
Could you please attach that exact replay file so I can try to reproduce it? (you might have to change the extension to zip for github to allow it)

**Comment by RewardedIvan** [comment]
It doesn't happen anymore, but as you can see for some reason the play button isn't synced with the play camera path button. Maybe someone else will find a way to recreate it somehow.
