### ISSUE TITLE
Crash while rendering

### ISSUE THREAD

**Issue by BeeFox-sys** [ReplayMod/ReplayMod#677]
Crash Details: https://bytebin.lucko.me/Dk6eQFxTBI

i have no idea why this happens, i have fiddled with settings to try and get it to work but it never does. it always seems to crash at frame four, i can send a replay file also if that will help

**Comment by Kepler-17c** [comment]
The path you save to is completely broken - reset it, then try rendering again.

Please use the official support Discord (https://discord.gg/5GR7RSb) for future questions.

**Comment by BeeFox-sys** [comment]
ah yep that will do it! thank you!
