### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Pectacular** [ReplayMod/ReplayMod#683]
[latest.log](https://github.com/ReplayMod/ReplayMod/files/8066604/latest.log)
When I try to launch Minecraft with Replay Mod and compatible Sodium version, it crashes.

**Comment by Kepler-17c** [comment]
Duplicate of https://github.com/ReplayMod/ReplayMod/issues/682

Manually update Amecs from <https://www.curseforge.com/minecraft/mc-mods/amecs/files>

If that doesn't work, use Fabric 1.12.x

For future questions, please use the official support Discord https://discord.gg/5GR7RSb

**Comment by Pectacular** [comment]
I don't use amecs

**Comment by Kepler-17c** [comment]
It's added by MouseWheelie

**Comment by Pectacular** [comment]
Thanks I removed MouseWheelie and Minecraft launches fine
