### ISSUE TITLE
Player view interpolation

### ISSUE THREAD

**Issue by psycho-history** [ReplayMod/ReplayMod#690]
When rendering with a view from player (b in editor), the camera exactly follows the view from the player.
However, when playing (even with cinematic camera on), the view is not/never completely smooth, like while pressing/releasing a movement key while holding another movement key, it shows up in the view, off course. Also (even with the cinematic camera motion on) when moving around with the mouse, sometimes the game play holds for a moment because of stuff getting calculated or so (outside the previous view). Then after the freeze it suddenly rotates quickly following the mouse actions during the freeze. 
The interpolation even could have a 'strength', for more or less interpolation of the whole of the camera position/angle.

However if there would be an interpolation on this camera view you get a (much) smoother rendering of the view.
Then, if so, it would be nice to also have the roll axis in the game play (or maybe there is another mod for it) just like in the recording session, and then this also is recorded (maybe it already is, i don't know for now).

Interpolation in the timing could also benefit recordings. Like for now if timing is adjusted and going in/out from low/high speed timing, depending on the markers in the editor, the transition in speed is like abrupt. Just like the player view interpolation a 'strength' could be there to. So things speed up and/or slow down less or more smooth.

I see a lot of issues in this repo, and like to say the following to everybody: Install Ubuntu 20.04 (boot version, not the Windows version). The whole system while recording during game play, and rendering DOES NOT CRASH!!!
Most crashes are because of the Windows/java and Windows/FFmpeg combination that just doesn't work that good.
Once you got the whole thing going under Ubuntu Linux you will not go back to the Windows platform. Remember when Windows constantly 'updates' lots of things, making changes in the Windows OS, which makes 3rd party software crippled.
Unintentionally or intentionally, you can never say. But its (speculating) the Micro$oft way of sabotaging third party software they don't like or having capabilities they don't like, and/or making software suddenly fail that worked fine before the update. 

Download a good FFmpeg static build from: https://johnvansickle.com/ffmpeg/ and add this to your ffmpeg options:

-segment_time 00:01:00 -f segment -reset_timestamps 1 

and set the filename in the settings above in the rendering wizard to: output%03d.mp4
Then you end up with output<nnn>.mp4 files that you can combine with like:

ffmpeg -safe 0 -f concat -i mylist.txt -c copy output_total.mp4

with in mylist.txt: 

file 'output000.mp4'
file 'output001.mp4'
file 'output002.mp4'
etc.

**Comment by Johni0702** [comment]
I don't know about this one. It started out somewhat reasonably but then quickly divulged into a rant about windows followed by some random advice I can neither confirm nor even make sense of.
The original author has also been blocked due to their behavior in a different issue.
So I'm just gonna close it. I think the only relevant thing is indeed duplicated in that other issue (this one's older, technically the other issue is the duplicate).
