### ISSUE TITLE
Camera Angle With Roller Coaster Mod

### ISSUE THREAD

**Issue by Kepler-17c** [ReplayMod/ReplayMod#691]
Poki_Sen#3145 reported camera angles to not match roller coaster rotation:  
https://discord.com/channels/708304818829262910/709108200632483900/948338873287708773

Also, while replaying, the camera glitches once per second for a single frame when spectating the player in the roller coaster.

Mod Repository:  
https://github.com/fredtargaryen/ExRollerCoaster_Old/tree/1.12.2

Example Video:  
Joining world for recording at 1:10 https://youtu.be/foW0qmbuA14?t=70
Replaying as spectator at 2:34 https://youtu.be/foW0qmbuA14?t=154

Example Screenshots:  
<table>
<tr>
<th>With ReplayMod</th>
<th>Without ReplayMod</th>
</tr>
<tr>
<td><img height="200" src="https://cdn.discordapp.com/attachments/709108200632483900/948340294221443092/2022-03-01_23.04.52.png"></img></td>
<td><img height="200" src="https://cdn.discordapp.com/attachments/709108200632483900/948340294812835870/2022-03-01_23.02.14.png"></img></td>
</tr>
</table>

**Comment by Johni0702** [comment]
From a (way too long, cause it's borderline impossible to parse) look at the code of that mod, I've come to the conclusion that it just doesn't even work with vanilla spectator mode (e.g. it rotates the camera based on the player entity, not based on the camera entity), so I have little hope of getting it working with RM.
I have no clue how it also breaks during recording and cannot be bothered to figure that out (I'll admit, RM's codebase isn't the prettiest either, but did you have a look at their code?).

Closing as won't fix. If someone else wishes to dig into it, feel free, but I don't have much hope here.

**Comment by Kepler-17c** [comment]
I didn't have a look at their code, as I have lots of other things on my plate already - and I'm not that deep in Minecraft modding, either, so I miss the big picture of how the required things here work or should work.

When I get compatibility issues reported, I try to compile as much useful information as possible and rely on your experience and expertise on the topic to find the issue quickly. I may be a developer and the language I know best is Java, but I don't know enough about the specifics of Minecraft and/or the Mixin system.

**Comment by Johni0702** [comment]
That wasn't directed at you. I know you're just compiling reports based on what you can get from people on discord, please continue doing that, it's very much appreciated.
That comment was directed at future people coming across this issue wondering why I didn't look into it more, and wasn't meant to be offensive (except maybe to the author of that mod, but it's old code, they've probably improved by now).

**Comment by Kepler-17c** [comment]
All good - I just didn't get it was a rhetorical question 👍
