### ISSUE TITLE
Minecraft 1.18.2

### ISSUE THREAD

**Issue by Kepler-17c** [ReplayMod/ReplayMod#697]
Add compatibility with the new Minecraft update.

**Comment by Boobies** [comment]
Useful ticked, now people are informed that 1.18.2 is out. Otherwise ReplayMod would have never updated. :P

**Comment by Kepler-17c** [comment]
@Boobies it was a reaction to a question in staff chat:
![image](https://user-images.githubusercontent.com/17955785/156936520-9e3d4ab4-4704-4236-a723-f6010146f85d.png)
