### ISSUE TITLE
Add mod to curseforge [1.12.2]

### ISSUE THREAD

**Issue by BraveCaperCat** [ReplayMod/ReplayMod#706]
What if someone wanted this in a [curseforge](https://www.curseforge.com/minecraft/mc-mods/replay-mod-for-forge) modpack, that means, all mods, HAVE TO be on [curseforge!](https://www.curseforge.com/minecraft/mc-mods/replay-mod-for-forge)

**Comment by BraveCaperCat** [comment]
(Links, are for a [forge-update port](https://www.curseforge.com/minecraft/mc-mods/replay-mod-for-forge) on [curseforge,](https://www.curseforge.com/minecraft/mc-mods/replay-mod-for-forge) i already have asked them)

**Comment by BraveCaperCat** [comment]
REOPEN,
i can't put this in my modpack, it doesn't show up in the curseforge launcher,
what if you add a curseforge launcher install button to your site?

**Comment by Primitive-Human** [comment]
That's not a request you can make, neither one that someone affiliated with CurseForge can even do.

And it's only because you limit yourself to using that goddamn garbage installer and never learned to install mods manually.

**Comment by BraveCaperCat** [comment]
> That's not a request you can make, neither one that someone (un)affiliated with CurseForge can even do.
> 
> And it's only because you limit yourself to using that goddamn garbage installer and never learned to install mods manually.

I've installed mods manually before, i just now use curseforge launcher because it's simpler to use.

**Comment by BraveCaperCat** [comment]
Look at my minecraft versions folder:
https://user-images.githubusercontent.com/96585698/162728227-f87c8bbe-cbbd-42ce-a3db-28dc20237d4b.mp4

**Comment by BraveCaperCat** [comment]
> That's just factually incorrect: https://support.curseforge.com/en/support/solutions/articles/9000197913-non-curseforge-mods And last I checked, ReplayMod was on the Approved Non-CurseForge Mods list.

Seem to have found how it works, it displays in curseforge, but can't install it manually, I discovered this just now.
