### ISSUE TITLE
Unknown crash during render

### ISSUE THREAD

**Issue by Rafii2198** [ReplayMod/ReplayMod#717]
Usually I provide some info but I am completely clueless this time. Whenever I try to render the game crashes at the very beginning. 
[Link to crash report](https://0x0.st/oboO.txt)
Also another thing is that similar crash happens when I try to go back in timeline.
Removing Sodium, Iris, Indium doesn't change anything.

**Comment by Kepler-17c** [comment]
There are a ton of other mods - please narrow it down first by removing all non-essential mods and reproducing the issue.

Also, please use our official support Discord https://discord.gg/5GR7RSb for future issues.

**Comment by Johni0702** [comment]
This is caused by some third-party mod which messes with the GUI screen background rendering. If you've figured out which mod that is, you should report it to them.
