### ISSUE TITLE
Player heads in a replay from 1.8.9 don't have skins

### ISSUE THREAD

**Issue by Thr0nSK** [ReplayMod/ReplayMod#718]
When I record a replay on a 1.18.1 client on a server which is running on 1.8.9, the player heads have the default Steve skin in the replay.

**Comment by Johni0702** [comment]
Cannot reproduce:
![](https://i.johni0702.de/pk4zp.png)

**Comment by Thr0nSK** [comment]
Interesting... I hadn't tried it on hypixel before and when I did just now, I found out that the heads work correctly. Any idea what could be causing the placed heads not to have skins on a different server? It is only the heads that are placed in the world that don't have skins in the replay recording. A head in an armor stand loads fine.
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/82978711/162426698-86428163-ebee-4a33-915a-8c99da0d9bd4.png">

**Comment by Thr0nSK** [comment]
Update: I can see the heads when I have Automatic Recording turned ON. However, when I start the recording manually, the heads don't have the skins.

**Comment by Thr0nSK** [comment]
This is an issue on any Spigot server according to my testing. You can reproduce it by creating a Spigot server on 1.8.9.

**Comment by Johni0702** [comment]
Spigot 1.8.9 by itself doesn't support 1.18.1. What exactly is it using to convert the packets for 1.18.1 clients? The Spigot ViaVersion plugin? BungeeCord ViaVersion? Velocity ViaVersion? Something else entirely?
Ideally you'd just provide me with a publicly accessible server address or a raw recording (from `.minecraft/replay_recordings/raw/`, corresponding to one which has the issue), so I don't have to set all that up myself.

**Comment by Thr0nSK** [comment]
Sure, you can try it yourself on `play.survival-games.cz`. Spigot and BungeeCord ViaVersion are used for packet conversion. There are some player heads on the ground as well as on armor stands on the main lobby.
