### ISSUE TITLE
Please stop using adf.ly, It has because much more worse.

### ISSUE THREAD

**Issue by PF94** [ReplayMod/ReplayMod#72]
It seems they're changing the way how adf.ly works.

So i tried to download it, but adf.ly forced me to enable notifications, they're trying to install adware on my Firefox. I had to disable adblock, enable notifications, reenable adblock, Go to my Firefox settings and block notifications from the ad.fly site.

In fact, the domain wasn't even adf.ly. It was www1.ecleneue.com, which, when searching for the site, makes the search results filled with guides on how to remove pop-ups from it.

**Comment by CrushedPixel** [comment]
We have concrete plans to get rid of adf.ly once and for all, before long you shouldn't be bothered anymore. In the meantime, you can use the "Mirror" link on the website to skip adf.ly entirely.

**Comment by PF94** [comment]
Ah.

**Comment by pacmangraphics** [comment]
Same here.
Minecraft is a game played by millions of kids.
When downloading through adf.ly you get hard core porn pics (sometimes).
Very annoying. The company and all the advertisers there should be ashamed of themselves.
Trauma Based Mind Control and subliminal messages they call that.
That is why people hate western society.
Maybe even Bill Gates agrees with that? (Or he owns adf.ly, like he owns Mojang, AND GitHub...)

**Comment by PF94** [comment]
I think it's less of the programmer and more of the advertiser and adf.ly itself, as most of the ads in Adf.ly are ethier "Sign up to Roblox today!" or "OMG! I GOT 100 MILLION ON A CASINO! SIGN UP TO GET THE SECRETS!" or "Your Flash Player may be out of date. Please install the new update".

**Comment by NicKnack819** [comment]
> I think it's less of the programmer and more of the advertiser and adf.ly itself, as most of the ads in Adf.ly are ethier "Sign up to Roblox today!" or "OMG! I GOT 100 MILLION ON A CASINO! SIGN UP TO GET THE SECRETS!" or "Your Flash Player may be out of date. Please install the new update".

I've had worse... for example a crazy loud and long error beep sound

**Comment by PF94** [comment]
Oh, that's one of those Indian scammer junk,

Anyways, Adfly's moved to asking to enable notifications so they can serve you the same "OMG! I GOT 100 MILLION ON A CASINO! SIGN UP TO GET THE SECRETS!" crap.

**Comment by yungwilder** [comment]
How is this still open, 

> you can use the "Mirror" link on the website to skip adf.ly entirely.

Just make that the only link, remove the link to the malware infested site, there is no excuse to knowingly continue to expose people to that!

**Comment by CrushedPixel** [comment]
We are aware that it's a problem. If you want to support the mod, please check out our Patreon, it has a goal at which we'll remove AdFly links from the website. https://patreon.com/replaymod
