### ISSUE TITLE
i want to embed replay mod in my project

### ISSUE THREAD

**Issue by RandomTNT** [ReplayMod/ReplayMod#720]
Is there any way to embed this inside another mod?

**Comment by Kepler-17c** [comment]
Depends on the mod you want to embed it in. But more importantly: Why would you try to *embed* it in another mod - or do you mean mod-pack?  
This is quite the complex project and I don't see parts that could be sensible candidates to be embedded.

**Comment by Johni0702** [comment]
Then just install it as a regular mod.
