### ISSUE TITLE
Underwater is entirely blue and black

### ISSUE THREAD

**Issue by itsmorethantech** [ReplayMod/ReplayMod#732]
![image](https://user-images.githubusercontent.com/82797019/168417759-d0b28e22-7253-4c83-830f-ac1bf337ff3d.png)
https://www.youtube.com/watch?v=JyNf0-0LsXI

(Mod pack is Fabulously Optimized with sodium disabled)

**Comment by Johni0702** [comment]
What's your ReplayMod version?

**Comment by Johni0702** [comment]
Duplicate of #572
