### ISSUE TITLE
Chunks won't load when opening up replay preview

### ISSUE THREAD

**Issue by Than0sCr33per** [ReplayMod/ReplayMod#734]
I recently recorded something on replay, and I'm trying to open it up on the preview mode, but nothing in the world is loading in. I've tried exiting the game, reloading the chunks, and shutting off my pc, but nothing changes. The only possible reason I could see for this is that the full recording is around 25 minutes, and i tried fixing that by splitting the recording into two, but it changed nothing.

I'm using replay on Minecraft version 1.18.2.

**Comment by Johni0702** [comment]
Press `B` to open the Player Overview, then click on your player, it should go into first person spectator mode (sneak to exit first person again). Does that fix it?
