### ISSUE TITLE
Crash when using ReplayMod (Fabric 1.16.5)

### ISSUE THREAD

**Issue by ComeOnBear** [ReplayMod/ReplayMod#737]
as title says!

latest.log is linked.

can link a replay of the crash if required, happens every time I boot with the .jar installed into the mod folder.
[latest.log](https://github.com/ReplayMod/ReplayMod/files/8749647/latest.log)

**Comment by Johni0702** [comment]
Update OptiFabric. If that doesn't fix it, remove Optifine and OptiFabric and [use alternatives](https://lambdaurora.dev/optifine_alternatives/).
