### ISSUE TITLE
Circumventing choppy player POV?

### ISSUE THREAD

**Issue by couleurm** [ReplayMod/ReplayMod#738]
Hey,

I'm trying to step up my VFX and noticed Replay Mod allows to export directly to **Blender**

But the biggest issue I have is that my player's perspective is smoothed and not accurate to the original mouse movements.

Here's some ways I've thought of going about to make it less worse:
* Using some kind of tool that can record my real mouse movement while I'm also recording, then replace my player's **head** movement with it
* Recording at the same time with OBS using a green-screen pack and then trying to overlay that on top of a replay mod project that's been exported to 360° 

Do you knowledgeable folks know any alternatives / ways to circumvent choppy POV? (***even cumbersome ways***)

**Comment by Stonley890** [comment]
I should preface by saying I'm not an expert, but I believe ReplayMod records the server ticks and linearly interpolates between each tick (which only gives you about 20hz of exact information). Recording the client-side movement would be a separate process entirely.

If you have the time, tools, and patience, it's possible that you could record your screen using OBS and then (with ReplayMod camera interpolation set to linear) match-move the ReplayMod camera to the overlaid OBS reference frame by frame (perhaps at half speed) with your player hidden.

Still, that has drawbacks and is extremely cumbersome.

**Comment by couleurm** [comment]
https://github.com/Igrium/ReplayFPS
