### ISSUE TITLE
Replay mod for forge 1.14.4??

### ISSUE THREAD

**Issue by Torunator** [ReplayMod/ReplayMod#74]
Any updates ?

**Comment by Johni0702** [comment]
Probably not happening. Porting to Forge requires significant work for no gain.
There's also the issue that 1.13+ Forge doesn't support Mixin (which we have a hard dependency on) whereas in Fabric it has first-party support which is really convenient.

If there's ever support for loading Fabric mods on Forge and the RM doesn't work in that setup, then that's a different issue and far more likely to get fixed.

**Comment by PF94** [comment]
fabric is 2x harder to install than forge,

**Comment by haykam821** [comment]
@PF94 It is not. You just need to find [the installer download](https://fabricmc.net/use/).
