### ISSUE TITLE
Add Logical Zoom compatibility

### ISSUE THREAD

**Issue by Lentern** [ReplayMod/ReplayMod#746]
I suggest adding compatibility with the [Logical Zoom](https://www.curseforge.com/minecraft/mc-mods/logical-zoom) Fabric mod. Just like with OptiFine, you should be able to zoom in while you are editing a replay.

**Comment by Johni0702** [comment]
Seems to be working perfectly fine for me after changing the key binding.

**Comment by Lentern** [comment]
I'm sorry, it seems to work now. I'm not sure why I remembered it not working but after testing it again on 1.17.1-1.19, it seems fine.
