### ISSUE TITLE
please publish jar files on github releases page

### ISSUE THREAD

**Issue by gmankab** [ReplayMod/ReplayMod#748]

**Comment by Kepler-17c** [comment]
You find all present and past versions on <https://www.replaymod.com/download/>.
What benefit would GitHub releases have over this?

**Comment by TheKodeToad** [comment]
Usage of GitHub API?

**Comment by gmankab** [comment]
github more friendly for parsing and automatic downloads

**Comment by TheKodeToad** [comment]
ReplayMod is not on CurseForge or Modrinth, so they probably don't want it on GitHub releases either.

**Comment by TheKodeToad** [comment]
Update: ReplayMod is now on modrinth
https://modrinth.com/mod/replaymod

You can use their well-documented API to download:
https://docs.modrinth.com/

**Comment by gmankab** [comment]
> Update: ReplayMod is now on modrinth https://modrinth.com/mod/replaymod
> 
> You can use their well-documented API to download: https://docs.modrinth.com/

thanks
