### ISSUE TITLE
Steve arm in 1st person

### ISSUE THREAD

**Issue by LindaJuffermans** [ReplayMod/ReplayMod#749]
Not only is the outer layer missing of my skin, it's also not my skin on the inner layer.

Minecraft 1.8.9
Forge 11.15.1.1722
ReplayMod 2.6.6

In-game screenshot while recording:
![2022-07-03_08 27 19](https://user-images.githubusercontent.com/31929183/177028019-23551bd9-d47f-43be-b9d5-7e573b8fe86d.png)

Replay Viewer 3rd person view:
![3rdperson](https://user-images.githubusercontent.com/31929183/177028031-f34d6111-2533-43a2-ad38-f52035ad210a.jpg)

Replay Viewer 1st person view:
![1stperson](https://user-images.githubusercontent.com/31929183/177028039-d1d439db-6b3a-4dbd-a249-537dbd42f870.jpg)

Replay Viewer 1st person screenshot:
![2022-07-03_08 28 45](https://user-images.githubusercontent.com/31929183/177028054-c6af0cef-db96-4860-981f-a6606b984949.png)

The recording file:
[2022_07_03_08_26_58.zip](https://github.com/ReplayMod/ReplayMod/files/9034177/2022_07_03_08_26_58.zip)

It *might* be related to https://github.com/ReplayMod/ReplayMod/issues/363.

**Comment by PandoCyclone** [comment]
Umm for me i use a client and enable culling when I switch to version 2.6.4 it works
