### ISSUE TITLE
Replay Mod rendered videos are corrupted

### ISSUE THREAD

**Issue by G93d14** [ReplayMod/ReplayMod#75]
The rendering progress bar is only quarterwise visible, and in the rendered video, also, only a portion of the actual clip is clean, the rest are a series of vertical or horizontal stripes. There was a similar issue on the replaymod website, but that user did not have any issue with the final product, and their issues disappeared on using a PC.

I am running replay mod 1.14.4 on Fabric through MultiMC on a Windows machine, if that helps.

I am sorry I can't describe this better, but I have attached a clip of the video and my log for that session:
[2019_08_28_19_07_00_Moment](https://user-images.githubusercontent.com/54314688/63862463-42096700-c9ca-11e9-9188-4e69d842abc3.jpg)
[latest.log](https://github.com/ReplayMod/ReplayMod/files/3551234/latest.log)

**Comment by G93d14** [comment]
update: the issue only seems to exist for render resolutions higher than my monitor resolution, a 720p video rendered just fine.

**Comment by Johni0702** [comment]
Any difference without all the other mods?
Either way, please post a log without them so it's clearer what's noise and what isn't.

**Comment by G93d14** [comment]
> Any difference without all the other mods?

That's strange, it doesn't seem to happen without the other mods.

**Comment by G93d14** [comment]
i really don't have the time to see which mod specifically is causing this error, but i can only see optifine (or the porting mod) as the other mod affecting rendering or graphics in my list.

**Comment by G93d14** [comment]
Here's a trimmed log from the same session with only replaymod, fabric, and optifine entries.
[2019-08-28-3_modified.log](https://github.com/ReplayMod/ReplayMod/files/3562102/2019-08-28-3_modified.log)

**Comment by pacmangraphics** [comment]
Use Encoding Presets: MP4 - High Quality.
Then convert later to smaller size with (latest) ffmpeg.exe with something like this:
ffmpeg -y -ss 00:19:00 -i some_music.mp3 -i 2019_09_12_02_09_25.mp4 -shortest -c:a aac -b:a 96k -c:v libx264 -preset veryfast -crf 23 -pix_fmt yuv420p youtube_format_with_audio.mp4
