### ISSUE TITLE
View Replay option doesn't appear at all

### ISSUE THREAD

**Issue by Snans101** [ReplayMod/ReplayMod#755]
When i'm on the main menu, the view replay button doesn't show up. and when im in game the options to toggle recording and such aren't there either. And I made sure i had the mod installed, I can configure the mod. It tells me it's recording. I just have no way of viewing the recording

**Comment by Johni0702** [comment]
Sounds like you're using some mod which replaces the main menu. Remove that mod or configure it to show the Replay Viewer button.

**Comment by Snans101** [comment]
> Sounds like you're using some mod which replaces the main menu. Remove that mod or configure it to show the Replay Viewer button.

I have already fixed it, and it was this issue. Thanks!
