### ISSUE TITLE
1.19.1-2 Version crashes on Replay viewer after recording on GeyserMC server.

### ISSUE THREAD

**Issue by DewsJaz** [ReplayMod/ReplayMod#764]
I am using ReplayMod in 1.19.1 on Sodium and Iris with Shaders. ReplayMod crashes when scrubbing past a certain point in the timeline and says "Saving World..." before crashing.

The first time this happened, all I had to do was turn off show chat in ReplayMod settings and it worked. The second time it happened, it still crashed despite show chat being off.

The server it was recorded on uses GeyserMC with floodgate, and since 1.19 geyser doesn't suport Chat Validation, the server had enforce-secure-profile in server properties set to false.

When viewing the recording, ReplayMod only crashes past a certain point in the timeline, and exactly when it gets past that point. I think there is an issue between GeyserMC and ReplayMod concerning the new Chat Validation Features that's causing the recording to crash.

Tried recreating the issue on 1.19.2 as someone on Discord suggested to do so and the issue still exists on version 1.19.2.

[latest.log](https://github.com/ReplayMod/ReplayMod/files/9281882/latest.log)

**Comment by MathiasYde** [comment]
Did you pause during recording?
