### ISSUE TITLE
Raw files pile up and dont delete themselves

### ISSUE THREAD

**Issue by mharbb** [ReplayMod/ReplayMod#765]
This takes up a lot a space

![image](https://user-images.githubusercontent.com/90333698/185680136-1134eedf-07a8-47a8-be8a-02255133b328.png)

This is the location-->
![image](https://user-images.githubusercontent.com/90333698/185680319-3b003341-c3b6-4172-9729-6767594076ef.png)

**Comment by Johni0702** [comment]
Raw files are kept for three weeks such that by the time you notice issues in the cut file, they're still there so you can use them instead and so you can submit them in a bug report.
