### ISSUE TITLE
MultiConnect + Replay Mod issue.

### ISSUE THREAD

**Issue by Aerodin** [ReplayMod/ReplayMod#769]
Hi,

I am trying to play on a 1.19 server using 1.19.2.  I play on several servers so using the latest client and MultiConnect to connect to any servers that are running older versions is needed.

The server in question I am creating this issue is for is a mostly vanilla Fabric server and has several Fabric mods like No Chat Report running.  I am unable to test the server side of things to to see if any of those impact the crash that happens when I try to connect/play.  On my full mods setup it would crash 1-5 minutes into play and on the vanilla setup it crashes immediately on connecting to the server. 

I narrowed this down to ReplayMod being the one causing the crash specifically.  I then recreated the issue using a fresh Minecraft instance with the mods in question only (latest versions). 

Minecraft 1.19.2
Fabric loader 0.14.9 + LWJGL 3.3.1

Mods:
Fabric API 0.60.0+1.19.2
MultiConnect 1.6-beta.23
Replay Mod 1.19.1-2.6.8

Screenshot of Errors:
https://imgur.com/a/AbGr2Xs

Log was too big for pasting here so I uploaded it.  Here is the download link for MinecraftLog-ReplayModCrash.txt:
https://wetransfer.com/downloads/9d11c9c13c9c7bddf9c5e0fe5929f99c20220825175239/4272e6154fe60bb8765099a544c141fc20220825175311/986316

**Comment by Felix14-v2** [comment]
#558
