### ISSUE TITLE
Sodium 4.4

### ISSUE THREAD

**Issue by PandaUprising** [ReplayMod/ReplayMod#772]
Hello,

Just a minor bug sodium 4.4 is releases and the new version iris (for shaders) needs sodium 4.4 but only 4.2 is available for replay mod

Thanks, PandaUprising

**Comment by Johni0702** [comment]
The official Sodium 0.4.4 should be compatible with ReplayMod now, you no longer need a special version.

**Comment by PandaUprising** [comment]
Ahh ok, Thank you!
