### ISSUE TITLE
Is there a way to reconstruct the map that the replay was played on?

### ISSUE THREAD

**Issue by hat7004** [ReplayMod/ReplayMod#779]
I have some replays that I would really want the map to play around with it in the single player. Is there a way to reconstruct such map from the replay file?

**Comment by drewc5131** [comment]
Believe they said no to this in the past, but would be nice since I have some replay files of our old maps that i dont have anymore sadly

**Comment by Johni0702** [comment]
This won't be a feature in ReplayMod directly because it's quite complex to do and very much out of scope.
But it should be possible to use a third-party world-downloader (mod or standalone) on replays. See for example https://github.com/bela333/replaymod-world.
