### ISSUE TITLE
Opening Replay Viewer Crashes With Meteor Client 1.19.2

### ISSUE THREAD

**Issue by TheKidThatCodes** [ReplayMod/ReplayMod#780]
When Meteor client is installed, opening the replay viewer crashes the game

**Comment by RaderRMT** [comment]
That's an issue with baritone, a mod meteor comes with.

**Comment by Johni0702** [comment]
Update baritone, and if that doesn't fix it, please provide more information on the actual crash (like the crash report and logs).
