### ISSUE TITLE
Why the newer versions aren´t for Forge?

### ISSUE THREAD

**Issue by Alphastein2021** [ReplayMod/ReplayMod#784]
I need Forge not Fabric!

**Comment by RaderRMT** [comment]
Fabric is the way to go.
https://web.archive.org/web/20220327080636/https://www.reddit.com/r/feedthebeast/comments/c0wkph/modmakers_how_likely_are_you_to_use_fabric_over/er8z4hr/

**Comment by Alphastein2021** [comment]
But not for **me**

**Comment by Johni0702** [comment]
You'll need to find someone willing to port RelayMod to modern Forge then. I'm will not be that person, Forge has been a PITA to work with for me for too long.

**Comment by Alphastein2021** [comment]
But how?
