### ISSUE TITLE
Server sent an invalid packet

### ISSUE THREAD

**Issue by lambrymc** [ReplayMod/ReplayMod#789]
So I was recording on a server and when I went to render some clips this popped up. I'd really appreciate some help
![javaw_nbsbnS22PM](https://user-images.githubusercontent.com/117764493/200635270-187929e1-1e6c-4669-a106-8730193c4d87.png)

**Comment by Hyphonic** [comment]
I got the same issue, i think replaymod require some mods u used while recording to be active on the client

**Comment by la-jig** [comment]
If you have multiconnect mod, that mod is the issue

**Comment by Hyphonic** [comment]
Yes, so i think the best thing u can do is run with the lowest amount of mods or mods wich you know won't break Replaymod.

**Comment by Hyphonic** [comment]
Sorry if you can't understand my comment, english isn't my main language.

**Comment by Johni0702** [comment]
Due to lack of details supplied by the OP, I'll assume this was indeed caused by the multiconnect incompatibility and will close this as a duplicate of #558.
