### ISSUE TITLE
Replay unrecoverable after full PC crash

### ISSUE THREAD

**Issue by UltimateCactus** [ReplayMod/ReplayMod#799]
I was editing a replay and my computer decided to crash. I still have the replay file, and everything looks fine, but the actual replay doesn't show up in the game. I attempted to recreate a "failed to save replay" situation, wherein the game would ask at start-up if you wanted to recover it, and upon saying yes it came up with a crash message in game (the game didn't close, I can still play). I have linked [a .zip file](https://drive.google.com/file/d/1XOvrHNLY_VNZEMYIwxpKWAdbvS9ZjWQB/view?usp=sharing) with the report, the corrupted replay and my fake replay .tmp folder (I couldn't upload it - too big).
Is it possible to manually recover this replay? From the crash report it looks like relatively simple fix, but I don't have the technical knowledge to do so.

**Comment by Johni0702** [comment]
Haven't checked if it actually plays but here is the same file with the zip error fixed, some data at the end of the replay may have been lost: https://send.vis.ee/download/66df6a7147df5e8a/#h3UiJdcoYqO1rjUJwJVX4g (download will expire)

FTR, this is what I did:
```
mkdir tmp
jar xvf ../broken.mcpr
jar cvf ../recovered.mcpr *
cd ..
rm -r tmp/
```

**Comment by UltimateCactus** [comment]
Thanks! I was going to use some footage from this in a video, but I am going on holiday tomorrow (as of this message) and was on a bit of time pressure so ended up not using it, but it's really good having the actual replay back!
You're a legend :)
