### ISSUE TITLE
Non-linear interpolation causes camera to rotate long way around

### ISSUE THREAD

**Issue by slicedlime** [ReplayMod/ReplayMod#8]
For instance, I had a path with a camera yaw of 1 at one point and -303 at the next (=47), and it wrapped the long way around instead of the short way. This makes paths nearly impossible to make because the camera keeps spinning wildly out of place.

It looks to me like this code from LinearInterpolator.java:

               if (!Double.isNaN(bound)) {
                    before = mod(before, bound);
                    after = mod(after, bound);
                    if (before < bound / 2 ^ after < bound / 2) {
                        // Wrapping around is quicker
                        if (before < bound / 2) {
                            after -= bound;
                        } else {
                            after += bound;
                        }
                    }
                }

Has no corresponding code in the other interpolator classes.

**Comment by Johni0702** [comment]
I cannot reproduce this using the cubic interpolation.
The corresponding code for it can be found in its super class, [here](https://github.com/ReplayMod/ReplayStudio/blob/bf2c7f3a22bdd80cc426c9b30c225632ad5d86d8/src/main/java/com/replaymod/replaystudio/pathing/interpolation/PolynomialSplineInterpolator.java#L122-L142).

I can however reproduce it with the CR interpolation and unless I'm missing something there doesn't seem to be any code to handle it.
