### ISSUE TITLE
Chat message validation failure

### ISSUE THREAD

**Issue by BluSpring** [ReplayMod/ReplayMod#801]
I tried to play back a replay recording I had made during this event I had participated in yesterday, and I ended up with this error
![image](https://user-images.githubusercontent.com/20620191/205887519-a7acce3e-0085-4db0-839b-1a99838ddb81.png)

According to the logs, I believe it to be failing due to Minecraft trying to load someone else's public key when they had logged into the server when the recording had started.
![image](https://user-images.githubusercontent.com/20620191/205887632-5143f9c4-106a-498e-9152-b6fac6950d32.png)

From what I'm aware, the server appears to have just been regular PaperMC, though there may have been some changes to its config.

[latest.log](https://github.com/ReplayMod/ReplayMod/files/10165423/latest.log) [IKEA Hide & Seek.mcpr](https://drive.google.com/file/d/1LM2S-l4Ldrr-x3dazQzqUZwK648Qrtmp/view?usp=sharing)

Attached are both the logs from trying to load it, and the problematic Replay file, though keep in mind that the file is 1 GB.

**Comment by Johni0702** [comment]
This is a known bug, though it appears I forgot to open an issue for it on GitHub.

The Minecraft 1.19.1 version of ReplayMod is *almost* fully compatible with Minecraft 1.19.2 except for this chat signing detail which changed again in Minecraft 1.19.2 such that the 1.19.1 fix included in ReplayMod no longer works.

A new fix will be included with the next update (which will also include 1.19.3 support). Until then, you can either use Minecraft 1.19.1 or disable playback of the chat in the ReplayMod Settings (accessible via the gear icon in the top right of the Replay Viewer screen, the key binding, or via ModMenu).
