### ISSUE TITLE
ReplayMod 1.19.3-2.6.9 not recording on multiplayer

### ISSUE THREAD

**Issue by RaderRMT** [ReplayMod/ReplayMod#803]
ReplayMod does not record multiplayer servers as it thinks they're replays.
Tried with automatic recording on and off and `Recording Server` is enabled.
It works fine on singleplayer though.

The [log](https://github.com/ReplayMod/ReplayMod/files/10189813/latest.log) doesn't contain much but I attached it nonetheless.

**Comment by abcdabra** [comment]
Can confirm, on singleplayer, the "Start Recording" button is available, but on multiplayer, it is not
