### ISSUE TITLE
When trying to watch a replay it says: server sent a invalid packet

### ISSUE THREAD

**Issue by normaluser12354** [ReplayMod/ReplayMod#816]
I want to know why it sends that

**Comment by la-jig** [comment]
Do you have MultiConnect?

**Comment by normaluser12354** [comment]
yes

**Comment by la-jig** [comment]
I have used that mod before, Replay Mod gets confused with server packets, because for example, it expects your Minecraft's client versions packets while it gets old packets, MultiConnect is the issue.

**Comment by normaluser12354** [comment]
ok
