### ISSUE TITLE
Replace Skin in Replay with Custom Local Skin

### ISSUE THREAD

**Issue by nzcsx** [ReplayMod/ReplayMod#825]
I want to replace the skin in replay with other skins. I am planning to do it by changing the source code, but I am not quite sure how.

I am able to ask the players to change the skins on Mojang website. Therefore, if there is a way to retrieve the latest skins, that would also work. Thank you.

**Comment by Kepler-17c** [comment]
One of our moderators (Rader) is developing a replay editing tool, that can change skins - his Discord is https://discord.gg/zNVkeGdjKt

**Comment by nzcsx** [comment]
Thank you. I'll keep an eye on it. I'm closing the issue for now.
