### ISSUE TITLE
Enhancement: Option to hide the timeline

### ISSUE THREAD

**Issue by Roadhog360** [ReplayMod/ReplayMod#826]
Render video has no sound, does not render chat or scoreboard, and takes over twice as long. I just want to quickly render a first person POV and make it closer to in-game footage, but these errors in rendering make it impossible.

I'd like an option to simply hide the timeline for more simple jobs like mine. I just need to record first person footage and the chat and scoreboard should be shown. No, F1 is not an option as it hides those things. Rendering seems to do a worse job for my use case and takes far longer than simply screen recording to get everything I want.

I have everything I need already in the game that I could screen record right now but unfortunately the huge timeline is in the way.

**Comment by RaderRMT** [comment]
press f1

**Comment by Roadhog360** [comment]
When was this a thing? I Googled all over and only saw the author telling people there's no way to hide the timeline.

**Comment by RaderRMT** [comment]
it has been added in [2.5.0](https://www.replaymod.com/changelog.txt)
