### ISSUE TITLE
Crashing in render and in 1080 x 1920 resolution is black screen (image)

### ISSUE THREAD

**Issue by OlmiPl** [ReplayMod/ReplayMod#828]
![22](https://user-images.githubusercontent.com/117110989/227327616-1dda7752-654a-4408-8306-523e689d8f48.png)

info: [20:23:11] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
info: [20:23:11] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
info: [20:23:12] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on G o niki (Realtek(R) Audio)
info: [20:23:12] [Render thread/INFO]: Sound engine started
info: [20:23:12] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
info: [20:23:12] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
info: [20:23:12] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
info: [20:23:12] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
info: [20:23:12] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
info: [20:23:12] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
info: [20:23:12] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
info: [20:23:12] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
info: [20:23:12] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
info: [20:23:12] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
info: [20:23:12] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
info: [20:23:14] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Controlling For Fabric, Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric Block API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Client Tags, Fabric Command API (v1), Fabric Command API (v2), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Convention Tags, Fabric Crash Report Info (v1), Fabric Data Generation API (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Groups (v0), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Lifecycle Events (v1), Fabric Loot API (v2), Fabric Loot Tables (v1), Fabric Message API (v1), Fabric Mining Level API (v1), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Particles (v1), Fabric Recipe API (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Conditions API (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Sound API (v1), Fabric Textures (v0), Fabric Transfer API (v1), Fabric Transitive Access Wideners (v1), Fabric Loader, Feather Client, Replay Mod), 269b3e3aeb7805e3ca5973735dec12701ae44072.zip, replaymod_lang
info: [20:23:15] [Worker-Main-5/WARN]: Unable to load model: 'armory:auto_generated/obsidian_chest' referenced from: minecraft:leather_chestplate#inventory: java.io.FileNotFoundException: armory:models/auto_generated/obsidian_chest.json
info: [20:23:15] [Worker-Main-5/WARN]: Unable to load model: 'boxitems:item/tree' referenced from: minecraft:spruce_sapling#inventory: com.google.gson.JsonParseException: boxitems:item/custom/H4UPbx is not valid resource location
info: [20:23:15] [Worker-Main-5/WARN]: Unable to load model: 'armory:auto_generated/obsidian_boots' referenced from: minecraft:leather_boots#inventory: java.io.FileNotFoundException: armory:models/auto_generated/obsidian_boots.json
info: [20:23:15] [Worker-Main-5/WARN]: Unable to load model: 'armory:auto_generated/obsidian_legs' referenced from: minecraft:leather_leggings#inventory: java.io.FileNotFoundException: armory:models/auto_generated/obsidian_legs.json
info: [20:23:15] [Worker-Main-5/WARN]: Unable to load model: 'boxitems:item/bow-czarnobyl_pulling_2' referenced from: minecraft:bow#inventory: java.io.FileNotFoundException: boxitems:models/item/bow-czarnobyl_pulling_2.json
[20:23:15] [Worker-Main-5/WARN]: Unable to load model: 'boxitems:item/bow-czarnobyl_pulling_1' referenced from: minecraft:bow#inventory: java.io.FileNotFoundException: boxitems:models/item/bow-czarnobyl_pulling_1.json
[20:23:15] [Worker-Main-5/WARN]: Unable to load model: 'boxitems:item/bow-czarnobyl_pulling_0' referenced from: minecraft:bow#inventory: java.io.FileNotFoundException: boxitems:models/item/bow-czarnobyl_pulling_0.json
info: [20:23:17] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[20:23:17] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
info: [20:23:17] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on G o niki (Realtek(R) Audio)
info: [20:23:17] [Render thread/INFO]: Sound engine started
info: [20:23:17] [Render thread/INFO]: Created: 2048x1024x4 minecraft:textures/atlas/blocks.png-atlas
info: [20:23:17] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
info: [20:23:17] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
info: [20:23:17] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
info: [20:23:17] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
info: [20:23:17] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
info: [20:23:17] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
info: [20:23:18] [Render thread/WARN]: Shader rendertype_armor_cutout_no_cull could not find sampler named Sampler1 in the specified shader program.
info: [20:23:18] [Render thread/WARN]: Shader rendertype_entity_translucent could not find uniform named IViewRotMat in the specified shader program.
[20:23:18] [Render thread/WARN]: Shader rendertype_entity_translucent could not find uniform named FogShape in the specified shader program.
info: [20:23:18] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
info: [20:23:18] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
info: [20:23:18] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[20:23:18] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
info: [20:23:20] [pool-8-thread-1/ERROR]: Failure during rendering: 
com.replaymod.render.FFmpegWriter$FFmpegStartupException: null
	at com.replaymod.render.FFmpegWriter.getVideoFile(FFmpegWriter.java:163) ~[replaymod-1.19.2-2.6.10.temp.jar:?]
	at com.replaymod.render.FFmpegWriter.consume(FFmpegWriter.java:121) [replaymod-1.19.2-2.6.10.temp.jar:?]
	at com.replaymod.render.rendering.VideoRenderer$1.consume(VideoRenderer.java:154) [replaymod-1.19.2-2.6.10.temp.jar:?]
	at com.replaymod.render.rendering.Pipeline$ParallelSafeConsumer.consume(Pipeline.java:150) [replaymod-1.19.2-2.6.10.temp.jar:?]
	at com.replaymod.render.rendering.Pipeline$ProcessTask.run(Pipeline.java:118) [replaymod-1.19.2-2.6.10.temp.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
info: [20:23:20] [Render thread/WARN]: Shader feather_colorsaturation could not find uniform named InSize in the specified shader program.

**Comment by Johni0702** [comment]
Your log is incomplete and difficult to read. Please just attach the `latest.log` file instead of pasting parts of the log verbatim.

**Comment by OlmiPl** [comment]
Sorry i forgot to close this issue it’s work on difrent launther on Clean minecraft
