### ISSUE TITLE
сбой при сохранении повторен 1.16.5

### ISSUE THREAD

**Issue by Bernchik** [ReplayMod/ReplayMod#830]
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 24.03.23 11:22
Description: Saving replay file

io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release0(AbstractReferenceCountedByteBuf.java:100) ~[netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:84) ~[netty-all-4.1.25.Final.jar:4.1.25.Final] {}
	at com.replaymod.replaystudio.io.ReplayOutputStream.doWrite(ReplayOutputStream.java:166) ~[?:?] {re:classloading}
	at com.replaymod.replaystudio.io.ReplayOutputStream.write(ReplayOutputStream.java:146) ~[?:?] {re:classloading}
	at com.replaymod.editor.gui.MarkerProcessor.apply(MarkerProcessor.java:192) ~[?:?] {re:classloading}
	at com.replaymod.recording.packet.PacketListener.saveReplayFile(PacketListener.java:304) ~[?:?] {re:classloading}
	at com.replaymod.recording.packet.PacketListener.lambda$channelInactive$2(PacketListener.java:108) ~[?:?] {re:classloading}
	at com.replaymod.recording.packet.PacketListener$$Lambda$5066/65108042.run(Unknown Source) ~[?:?] {}
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1407761632 bytes (1342 MB) / 3154116608 bytes (3008 MB) up to 3154116608 bytes (3008 MB)
	CPUs: 12
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmx3000M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine-OptiFine-1.16.5_HD_U_G8_pre2.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.39.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.39
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.39-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.39-universal.jar                |Forge                         |forge                         |36.2.39             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		tl_skin_cape_forge_1.16.5-1.19.jar                |TLSkinCape                    |tlskincape                    |1.19                |DONE      |Manifest: 19:f5:ce:44:81:0c:e4:22:05:5e:73:c5:a8:cd:de:f3:c8:cf:a9:b3:01:70:40:a0:ee:2d:50:7a:1c:3d:1c:8a
		replaymod-1.16.4-forge-1.0.1.jar                  |Replay Mod                    |replaymod                     |2.5.1               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 1b5eb01b-6d18-4301-ab6d-d1bfc6703993
	OptiFine Version: OptiFine_1.16.5_HD_U_G8_pre2
	OptiFine Build: 20210305-002749
	Render Distance Chunks: 64
	Mipmaps: 1
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 528.24
	OpenGlRenderer: NVIDIA GeForce RTX 3050 Laptop GPU/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Comment by RaderRMT** [comment]
you are using an unofficial forge port. go ask its creator for help.
