### ISSUE TITLE
Please update the mod to 1.19.4

### ISSUE THREAD

**Issue by TechPro424** [ReplayMod/ReplayMod#831]
Please update the mod to 1.19.4
(Take your time, no pressure :) )

**Comment by Bahesh** [comment]
yeah waiting , but no pressure.

**Comment by Johni0702** [comment]
Just released ReplayMod 2.6.11 with support for Minecraft 1.19.4.
Git it while it's hot (and tell me if it explodes before I go ping everyone tomorrow):
https://www.replaymod.com/download/ or https://modrinth.com/mod/replaymod

**Comment by Bahesh** [comment]
Thanks A Lot. This mod is just amazing , and helpful to document all the best moments in the game.

**Comment by TechPro424** [comment]
For me, it's mainly useful if I fall to my death or into lava somewhere and need the coordinates so that my brothers can come and save me :)

**Comment by Bahesh** [comment]
I see.
