### ISSUE TITLE
when I click on the replay viewer it says saving and then it crashes 

### ISSUE THREAD

**Issue by ary4nk** [ReplayMod/ReplayMod#839]
when I click on the replay viewer it says saving and then it crashes

**Comment by Kepler-17c** [comment]
Please use our official support Discord - it's linked on https://replaymod.com/

**Comment by Johni0702** [comment]
> this is a bug deeply rooted in the design of the current gui library which RM uses, and as such is quite difficult to fix (so I've more or less stopped trying, especially because I will slowly transition to a different gui lib anyway). this happens when a key is pressed on the very first frame after the Replay Viewer screen (or really any RM gui) is opened.
usually super easy to avoid but I recall there was one case years back where for some unknown reason someone's mouse (or keyboard?) driver would always send a keypress immediately after they clicked something, thereby reliably triggering this bug. unfortunately I have no way to find that conversation and I don't recall how they solved it but I'm guessing you've got the same issue. if you happen to own a different mouse or have some other way to click the button, then try playing around with that, or try re-plugging your mouse. I vaguely remember something like that helping them solve it.
