### ISSUE TITLE
Buttons in the main and pause menu do not move on resize on 1.19.4

### ISSUE THREAD

**Issue by simply-kel** [ReplayMod/ReplayMod#841]
When you change the size of the window, the buttons do not move with the others.
I have seen this in the main menu and in the pause menu.

# In the main menu
### Before resizing
![Снимок экрана от 2023-04-13 09-58-33](https://user-images.githubusercontent.com/86980879/231679708-318d6bf4-430b-42cc-bd5f-ad003274e7a6.png)

### After resizing
![Снимок экрана от 2023-04-13 09-58-38](https://user-images.githubusercontent.com/86980879/231679728-b3f5d36c-333a-4c4a-a014-1372aa647828.png)

# In the pause menu
### Before resizing
![Снимок экрана от 2023-04-13 10-07-26](https://user-images.githubusercontent.com/86980879/231680895-c6181f45-873b-4785-8ba7-86e3b3080856.png)

### After resizing
![Снимок экрана от 2023-04-13 10-07-34](https://user-images.githubusercontent.com/86980879/231680920-ed55b522-e6b8-4540-97d3-09d6c71bff24.png)

MC: 1.19.4
Fabric: 0.14.17
FAPI: v0.78.0+1.19.4

**Comment by mooziii** [comment]
Can confirm for Fabric 1.19.4

**Comment by cootshk** [comment]
Also happens to me
