### ISSUE TITLE
Item-Display Teleport Rubber-Bands

### ISSUE THREAD

**Issue by Kepler-17c** [ReplayMod/ReplayMod#846]
On a clean instance with Fabric, teleport of a `minecraft:item_display` entity works flawlessly. Once ReplayMod is added, it breaks and seems to jump around between two locations.

Steps to reproduce:

- place two command blocks
- keep the first on impulse with command `summon zombie ~ ~ ~ {Passengers:[{id:"minecraft:item_display",item:{id:"minecraft:iron_axe",Count:1b}}],ArmorItems:[{},{},{},{id:"minecraft:iron_helmet",Count:1b}],ActiveEffects:[{Id:14,Amplifier:1b,Duration:-1,ShowParticles:0b}]}`
- set the second to repeat with command `execute as @e[type=minecraft:item_display] at @s run tp @s ~ ~ ~ facing entity @p`
- run the impulse block
- activate the repeat block

Support thread: https://discord.com/channels/708304818829262910/1103748525566734336

**Comment by byquanton** [comment]
Also having this behavior:

Only having Replay Mod (1.20.1-2.6.13) installed without other mods.

The entity is an item_display on an armor_stand ~~(with motion)~~ and the Rotation[0] value is copied from the player, so it rotates with the Player's Head Rotation.

[Vanilla Behavior](https://youtu.be/ShWZdY-e4xA)
[Replay Mod Behavior](https://youtu.be/3P_qvzt6qpw)

[Test World replaybug.zip](https://github.com/ReplayMod/ReplayMod/files/12307088/replaybug.zip)

**Comment by AloneRUS** [comment]
This bug still exist
Do you have plans about fix?
