### ISSUE TITLE
Problem, infinity of world loading 

### ISSUE THREAD

**Issue by Mega4oSS** [ReplayMod/ReplayMod#848]
Screen
![image](https://github.com/ReplayMod/ReplayMod/assets/69154702/d2646269-e552-43fe-8806-30324c8f5df4)
(Text on screen = Connecting to the world)
Absolutely on ever replays, and versions 1.18.2/1.19.4.
**Logs:**
[latest.log](https://github.com/ReplayMod/ReplayMod/files/11472621/latest.log)
**List of mods:**
- Sodium (Sodium Extra and Sodium Reeses Options)
- ReplayMod 2.6.11(12 has the same problem)
- ModMenu
- Litematica
- JourneyMap
- Iris
- InGameAccountSwitcher
- Fabric API
- Dynamic Crosshair
- Cloth-Config
- ChunkAnimator
- Borderless Mining
- Bobby (enabled and disabled have problem)
- AdvancedCompass

**Comment by Kepler-17c** [comment]
Try without AdvancedCompass - if the issue persists, please use our official support Discord (invite link on <https://www.replaymod.com/>)
