### ISSUE TITLE
Crashing during render

### ISSUE THREAD

**Issue by wereretot** [ReplayMod/ReplayMod#850]
When attempting to render it will only render 3 frames then crash.
[Log.txt](https://github.com/ReplayMod/ReplayMod/files/11537655/Log.txt)

**Comment by Kepler-17c** [comment]
Flatpak comes with its own version of FFmpeg, which has a reduced feature set. You need to make the FFmpeg from your package manager available to Flatpak or run a non-Flatpak version of your launcher.

If issues persist, please use our official support Discord (invite link on our website).

**Comment by wereretot** [comment]
Alright, using a non-flatpak version of prism launcher solved the issue.
