### ISSUE TITLE
Using linear and cubic interpolators at the same time makes things weird

### ISSUE THREAD

**Issue by MatinButNot** [ReplayMod/ReplayMod#852]
Using only one of the linear or cubic interpolations work perfectly, but this problem happens when I want to use both interpolations in one recording. The thing that happens is that all of the cubic interpolations after a linear interpolation look extremely weird. Look at this image (the red circle is the linear interpolation, and all others are cubic):
  
![image](https://github.com/ReplayMod/ReplayMod/assets/125367193/63d1dcba-22f0-436a-9c71-533a6ca1d423)

I'm on Minecraft 1.19.4

**Comment by Kepler-17c** [comment]
An interpolator can only ever be applied to a section of keyframes with the same interpolator, not across sections with different interpolators. It is near impossible to create an interpolator that combines other interpolators in an arbitrary order. That's why each section behaves as if the surrounding sections don't exist.

**Comment by MatinButNot** [comment]
It's ok I think. But the reason that I wanted to do this (not mentioned in the picture), was to make the camera just stand in a place for a while and not move. This was not possible for cubic scenes (the camera was not static and was kinda moving because of cubic), so this came into my mind. Is it a way to make the camera have "no movement" for a while in between cubic interpolators? I'm pretty sure it should be because it is extremely important. You know, there's no movie that the camera is always moving around in its scenes 😅

**Comment by Kepler-17c** [comment]
Do you mean a behaviour like a camera dolly slowing down, staying still for a moment, then continuing?
That would require separating the camera position and movement. More feasible than a mixable interpolator, but it creates other issues:
What would be a good GUI for that?

**Comment by MatinButNot** [comment]
So do you mean that in a cubic scene, there's no way to make the camera just stay somewhere for a while?
