### ISSUE TITLE
Support for 1.20

### ISSUE THREAD

**Issue by SorkoPiko** [ReplayMod/ReplayMod#855]
1.20 came out pretty recently. I hoped to use replay mod on the new version, but there is no version for 1.20. Please update ASAP. Thanks!

**Comment by AkarinLiu** [comment]
Yes, I need This Mod to recording video, and using DaVinci Resolve Software Make video by BlackMagicDesign. @Johni0702

**Comment by PandaUprising** [comment]
Mods Like this take time to update, I am sure the devs are working hard to get it up to day, in the meantime please be patient.

**Comment by SorkoPiko** [comment]
We're not rushing them, I asked for this a while back and I know they are aware of it.

**Comment by iambeingtracked** [comment]
The 1.19.4 "works" on Minecraft 1.20.1 but I can't even configure it. The mod is there but it just doesn't function

**Comment by Vadym-beep** [comment]
what if someone can port it to 1.20? I've been thinking about porting it

**Comment by SorkoPiko** [comment]
Thank you so much!
