### ISSUE TITLE
Feature: record sounds

### ISSUE THREAD

**Issue by MHYCWasTaken** [ReplayMod/ReplayMod#857]
Is there any possible to record sounds in records and export it into mp4 file?

**Comment by Kepler-17c** [comment]
Resolved in Discord - can be closed

**Comment by MHYCWasTaken** [comment]
Discord:
Marius (CrushedPixel) — 2020/05/12 03:41
a bit of background why this isn't a part of the ReplayMod: first of all, Minecraft's sound engine is terrible, I've looked into it when first creating the mod and there wasn't a remotely nice way of solving this. Secondly, it'd sound very weird when videos aren't in real-time, i.e. the audio would need to be slowed down or sped up.
