### ISSUE TITLE
Crash (or killed?) trying to render.

### ISSUE THREAD

**Issue by Magicrafter13** [ReplayMod/ReplayMod#869]
When I attempt to render a camera path for one of my replays, it renders around 5 frames before Minecraft hard crashes. It's so bad that MultiMC is killed, as well as Lutris (which was used to launch MultiMC). I tried running it in a terminal to see if I could get some useful output, but it killed the damn terminal as well. I really don't know what could cause that.

export.log doesn't seem to have anything of note:
```
gamemodeauto: 
ffmpeg version n6.0 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 13.1.1 (GCC) 20230429
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libjxl --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-opencl --enable-opengl --enable-shared --enable-version3 --enable-vulkan
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
```

here's my latest log file, which despite everything that happens, does get saved:
https://paste.ee/p/OPPlx

**Comment by RaderRMT** [comment]
You are rendering with x8 AA, either set it to x2 or don't use it at all

**Comment by Kepler-17c** [comment]
High anti-aliasing requires lots of RAM, because ReplayMod renders at higher resolutions and tells FFmpeg to smooth-scale down to the target resolution. You can try how much your system can handle by assigning more RAM and trying the different AA settings.

**Comment by Magicrafter13** [comment]
is 16 GiB not enough? I can try 24...
also I'm fairly certain I tried without anti-aliasing at some point but I could be wrong.
