### ISSUE TITLE
1.20.2 support

### ISSUE THREAD

**Issue by ancap-kun** [ReplayMod/ReplayMod#905]

**Comment by Akul2010** [comment]
It's always a few weeks behind for the people who don't pay.

**Comment by cyberaspect** [comment]
not an issue

**Comment by 3TaeTae** [comment]
when will it release?

**Comment by KrisDreemurr1** [comment]
> It's always a few weeks behind for the people who don't pay.

it does release tho right?

**Comment by TiboOpGithub** [comment]
When will it update?

**Comment by Unknown303YT** [comment]
@CrushedPixel Yeah, when will it be updated to 1.20.2 for the public?

**Comment by Unknown303YT** [comment]
> It's always a few weeks behind for the people who don't pay.

Its been 2 months, and NOTHING???? Is it going to happen, and when?

**Comment by wgaylord** [comment]
Any progress on adding 1.20.2 support?

**Comment by yupyuptrp** [comment]
is there any progress? it's been 2 months and i really need it

**Comment by ancap-kun** [comment]
Maybe fork it?

**Comment by tomasalias** [comment]
pls update to 1.20.2

**Comment by Onako2** [comment]
> Please add the 1.20.2 support. The 1.20.4 has already finished

Pay the developers on Patreon and you will recieve it earlier. For everyone else: Patience is the key

**Comment by Unknown303YT** [comment]
> > Please add the 1.20.2 support. The 1.20.4 has already finished
> 
> Pay the developers on Patreon and you will recieve it earlier. For everyone else: Patience is the key

We know, the problem is, we need this for things like YouTube Videos. I personally use replay mod to make some of my thumbnails, but I can't.

**Comment by wgaylord** [comment]
> > > Please add the 1.20.2 support. The 1.20.4 has already finished
> > 
> > 
> > Pay the developers on Patreon and you will recieve it earlier. For everyone else: Patience is the key
> 
> We know, the problem is, we need this for things like YouTube Videos. I personally use replay mod to make some of my thumbnails, but I can't.

If your using it on a server, you can always use ViaVersion to connect with 1.20.1

**Comment by JohnSmith192** [comment]
> > > > Please add the 1.20.2 support. The 1.20.4 has already finished
> > > 
> > > 
> > > Pay the developers on Patreon and you will recieve it earlier. For everyone else: Patience is the key
> > 
> > 
> > We know, the problem is, we need this for things like YouTube Videos. I personally use replay mod to make some of my thumbnails, but I can't.
> 
> If your using it on a server, you can always use ViaVersion to connect with 1.20.1

Thank you. I will be more patient. And I will use ViaVersion on my server.
