### ISSUE TITLE
Visual errors with Item Display Entities

### ISSUE THREAD

**Issue by Shyvvi** [ReplayMod/ReplayMod#913]
Whenever the position of an Item Display Entity is updated with Replay Mod on your client, a visual error occurs between the updated position of the Item Display Entity, and its initial position.

**Comment by Shyvvi** [comment]
https://github.com/ReplayMod/ReplayMod/assets/131827772/8bd90c67-5315-4ebe-96cd-ef01f58f7bd5

Here is a video of the issue described, the particles are where the display entities are meant to be, I hope this issue gets noticed and I hope this helps

**Comment by Johni0702** [comment]
Duplicate of #846
