### ISSUE TITLE
Issue with the ReplayMod and FancyMenu

### ISSUE THREAD

**Issue by invicniclb** [ReplayMod/ReplayMod#919]
So basically i have an issue that whenever i put BIG on the code list, 2 buttons appear on the fancymenu, and i can't move none of them.

**Comment by Johni0702** [comment]
ReplayMod as of 2.6.13 should have no more problems with recent versions of FancyMenu (and there's no need to use the BIG button).
If you do still have issues, please give more details such as the versions of Minecraft, ReplayMod and FancyMenu you're using, as well as your FancyMenu config and any other mods required to reproduce the issue.
