### ISSUE TITLE
Please add forge support

### ISSUE THREAD

**Issue by michelle1574** [ReplayMod/ReplayMod#920]
If you don't want to add forge, then please provide me with recording mods for minecraft.

**Comment by Syhmac** [comment]
There will be no support for Forge. And no one here is required to provide you anything. There is a thing called "Google", "Yahoo", "Bing" or "Duck duck go". You have all tools required to find what you want.

**Comment by seacat17** [comment]
> There will be no support for Forge. And no one here is required to provide you anything. There is a thing called "Google", "Yahoo", "Bing" or "Duck duck go". You have all tools required to find what you want.

Still no recording mods for Forge 1.20.1. I am making this huge video project about TerraFirmaCraft 1.20.1 and TFC is Forge only. I am not gonna have 3rd person shots, am I?

**Comment by Syhmac** [comment]
You can create 3rd person shots by having two instances on Minecraft open at the same time. Hope that helps.
