### ISSUE TITLE
Replay mod and Item Swapper mod incompatibility

### ISSUE THREAD

**Issue by PreachyWheat897** [ReplayMod/ReplayMod#922]
I use a multitude of mods (~80). I tried adding replay mod "replaymod-1.20.2-2.6.14"  to my list of mods and the game crashed during bootup. I compartmentalized and found that the Item Swapper mod "itemswapper-fabric-0.5.4-mc1.20.2" and the replay mod cause a crash when they are both in my mods folder.

Link to the Item Swapper Modrinth page: https://modrinth.com/plugin/itemswapper

**Comment by Johni0702** [comment]
Please attach the log file (`.minecraft/logs/latest.log`) that contains the crash.

**Comment by PreachyWheat897** [comment]
[latest.log](https://github.com/ReplayMod/ReplayMod/files/13670313/latest.log)

**Comment by Johni0702** [comment]
You're using an old version of itemswapper, this has been fixed in version 0.5.5: https://github.com/tr7zw/ItemSwapper/issues/187

ReplayMod includes some parts of fabric-api 0.91.2, hence why it breaks when you add it.

**Comment by PreachyWheat897** [comment]
Just tested and it works, thank you!
