### ISSUE TITLE
Crash when pressing "Render"

### ISSUE THREAD

**Issue by schnow265** [ReplayMod/ReplayMod#937]
The Game crashes when I try to render my camera path. I am using Fedora Linux 39 and the ffmpeg binary from RPMFusion, which includes nonfree codecs. [This is the crashlog](https://mclo.gs/TnQJCcL). I used Prism Launcher over Flatpak and gave it every permission possible.

**Comment by RaderRMT** [comment]
Your ffmpeg wasn't built with libx264 enabled. Please find one that was compiled with libx264 enabled and try again.

**Comment by schnow265** [comment]
Yeah, built ffmpeg from source with all libs enabled and also installed Prism from the rpm. It is currently rendering.

**Comment by Casssiee11** [comment]
Whenever I click render it will show up for a second before crashing and closing out. do you have any suggestions on what to do? I tried everything I've seen people being responded to.



[crashlog.txt](https://github.com/user-attachments/files/18842191/crashlog.txt)
