### ISSUE TITLE
Issue with Modpack

### ISSUE THREAD

**Issue by SanMiguelZ** [ReplayMod/ReplayMod#938]
Hello, i have an issue when installing Replay mod with other mods.

Using the modpack without replay mod works fine, but when i install it, it completely crashes. 
I dont know what the cause of this could be, and im not good at reading logs.

Whoever can help me with this i will be very grateful to! 

The pastebin of the Log i have. [https://pastebin.com/PdS2mNHR](url)

**Comment by RaderRMT** [comment]
You are not using the official ReplayMod. Report this issue to whoever made the forge port.
