### ISSUE TITLE
Forge 1.18.2

### ISSUE THREAD

**Issue by mrGRINCH** [ReplayMod/ReplayMod#939]
Could we please get a 1.18.2 version for Forge.

**Comment by Syhmac** [comment]
No. Replay Mod does not support forge anymore and will NOT support it.

**Comment by mrGRINCH** [comment]
No worries, thanks for the reply.

Do you happen to know of any Forge alternative? I'm playing a Forge modpack at the moment and have some stuff I'd like to time lapse.
