### ISSUE TITLE
Game crashes when trying to apply a split on the main menu

### ISSUE THREAD

**Issue by SubayAdamm** [ReplayMod/ReplayMod#940]
Hello, I am playing on 1.20.1 with the [Sinytra Connector](https://modrinth.com/mod/connector) mod installed, I've recorded a 1 hour and 30 minutes replay recording, but while trying to split it up, the game crashes and I cannot go past the 65th minute mark, which I assume is because of the length of the recording.

Here is the crash report;
`---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2024-02-27 21:29:56
Description: Running marker processor

java.io.EOFException: null
	at com.replaymod.replaystudio.io.ReplayInputStream.fillBuffer(ReplayInputStream.java:159) ~[replaymod-1.20.1-2.6.14_mapped_srg_1.20.1.jar%23332!/:?] {re:classloading}
	at com.replaymod.replaystudio.io.ReplayInputStream.readPacket(ReplayInputStream.java:140) ~[replaymod-1.20.1-2.6.14_mapped_srg_1.20.1.jar%23332!/:?] {re:classloading}
	at com.replaymod.editor.gui.MarkerProcessor.apply(MarkerProcessor.java:224) ~[replaymod-1.20.1-2.6.14_mapped_srg_1.20.1.jar%23332!/:?] {re:classloading}
	at com.replaymod.editor.gui.GuiEditReplay.lambda$apply$12(GuiEditReplay.java:164) ~[replaymod-1.20.1-2.6.14_mapped_srg_1.20.1.jar%23332!/:?] {re:classloading}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {re:mixin}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2387121880 bytes (2276 MiB) / 5033164800 bytes (4800 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz
	Identifier: Intel64 Family 6 Model 167 Stepping 1
	Microarchitecture: Rocket Lake
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 3060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2487
	Graphics card #0 versionInfo: DriverVersion=31.0.15.4633
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.00
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.00
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 39185.21
	Virtual memory used (MB): 30954.39
	Swap memory total (MB): 22931.89
	Swap memory used (MB): 1526.61
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Loaded Shaderpack: ComplementaryReimagined_r5.1.1.zip
		Profile: VERYHIGH (+2 options changed by user)
	Sinytra Connector: 1.0.0-beta.36+1.20.1
		SINYTRA CONNECTOR IS PRESENT!
		Please verify issues are not caused by Connector before reporting them to mod authors. If you're unsure, file a report on Connector's issue tracker.
		Connector's issue tracker can be found at https://github.com/Sinytra/Connector/issues.
		Installed Fabric mods:
		| ================================================== | ============================== | ============================== | ==================== |
		| boosted-brightness-2.2.01.20.1_mapped_srg_1.20.1.j | Boosted Brightness             | boostedbrightness              | 2.2.0                |
		| replaymod-1.20.1-2.6.14_mapped_srg_1.20.1.jar      | Replay Mod                     | replaymod                      | 1.20.1-2.6.14        |
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.2.20.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.20.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.2.20.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.2.20.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.20.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar essential-loader TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar mixin-transmogrifier TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar connector_loader TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
		lowcodefml@null
	Mod List: 
		fabric-transfer-api-v1-3.3.3+b00938ec77.jar       |Fabric Transfer API (v1)      |fabric_transfer_api_v1        |3.3.3+b00938ec77    |DONE      |Manifest: NOSIGNATURE
		fabric-dimensions-v1-2.1.53+8005d10d77.jar        |Fabric Dimensions API (v1)    |fabric_dimensions_v1          |2.1.53+8005d10d77   |DONE      |Manifest: NOSIGNATURE
		fabric-renderer-api-v1-3.2.0+1d29b44577.jar       |Fabric Renderer API (v1)      |fabric_renderer_api_v1        |3.2.0+1d29b44577    |DONE      |Manifest: NOSIGNATURE
		fabric-model-loading-api-v1-1.0.2+3a78c72c77.jar  |Fabric Model Loading API (v1) |fabric_model_loading_api_v1   |1.0.2+3a78c72c77    |DONE      |Manifest: NOSIGNATURE
		fabric-item-api-v1-2.1.27+2272fc7f77.jar          |Fabric Item API (v1)          |fabric_item_api_v1            |2.1.27+2272fc7f77   |DONE      |Manifest: NOSIGNATURE
		kubejs-bridge-1.9.2+1.20.1.jar                    |Connector Extras KubeJS Bridge|connectorextras_kubejs_bridge |1.9.2+1.20.1        |DONE      |Manifest: NOSIGNATURE
		fabric-rendering-fluids-v1-3.0.27+4ac5e37a77.jar  |Fabric Rendering Fluids (v1)  |fabric_rendering_fluids_v1    |3.0.27+4ac5e37a77   |DONE      |Manifest: NOSIGNATURE
		fabric-screen-handler-api-v1-1.3.29+561530ec77.jar|Fabric Screen Handler API (v1)|fabric_screen_handler_api_v1  |1.3.29+561530ec77   |DONE      |Manifest: NOSIGNATURE
		fabric-resource-loader-v0-0.11.9+142e25ab77.jar   |Fabric Resource Loader (v0)   |fabric_resource_loader_v0     |0.11.9+142e25ab77   |DONE      |Manifest: NOSIGNATURE
		fabric-models-v0-0.4.1+7c3892a477.jar             |Fabric Models (v0)            |fabric_models_v0              |0.4.1+7c3892a477    |DONE      |Manifest: NOSIGNATURE
		fabric-rendering-v1-3.0.7+1c0ea72177.jar          |Fabric Rendering (v1)         |fabric_rendering_v1           |3.0.7+1c0ea72177    |DONE      |Manifest: NOSIGNATURE
		fabric-renderer-indigo-1.5.0+67f9824077.jar       |Fabric Renderer - Indigo      |fabric_renderer_indigo        |1.5.0+67f9824077    |DONE      |Manifest: NOSIGNATURE
		fabric-convention-tags-v1-1.5.4+fa3d1c0177.jar    |Fabric Convention Tags        |fabric_convention_tags_v1     |1.5.4+fa3d1c0177    |DONE      |Manifest: NOSIGNATURE
		fabric-mining-level-api-v1-2.1.49+561530ec77.jar  |Fabric Mining Level API (v1)  |fabric_mining_level_api_v1    |2.1.49+561530ec77   |DONE      |Manifest: NOSIGNATURE
		fabric-command-api-v1-1.2.33+f71b366f77.jar       |Fabric Command API (v1)       |fabric_command_api_v1         |1.2.33+f71b366f77   |DONE      |Manifest: NOSIGNATURE
		fabric-command-api-v2-2.2.12+561530ec77.jar       |Fabric Command API (v2)       |fabric_command_api_v2         |2.2.12+561530ec77   |DONE      |Manifest: NOSIGNATURE
		fabric-block-view-api-v2-1.0.0+0767707077.jar     |Fabric BlockView API (v2)     |fabric_block_view_api_v2      |1.0.0+0767707077    |DONE      |Manifest: NOSIGNATURE
		mixinextras-forge-0.3.5.jar                       |MixinExtras                   |mixinextras                   |0.3.5               |DONE      |Manifest: NOSIGNATURE
		rei-bridge-1.9.2+1.20.1.jar                       |Connector Extras REI Bridge   |connectorextras_rei_bridge    |1.9.2+1.20.1        |DONE      |Manifest: NOSIGNATURE
		geckolib-fabric-compat-1.9.2+1.20.1.jar           |Connector Extras Geckolib-Fabr|connectorextras_geckolib_fabri|1.9.2+1.20.1        |DONE      |Manifest: NOSIGNATURE
		continuity-compat-1.9.2+1.20.1.jar                |Connector Extras Continuity Co|connectorextras_continuity_com|1.9.2+1.20.1        |DONE      |Manifest: NOSIGNATURE
		boosted-brightness-2.2.01.20.1_mapped_srg_1.20.1.j|Boosted Brightness            |boostedbrightness             |2.2.0               |DONE      |Manifest: NOSIGNATURE
		fabric-screen-api-v1-2.0.7+45a670a577.jar         |Fabric Screen API (v1)        |fabric_screen_api_v1          |2.0.7+45a670a577    |DONE      |Manifest: NOSIGNATURE
		energy-bridge-1.9.2+1.20.1.jar                    |Connector Extras Energy Bridge|connectorextras_energy_bridge |1.9.2+1.20.1        |DONE      |Manifest: NOSIGNATURE
		fabric-particles-v1-1.1.1+78e1ecb877.jar          |Fabric Particles (v1)         |fabric_particles_v1           |1.1.1+78e1ecb877    |DONE      |Manifest: NOSIGNATURE
		forge-1.20.1-47.2.20-universal.jar                |Forge                         |forge                         |47.2.20             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		fabric-api-0.91.0+1.10.8+1.20.1.jar               |Forgified Fabric API          |fabric_api                    |0.91.0+1.10.8+1.20.1|DONE      |Manifest: NOSIGNATURE
		modmenu-bridge-1.9.2+1.20.1.jar                   |Connector Extras ModMenu Bridg|connectorextras_modmenu_bridge|1.9.2+1.20.1        |DONE      |Manifest: NOSIGNATURE
		fabric-content-registries-v0-4.0.10+a670df1e77.jar|Fabric Content Registries (v0)|fabric_content_registries_v0  |4.0.10+a670df1e77   |DONE      |Manifest: NOSIGNATURE
		konkrete_forge_1.8.0_MC_1.20-1.20.1.jar           |Konkrete                      |konkrete                      |1.8.0               |DONE      |Manifest: NOSIGNATURE
		embeddium-0.3.1+mc1.20.1.jar                      |Embeddium                     |embeddium                     |0.3.1+mc1.20.1      |DONE      |Manifest: NOSIGNATURE
		fabric-transitive-access-wideners-v1-4.3.0+1880499|Fabric Transitive Access Widen|fabric_transitive_access_widen|4.3.0+1880499877    |DONE      |Manifest: NOSIGNATURE
		terrablender-bridge-1.9.2+1.20.1.jar              |Connector Extras Terrablender |connectorextras_terrablender_b|1.9.2+1.20.1        |DONE      |Manifest: NOSIGNATURE
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		fabric-game-rule-api-v1-1.0.39+461110ab77.jar     |Fabric Game Rule API (v1)     |fabric_game_rule_api_v1       |1.0.39+461110ab77   |DONE      |Manifest: NOSIGNATURE
		fabric-api-base-0.4.30+ef105b4977.jar             |Fabric API Base               |fabric_api_base               |0.4.30+ef105b4977   |DONE      |Manifest: NOSIGNATURE
		fabric-api-lookup-api-v1-1.6.35+67f9824077.jar    |Fabric API Lookup API (v1)    |fabric_api_lookup_api_v1      |1.6.35+67f9824077   |DONE      |Manifest: NOSIGNATURE
		fabric-blockrenderlayer-v1-1.1.40+1d0da21e77.jar  |Fabric BlockRenderLayer Regist|fabric_blockrenderlayer_v1    |1.1.40+1d0da21e77   |DONE      |Manifest: NOSIGNATURE
		amecsapi-1.5.3+mc1.20-pre1.jar                    |Amecs API                     |amecsapi                      |1.5.3+mc1.20-pre1   |DONE      |Manifest: NOSIGNATURE
		fabric-block-api-v1-1.0.10+0e6cb7f777.jar         |Fabric Block API (v1)         |fabric_block_api_v1           |1.0.10+0e6cb7f777   |DONE      |Manifest: NOSIGNATURE
		jei-bridge-1.9.2+1.20.1.jar                       |Connector Extras JEI Bridge   |connectorextras_jei_bridge    |1.9.2+1.20.1        |DONE      |Manifest: NOSIGNATURE
		fabric-resource-conditions-api-v1-2.3.7+9ad825cd77|Fabric Resource Conditions API|fabric_resource_conditions_api|2.3.7+9ad825cd77    |DONE      |Manifest: NOSIGNATURE
		reach-entity-attributes-2.4.0.jar                 |Reach Entity Attributes       |reach_entity_attributes       |2.4.0               |DONE      |Manifest: NOSIGNATURE
		forgeconfigapiport-1.9.2+1.20.1.jar               |Forge Config API Port (Connect|forgeconfigapiport            |8.0.0               |DONE      |Manifest: NOSIGNATURE
		architectury-bridge-1.9.2+1.20.1.jar              |Connector Extras Architectury |connectorextras_architectury_b|1.9.2+1.20.1        |DONE      |Manifest: NOSIGNATURE
		oculus-mc1.20.1-1.6.15.jar                        |Oculus                        |oculus                        |1.6.15              |DONE      |Manifest: NOSIGNATURE
		fabric-item-group-api-v1-4.0.11+f687ac9377.jar    |Fabric Item Group API (v1)    |fabric_item_group_api_v1      |4.0.11+f687ac9377   |DONE      |Manifest: NOSIGNATURE
		replaymod-1.20.1-2.6.14_mapped_srg_1.20.1.jar     |Replay Mod                    |replaymod                     |1.20.1-2.6.14       |DONE      |Manifest: NOSIGNATURE
		witherstormmod-1.20.1-4.0.1.1.jar                 |Cracker's Wither Storm Mod    |witherstormmod                |4.0.1.1             |DONE      |Manifest: NOSIGNATURE
		Connector-1.0.0-beta.36+1.20.1-mod.jar            |Connector                     |connectormod                  |1.0.0-beta.36+1.20.1|DONE      |Manifest: NOSIGNATURE
		fabric-biome-api-v1-13.0.12+dd0389a577.jar        |Fabric Biome API (v1)         |fabric_biome_api_v1           |13.0.12+dd0389a577  |DONE      |Manifest: NOSIGNATURE
		fabric-entity-events-v1-1.5.22+b909fbe377.jar     |Fabric Entity Events (v1)     |fabric_entity_events_v1       |1.5.22+b909fbe377   |DONE      |Manifest: NOSIGNATURE
		fabric-registry-sync-v0-2.3.2+1c0ea72177.jar      |Fabric Registry Sync (v0)     |fabric_registry_sync_v0       |2.3.2+1c0ea72177    |DONE      |Manifest: NOSIGNATURE
		fabric-recipe-api-v1-1.0.20+514a076577.jar        |Fabric Recipe API (v1)        |fabric_recipe_api_v1          |1.0.20+514a076577   |DONE      |Manifest: NOSIGNATURE
		fabric-object-builder-api-v1-11.1.2+2174fc8477.jar|Fabric Object Builder API (v1)|fabric_object_builder_api_v1  |11.1.2+2174fc8477   |DONE      |Manifest: NOSIGNATURE
		fabric-loot-api-v2-1.2.0+eb28f93e77.jar           |Fabric Loot API (v2)          |fabric_loot_api_v2            |1.2.0+eb28f93e77    |DONE      |Manifest: NOSIGNATURE
		rubidium-extra-0.5.4+mc1.20.1-build.116.jar       |Embeddium Extra               |embeddium_extra               |0.5.4+mc1.20.1-build|DONE      |Manifest: NOSIGNATURE
		ConnectorExtras-1.9.2+1.20.1.jar                  |Connector Extras              |connectorextras               |1.9.2+1.20.1        |DONE      |Manifest: NOSIGNATURE
		fabric-rendering-data-attachment-v1-0.3.36+a6081af|Fabric Rendering Data Attachme|fabric_rendering_data_attachme|0.3.36+a6081afc77   |DONE      |Manifest: NOSIGNATURE
		justzoom_forge_1.0.2_MC_1.20.1.jar                |Just Zoom                     |justzoom                      |1.0.2               |DONE      |Manifest: NOSIGNATURE
		fabric-networking-api-v1-1.3.10+503a202477.jar    |Fabric Networking API (v1)    |fabric_networking_api_v1      |1.3.10+503a202477   |DONE      |Manifest: NOSIGNATURE
		fabric-sound-api-v1-1.0.12+4f23bd8477.jar         |Fabric Sound API (v1)         |fabric_sound_api_v1           |1.0.12+4f23bd8477   |DONE      |Manifest: NOSIGNATURE
		fabric-message-api-v1-5.1.8+52cc178c77.jar        |Fabric Message API (v1)       |fabric_message_api_v1         |5.1.8+52cc178c77    |DONE      |Manifest: NOSIGNATURE
		emi-bridge-1.9.2+1.20.1.jar                       |Connector Extras EMI Bridge   |connectorextras_emi_bridge    |1.9.2+1.20.1        |DONE      |Manifest: NOSIGNATURE
		fabric-lifecycle-events-v1-2.2.21+afab492177.jar  |Fabric Lifecycle Events (v1)  |fabric_lifecycle_events_v1    |2.2.21+afab492177   |DONE      |Manifest: NOSIGNATURE
		fabric-data-generation-api-v1-12.3.3+369cb3a477.ja|Fabric Data Generation API (v1|fabric_data_generation_api_v1 |12.3.3+369cb3a477   |DONE      |Manifest: NOSIGNATURE
		fabric-events-interaction-v0-0.6.1+0d0bd5a777.jar |Fabric Events Interaction (v0)|fabric_events_interaction_v0  |0.6.1+0d0bd5a777    |DONE      |Manifest: NOSIGNATURE
		fabric-key-binding-api-v1-1.0.36+561530ec77.jar   |Fabric Key Binding API (v1)   |fabric_key_binding_api_v1     |1.0.36+561530ec77   |DONE      |Manifest: NOSIGNATURE
		Essential (forge_1.20.1).jar                      |Essential                     |essential                     |1.3.0.6+g4dc55a95bd |DONE      |Manifest: NOSIGNATURE
		fabric-client-tags-api-v1-1.1.1+5d6761b877.jar    |Fabric Client Tags            |fabric_client_tags_api_v1     |1.1.1+5d6761b877    |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 88694bc2-c6da-4c07-9c0f-367d6ea994ce
	FML: 47.2
	Forge: net.minecraftforge:47.2.20`

**Comment by RaderRMT** [comment]
The ReplayMod on any version that is newer than 1.12.2 is fabric only. As you're using a fabric version on forge through a connector, report this issue to the connector's maintainer.

**Comment by SubayAdamm** [comment]
Will do, appreciate it.

**Comment by SubayAdamm** [comment]
With some more testing, I've realized that the issue is not on the connector mod, as I tried to split the replay on the Fabric version, without opening the replay. It crashed again and gave me this code (Tried this on a different PC.)

I really need this replay recording, so any help is appreciated.

``---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2024-02-29 10:56:38
Description: Running marker processor

java.io.EOFException
	at com.replaymod.replaystudio.io.ReplayInputStream.fillBuffer(ReplayInputStream.java:159)
	at com.replaymod.replaystudio.io.ReplayInputStream.readPacket(ReplayInputStream.java:140)
	at com.replaymod.editor.gui.MarkerProcessor.apply(MarkerProcessor.java:224)
	at com.replaymod.editor.gui.GuiEditReplay.lambda$apply$12(GuiEditReplay.java:164)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1489117784 bytes (1420 MiB) / 2013265920 bytes (1920 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i5-12500H
	Identifier: Intel64 Family 6 Model 154 Stepping 3
	Microarchitecture: Alder Lake
	Frequency (GHz): 3.11
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 16
	Graphics card #0 name: Intel(R) Iris(R) Xe Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x46a6
	Graphics card #0 versionInfo: DriverVersion=31.0.101.3358
	Graphics card #1 name: NVIDIA GeForce RTX 3050 Ti Laptop GPU
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x25a0
	Graphics card #1 versionInfo: DriverVersion=31.0.15.3623
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 30424.49
	Virtual memory used (MB): 24335.42
	Swap memory total (MB): 14336.00
	Swap memory used (MB): 961.74
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric-api: Fabric API 0.92.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.1+1802ada577
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.4+1802ada577
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabricloader: Fabric Loader 0.15.7
			mixinextras: MixinExtras 0.3.5
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.20.1
		replaymod: Replay Mod 1.20.1-2.6.14
		sodium: Sodium 0.5.8+mc1.20.1``

**Comment by RaderRMT** [comment]
Was this replay recorded on fabric? If not, try with a replay you recorded on fabric.

**Comment by SubayAdamm** [comment]
The replay was recorded on forge, I will try it in a few hours because I don't have any recordings on this PC.

**Comment by SubayAdamm** [comment]
Okay so I splitted a recording of same length on fabric 1.20.1, no errors, it splits the recording. 

Well, I guess there is something with the connector, but it is weird that the replay recording crashes while trying to split even without the connector mod being used.

**Comment by Johni0702** [comment]
> Well, I guess there is something with the connector, but it is weird that the replay recording crashes while trying to split even without the connector mod being used.

Doesn't seem weird to me. It's not the splitting that's broken, it's the recording. If Forge messes with the recording process in a way that sometimes produces invalid replays, then those will ofc still be invalid if you try to split them even on Fabric, at that point the loader doesn't matter.
