### ISSUE TITLE
Won’t load Replay

### ISSUE THREAD

**Issue by TheEpicTen** [ReplayMod/ReplayMod#946]
I have recorded a 15 minute replay. When looking in the replay viewer, there are no thumbnails, and when I load the replay, it gets stuck on “Joining World”. If I click anywhere, it crashes. Running with Sodium and Lithium installed doesn’t help. I really need the contents of this replay. Please help!

**Comment by TheEpicTen** [comment]
UPDATE: Will try using fabric standalone, as I’m currently using CurseForge.

**Comment by JohnSmith192** [comment]
I have the same problem. For me, it happened when I use bungeecord to swtich server and restart recording.

**Comment by TheEpicTen** [comment]
UPDATE: Same issue with using standalone fabric. I'll try with no other mods soon.

**Comment by JohnSmith192** [comment]
UPDATE:I tried it before. The issue won't disappear

**Comment by Johni0702** [comment]
There should be an uncut version of your replay in `.minecraft/replay_recordings/raw/`, please move that up one folder so it appears ingame and try that instead.
If it works, please consider attaching the file to this issue so I can debug it.

**Comment by TheEpicTen** [comment]
Trying that now.

**Comment by JohnSmith192** [comment]
> There should be an uncut version of your replay in `.minecraft/replay_recordings/raw/`, please move that up one folder so it appears ingame and try that instead. If it works, please consider attaching the file to this issue so I can debug it.

It works. I have attached the files.
[Uploading replay_recordings.zip…]()

**Comment by Johni0702** [comment]
You posted your message before the files were done uploading.

**Comment by JohnSmith192** [comment]
[replay_recordings.zip](https://github.com/ReplayMod/ReplayMod/files/14545862/replay_recordings.zip)

**Comment by kittycattart-design** [comment]
could anyone help me with mine? mine is also broken and i dont know what to do
