### ISSUE TITLE
Replay Mod is incompatible with ViaFabric / ViaFabricPlus

### ISSUE THREAD

**Issue by Kichura** [ReplayMod/ReplayMod#972]
### Client logs

The client logs can be found [here](https://pastebin.com/raw/c1ugQ2y8).

### Bug Description

When attempting to start up a new 1.20.4 instance that already has ViaFabric / ViaFabricPlus on it, including Replay Mod into the mods list will break ViaVersion's initialization system entirely.

### Steps to Reproduce

1. Make a new 1.20.6 client instance that has fabric loader and API installed,
2. Install the latest ViaFabric or ViaFabricPlus mod from modrinth, *(main version of VF is preferred for stability)*
3. Include Replay Mod in the mods list,
4. Crash.

### Expected Behavior

Replay Mod and ViaFabric / ViaFabricPlus should work together properly.

**Comment by theMisterPhD** [comment]
[21:18:15] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.11
[21:18:16] [main/WARN]: Warnings were found!
 - Mod 'ViaBackwards' (viabackwards) 4.10.3-SNAPSHOT recommends any version of viarewind, which is missing!
	 - You should install any version of viarewind for the optimal experience.
	 

Have you tried including viarewind, as requested?

**Comment by Kichura** [comment]
> [21:18:15] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.11 [21:18:16] [main/WARN]: Warnings were found!
> 
>     * Mod 'ViaBackwards' (viabackwards) 4.10.3-SNAPSHOT recommends any version of viarewind, which is missing!
>       
>       * You should install any version of viarewind for the optimal experience.
> 
> 
> Have you tried including viarewind, as requested?

this is not required as viabackwards itself optionally wants this in case the end-user needs 1.8.9 client support.

**Comment by Timokaproka** [comment]
In version 2.6.17 everything works correctly

**Comment by Kichura** [comment]
Fixed, Update replaymod to 2.6.16 or newer.
