### ISSUE TITLE
Forge 1.18.2 please

### ISSUE THREAD

**Issue by quanghuy2013** [ReplayMod/ReplayMod#996]
I have some mods that only work, supported forge only, I need the dev to work. Thanks

**Comment by Syhmac** [comment]
Too bad no-one cares. You can port this mod to Forge by yourself if you want. Johni is not going to do that.

**Comment by Syhmac** [comment]
And stop spamming issues

**Comment by quanghuy2013** [comment]
> And stop spamming issues

Then ask Johni pls
